<Project>
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj-*\**;Release-*\**;Debug-*\**</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'player-assistant'">
    <BaseIntermediateOutputPath>obj\player-assistant\</BaseIntermediateOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'DungeonMaster'">
    <BaseIntermediateOutputPath>obj\DungeonMaster\</BaseIntermediateOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'to-orcish'">
    <BaseIntermediateOutputPath>obj\to-orcish\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
