namespace PlayerAssistant
{
    internal static partial class OrcishTranslatorUtility
    {
        private const string VariousEbooksCorpusThirdSourceCandidateData = """
abaft
abdicated
abdication
abeam
abhorrent
abides
ablutions
acacia
acclamation
accusers
accuses
acquittal
acropolis
acumen
adjudged
adjutant-general
adobe
affray
agape
aggressor
agrarian
aides-de-camp
alder
alders
allotment
aloes
alum
ambrosia
amputated
anent
annulled
anomalous
antediluvian
apocryphal
apostate
appealingly
appetizing
apple-tree
aqueduct
aqueducts
arbitrarily
arraigned
arrow-heads
arsenic
artillerymen
ascendant
asceticism
aspen
assay
assimilated
atheism
attainable
augur
augurs
aver
avocations
awe-inspiring
bairn
bairns
banshee
baser
basilica
battle-cry
battlefields
bayou
beeves
befits
beginner
beleaguered
beneficence
benefices
benignant
bevy
bewail
bewailed
bewailing
bigoted
binnacle
black-eyed
blackberries
blacksmith's
blindfold
blindfolded
blockhouse
bluejackets
boat-hook
boded
boggy
bole
boo
boor
bouillon
bounden
bounteous
bowman
braggart
bras
breakwater
brevet
bridged
brigantine
brownish
browsing
bruin
buddy
bull-dog
burdensome
burgomaster
butte
caissons
calabash
camp-fires
camphor
cannibalism
canteens
cantering
canto
cantonments
canvass
caparisoned
capitulate
capitulated
captain-general
captaincy
carbuncle
cased
caterpillar
cavalrymen
centurion
chaplet
cheek-bones
chili
chirping
choral
chores
chow
churl
churlish
circumcision
clarion
clipper
coast-line
cockade
cocoa-nut
codex
collie
colonelcy
colonnade
combustible
comeliness
common-sense
companionway
concocted
concubine
concubines
conjectural
conning
connivance
convened
conveyances
corsairs
corvette
cote
counter-attack
countersign
courser
coursers
coxswain
craftily
crone
crossings
culinary
cumbrous
cupola
curia
cursory
curtailed
cynic
dappled
davits
day-break
debauch
decrepitude
defrauded
defunct
degeneracy
deified
delineated
demarcation
demented
demoniacal
denuded
deputed
derided
derrick
desperadoes
detract
detrimental
deviate
dictum
dilatory
dinghy
direful
disheartening
distaff
distortion
dizzily
dockyard
doctrinal
donor
doorkeeper
dour
dower
down-stream
dram
drear
droves
dub
duff
dug-out
dug-outs
dynastic
dysentery
earldom
easy-going
eatables
effulgence
elfin
embattled
embellishments
emblematic
emigrated
emir
enactments
encroachments
endued
entrap
entrapped
ephemeral
epicurean
escutcheon
eventide
ever-present
ewes
excruciating
execration
existent
exorcism
expiate
expiated
extraneous
eye-witnesses
factious
fagged
fagots
far-famed
far-seeing
fatherless
fervid
festal
fez
fief
field-pieces
fig-tree
finder
fire-place
fisher's
fishy
flag-ship
flagging
flagon
flagstaff
flamboyant
flat-topped
fleshly
floe
floes
floored
foal
folklore
foot-soldiers
footsore
foregone
forelock
foremen
forerunner
forfeiture
franc
frankincense
fraudulent
freebooters
freedman
freedmen
fresh-water
frisky
frost-bitten
fruit-trees
furtherance
fusillade
fuzzy
gaff
galore
general-in-chief
generalissimo
generalship
gloaming
godhead
godless
goldsmiths
granaries
granary
grandma
grape-shot
gray-haired
greensward
gridiron
gritted
groundwork
guard-house
gun-boats
gunnery
habituated
hackney
half-starved
hard-working
harm's
hauteur
haversack
headman
headpiece
headwaters
heart-breaking
heart-rending
hearths
heathenism
heavenward
heinous
herculean
hereof
high-born
hill-top
home-made
homespun
homicide
hot-headed
hummock
hummocks
hyacinth
idolaters
idolatrous
ill-treatment
immoderate
impaled
impartiality
imperishable
improbability
inboard
inculcated
indicted
infantrymen
informers
inshore
interdict
intermixed
interstices
inundated
invective
inviolate
irate
irreconcilable
itinerant
jabbering
jacks
jaguar
jasmine
jogging
jollity
juniper
jurors
kid's
knell
kraal
lading
lagging
laird
land's
landings
landward
lariat
lawgiver
laymen
leach
leader's
leaky
leaven
left-handed
leghorn
lengthwise
libation
libations
life-blood
life-giving
life-long
light-armed
limerick
line-of-battle
lisle
long-boat
long-continued
long-range
long-suffering
lough
luff
lugger
luminary
mackerel
magistracy
make-up
malcontents
malefactors
mammon
mango
marksmanship
mediator
medicine-man
meeting-place
mercer
messmates
metamorphosed
midland
midshipmen
mimosa
minarets
mink
minstrelsy
mistletoe
mizzen
moires
monarchical
monkish
monotheism
monseigneur
monsoon
mopping
moralist
moralists
mountain-side
multifarious
munificence
musketeers
muskrat
mustang
myrmidons
myrrh
nab
navel
nefarious
nerveless
neutrals
new-found
nimrod
non-existent
noontide
north-eastern
north-western
oak-tree
obligatory
obsequies
obviate
occupancy
octagonal
officiating
opponent's
outermost
outhouse
outwit
outworks
pack-horses
padlock
palanquin
palatial
palfrey
palm-tree
palsied
pampered
pancakes
papacy
paramour
parochial
parsley
passer-by
pathless
paymaster
pediment
peninsular
pennons
perennial
perpetuity
personified
pertinacity
pestered
pestilential
pests
petrel
piecemeal
pine-tree
pine-trees
pitfalls
plaint
plantain
plantains
pliable
plotters
polygamy
polytheism
poniard
pontoon
pontoons
portage
possum
posthumous
poverty-stricken
precocious
predilection
predominance
predominated
prejudicial
prig
primate
prize-money
prolongation
propagated
prophetess
proprietary
proscription
provender
pueblo
puerile
python
qualms
quartermaster's
queen-mother
quicksand
quinine
quizzical
quizzically
raccoon
ramifications
ramp
ramrod
rankled
rapacity
re-echoed
re-enter
re-establish
re-established
rearguard
reconnoiter
reconnoitering
reedy
remitted
repelling
reprehensible
reprobate
rescuer
rescuers
retrograde
reveille
reverenced
reviled
revoked
rhea
rind
ringleaders
ripen
risings
riven
river-bank
rollicking
roped
rosemary
rosette
round-up
rowboat
rump
rupees
sacerdotal
saddle-bags
safe-conduct
salt-water
sand-bags
sand-hills
sappers
sardines
satiated
saturnine
scantily
scimitar
scow
scrimmage
scrubby
scud
scudding
seaboard
seditious
seers
self-reliance
self-same
self-will
selfsame
seller
semicircular
sergeant-major
serpent's
servility
sesame
shah
shanks
sharp-pointed
shell-fish
shipboard
shoeing
shucks
siesta
sinless
sirens
sittings
skim
skinning
slave-trade
sleighs
snag
snow-shoes
snowshoes
soothsayer
south-eastern
south-western
speared
specie
spendthrift
spindle
splints
spoliation
spring-time
spy-glass
squeaky
staccato
state-room
stein
stentorian
step-mother
stern-sheets
store-room
storekeeper
stringent
strutted
stucco
succulent
sugar-cane
sun-god
suzerain
suzerainty
sweetened
sylvan
table-land
tableland
tabor
taffrail
tailor's
tartan
teamsters
threescore
thyme
tiara
tincture
to-day's
to-morrow's
topmast
torrid
townsfolk
tracery
tractable
traitorous
tranquility
transcends
transgress
transgressed
treeless
troughs
truculent
tryst
turbulence
turnings
turpentine
typhoon
unassuming
unbending
unconditional
unlovely
unpleasing
unsightly
unwarrantable
up-stream
usurpation
usury
vacillating
vandal
vandals
varmint
vassalage
vaunt
vend
venturesome
veriest
vernal
vestal
victim's
viking
vikings
virulent
vizier
waif
war-cry
war-path
war-ships
war-time
war-whoop
watchword
water-line
water-tight
watercourse
watercourses
watershed
waterway
waterways
wealthier
ween
welkin
well-armed
well-beloved
well-directed
whalebone
wheresoever
whetted
whilom
whiz
wide-spread
wildcat
winded
winder
winkle
winsome
wist
wold
woodcraft
wormwood
wrongfully
yams
yanked
yard-arm
yawl
yearling
yule
zephyr
zodiac
""";

        private const string VariousEbooksCorpusThirdNearKinCandidateData = """
abdicate|abdicated
abdicates|abdicated
abdicating|abdicated
abdication's|abdication
abdications|abdicated
abhorrently|abhorrent
ablution|ablutions
ablution's|ablutions
acacia's|acacia
acacias|acacia
acclamation's|acclamation
acquittal's|acquittal
acquittals|acquittal
acropolises|acropolis
acumen's|acumen
adjudge|adjudged
adjudges|adjudged
adjudging|adjudged
adobe's|adobe
adobes|adobe
affray's|affray
affrays|affray
agape's|agape
aggressor's|aggressor
aggressors|aggressor
agrarian's|agrarian
agrarians|agrarian
alder's|alder
allotment's|allotment
allotments|allotment
aloe|aloes
aloe's|aloes
alum's|alum
alums|alum
ambrosia's|ambrosia
amputate|amputated
amputates|amputated
amputating|amputated
amputations|amputated
anomalously|anomalous
apocryphally|apocryphal
apostate's|apostate
apostates|apostate
appetizingly|appetizing
aqueduct's|aqueduct
arraign|arraigned
arraigning|arraigned
arraignment|arraigned
arraigns|arraigned
arsenic's|arsenic
ascendant's|ascendant
ascendants|ascendant
asceticism's|asceticism
aspen's|aspen
assay's|assay
assayed|assay
assayer|assay
assayers|assay
assaying|assay
assays|assay
assimilate|assimilated
assimilates|assimilated
assimilating|assimilated
assimilation|assimilated
atheism's|atheism
augur's|augur
augured|augur
auguring|augur
avers|aver
avocation|avocations
avocation's|avocations
bairn's|bairn
banshee's|banshee
banshees|banshee
basilica's|basilica
basilicas|basilica
battlefield's|battlefields
bayou's|bayou
bayous|bayou
befit|befits
beginner's|beginner
beginners|beginner
beleaguer|beleaguered
beleaguering|beleaguered
beleaguers|beleaguered
benefice|benefices
benefice's|benefices
beneficence's|beneficence
bevies|bevy
bevy's|bevy
bewails|bewail
bigot|bigoted
bigot's|bigoted
bigots|bigoted
binnacle's|binnacle
binnacles|binnacle
blackberry|blackberries
blackberry's|blackberries
blackberrying|blackberries
blindfold's|blindfold
blindfolding|blindfold
blindfolds|blindfold
blockhouse's|blockhouse
blockhouses|blockhouse
bluejacket|bluejackets
bluejacket's|bluejackets
bod|boded
bod's|boded
boding|boded
bods|boded
boggier|boggy
boggiest|boggy
bole's|bole
boles|bole
boo's|boo
booed|boo
booing|boo
boor's|boor
boors|boor
boos|boo
bouillon's|bouillon
bouillons|bouillon
bounteously|bounteous
bounteousness|bounteous
bowman's|bowman
bra|bras
bra's|bras
braggart's|braggart
braggarts|braggart
breakwater's|breakwater
breakwaters|breakwater
brevet's|brevet
brevets|brevet
bridge's|bridged
bridging|bridged
brigantine's|brigantine
brigantines|brigantine
browse|browsing
browse's|browsing
browsed|browsing
browser|browsing
browsers|browsing
browses|browsing
bruin's|bruin
bruins|bruin
buddies|buddy
buddy's|buddy
burgomaster's|burgomaster
burgomasters|burgomaster
butte's|butte
buttes|butte
caisson|caissons
caisson's|caissons
calabash's|calabash
calabashes|calabash
camphor's|camphor
cannibalism's|cannibalism
canteen's|canteens
canto's|canto
cantonment's|cantonments
cantos|canto
canvassed|canvass
canvasser|canvass
canvassers|canvass
canvasses|canvass
canvassing|canvass
caparison|caparisoned
caparison's|caparisoned
caparisoning|caparisoned
caparisons|caparisoned
capitulates|capitulate
capitulating|capitulate
capitulations|capitulate
captaincies|captaincy
captaincy's|captaincy
carbuncle's|carbuncle
carbuncles|carbuncle
case's|cased
casings|cased
caterpillar's|caterpillar
caterpillars|caterpillar
centurion's|centurion
centurions|centurion
chaplet's|chaplet
chaplets|chaplet
chili's|chili
chirp|chirping
chirp's|chirping
chirped|chirping
chirps|chirping
choral's|choral
chorally|choral
chorals|choral
chore|chores
chore's|chores
chow's|chow
chowed|chow
chowing|chow
chows|chow
churl's|churl
churlishly|churlish
churlishness|churlish
churls|churl
circumcision's|circumcision
clarion's|clarion
clarioned|clarion
clarioning|clarion
clarions|clarion
clipper's|clipper
clippers|clipper
cockade's|cockade
cockades|cockade
codex's|codex
collie's|collie
colliers|collie
collies|collie
colonelcy's|colonelcy
colonnade's|colonnade
colonnaded|colonnade
colonnades|colonnade
combustible's|combustible
combustibles|combustible
companionway's|companionway
companionways|companionway
concoct|concocted
concocting|concocted
concocts|concocted
concubine's|concubine
connivance's|connivance
convene|convened
convenes|convened
convening|convened
conveyance's|conveyances
conveyancing|conveyances
corsair|corsairs
corsair's|corsairs
corvette's|corvette
corvettes|corvette
cote's|cote
cotes|cote
countersign's|countersign
countersigned|countersign
countersigning|countersign
countersigns|countersign
courser's|courser
coxswain's|coxswain
coxswains|coxswain
crone's|crone
crones|crone
crossing's|crossings
cupola's|cupola
cupolaed|cupola
cupolas|cupola
curia's|curia
cursoriness|cursory
curtail|curtailed
curtailing|curtailed
curtailment|curtailed
curtails|curtailed
cynic's|cynic
cynics|cynic
dapple|dappled
dapple's|dappled
dapples|dappled
dappling|dappled
davit|davits
davit's|davits
debauch's|debauch
debauched|debauch
debauches|debauch
debauching|debauch
decrepitude's|decrepitude
defraud|defrauded
defrauder|defrauded
defrauders|defrauded
defrauding|defrauded
defrauds|defrauded
degeneracy's|degeneracy
deification|deified
deifies|deified
deify|deified
deifying|deified
delineate|delineated
delineates|delineated
delineating|delineated
delineation|delineated
delineations|delineated
demarcation's|demarcation
dementedly|demented
demoniacally|demoniacal
denude|denuded
denudes|denuded
denuding|denuded
depute|deputed
deputes|deputed
deputing|deputed
deride|derided
derides|derided
deriding|derided
derrick's|derrick
derricks|derrick
detracted|detract
detracting|detract
detrimentally|detrimental
deviate's|deviate
deviated|deviate
deviates|deviate
deviating|deviate
deviations|deviate
dictum's|dictum
dinghies|dinghy
dinghy's|dinghy
dishearteningly|disheartening
distaff's|distaff
distaffs|distaff
distortion's|distortion
distortions|distortion
dockyard's|dockyard
dockyards|dockyard
donor's|donor
donors|donor
doorkeeper's|doorkeeper
doorkeepers|doorkeeper
dourer|dour
dourest|dour
dourly|dour
dourness|dour
dower's|dower
dowered|dower
dowering|dower
dowers|dower
dram's|dram
drams|dram
drove's|droves
drover|droves
drovers|droves
dub's|dub
dubs|dub
duff's|duff
duffed|duff
duffer|duff
duffers|duff
duffing|duff
duffs|duff
dysentery's|dysentery
earldom's|earldom
earldoms|earldom
eatable's|eatables
effulgence's|effulgence
embellishment's|embellishments
emigrate|emigrated
emigrates|emigrated
emigrating|emigrated
emigrations|emigrated
emir's|emir
emirs|emir
enactment's|enactments
encroachment's|encroachments
endue|endued
endues|endued
enduing|endued
entraps|entrap
ephemerally|ephemeral
epicurean's|epicurean
epicureans|epicurean
escutcheon's|escutcheon
escutcheons|escutcheon
eventide's|eventide
ewe|ewes
ewe's|ewes
ewer|ewes
ewers|ewes
excruciatingly|excruciating
execration's|execration
exorcism's|exorcism
exorcisms|exorcism
expiates|expiate
expiating|expiate
extraneously|extraneous
fagot|fagots
fagot's|fagots
fagoting|fagots
fervidly|fervid
fez's|fez
fief's|fief
fiefs|fief
finder's|finder
fishier|fishy
fishiest|fishy
fishiness|fishy
flagon's|flagon
flagons|flagon
flagstaff's|flagstaff
flagstaffs|flagstaff
flamboyantly|flamboyant
fleshlier|fleshly
fleshliest|fleshly
floe's|floe
floor's|floored
foal's|foal
foaled|foal
foaling|foal
foals|foal
folklore's|folklore
forelock's|forelock
forelocks|forelock
forerunner's|forerunner
forerunners|forerunner
forfeiture's|forfeiture
forfeitures|forfeiture
franc's|franc
francs|franc
frankincense's|frankincense
fraudulently|fraudulent
freebooter|freebooters
freebooter's|freebooters
freedman's|freedman
friskier|frisky
friskiest|frisky
friskiness|frisky
furtherance's|furtherance
fusillade's|fusillade
fusillades|fusillade
fuzzier|fuzzy
fuzziest|fuzzy
fuzziness|fuzzy
gaff's|gaff
gaffed|gaff
gaffer|gaff
gaffers|gaff
gaffing|gaff
gaffs|gaff
generalissimo's|generalissimo
generalissimos|generalissimo
generalship's|generalship
gloaming's|gloaming
gloamings|gloaming
godhead's|godhead
godlessly|godless
godlessness|godless
granary's|granaries
grandma's|grandma
grandmas|grandma
greensward's|greensward
gridiron's|gridiron
gridirons|gridiron
groundwork's|groundwork
gunnery's|gunnery
habituate|habituated
habituates|habituated
habituating|habituated
habituation|habituated
hackney's|hackney
hackneyed|hackney
hackneying|hackney
hackneys|hackney
hauteur's|hauteur
haversack's|haversack
haversacks|haversack
headman's|headman
headpiece's|headpiece
headpieces|headpiece
heathenism's|heathenism
heavenwards|heavenward
heinously|heinous
heinousness|heinous
homespun's|homespun
homicide's|homicide
homicides|homicide
hummock's|hummock
hyacinth's|hyacinth
idolater|idolaters
idolater's|idolaters
immoderately|immoderate
impale|impaled
impalement|impaled
impales|impaled
impaling|impaled
impartiality's|impartiality
improbabilities|improbability
improbability's|improbability
inboard's|inboard
inboards|inboard
inculcate|inculcated
inculcates|inculcated
inculcating|inculcated
inculcation|inculcated
indict|indicted
indictable|indicted
indicting|indicted
indicts|indicted
interdict's|interdict
interdicted|interdict
interdicting|interdict
interdicts|interdict
intermix|intermixed
intermixes|intermixed
intermixing|intermixed
interstice|interstices
interstice's|interstices
inundate|inundated
inundates|inundated
inundating|inundated
inundations|inundated
invective's|invective
irately|irate
irateness|irate
itinerant's|itinerant
itinerants|itinerant
jabber|jabbering
jabber's|jabbering
jabbered|jabbering
jabberer|jabbering
jabberers|jabbering
jabbers|jabbering
jack|jacks
jack's|jacks
jacked|jacks
jacking|jacks
jaguar's|jaguar
jaguars|jaguar
jasmine's|jasmine
jasmines|jasmine
jogging's|jogging
jollity's|jollity
juniper's|juniper
junipers|juniper
juror|jurors
juror's|jurors
knell's|knell
knelled|knell
knelling|knell
knells|knell
kraal's|kraal
kraals|kraal
lading's|lading
lagging's|lagging
laird's|laird
lairds|laird
lander|land's
landwards|landward
lariat's|lariat
lariats|lariat
lawgiver's|lawgiver
lawgivers|lawgiver
leach's|leach
leached|leach
leaches|leach
leaching|leach
leakier|leaky
leakiest|leaky
leakiness|leaky
leaven's|leaven
leavened|leaven
leavening|leaven
leavens|leaven
leghorn's|leghorn
leghorns|leghorn
libation's|libation
limerick's|limerick
limericks|limerick
lisle's|lisle
luffed|luff
luffing|luff
luffs|luff
lugger's|lugger
luggers|lugger
luminaries|luminary
luminary's|luminary
mackerel's|mackerel
mackerels|mackerel
magistracy's|magistracy
malcontent|malcontents
malcontent's|malcontents
malefactor|malefactors
malefactor's|malefactors
mammon's|mammon
mango's|mango
marksmanship's|marksmanship
mediator's|mediator
mediators|mediator
mercer's|mercer
mercers|mercer
messmate|messmates
messmate's|messmates
metamorphose|metamorphosed
metamorphoses|metamorphosed
metamorphosing|metamorphosed
midland's|midland
midlands|midland
mimosa's|mimosa
mimosas|mimosa
minaret|minarets
minaret's|minarets
mink's|mink
minks|mink
minstrelsy's|minstrelsy
mistletoe's|mistletoe
mizzen's|mizzen
mizzens|mizzen
moire|moires
moire's|moires
monotheism's|monotheism
monseigneur's|monseigneur
monsoon's|monsoon
monsoons|monsoon
moralist's|moralist
multifariously|multifarious
multifariousness|multifarious
munificence's|munificence
musketeer|musketeers
musketeer's|musketeers
muskrat's|muskrat
muskrats|muskrat
mustang's|mustang
mustangs|mustang
myrmidon|myrmidons
myrmidon's|myrmidons
myrrh's|myrrh
nabs|nab
navel's|navel
navels|navel
nefariously|nefarious
nefariousness|nefarious
nervelessly|nerveless
nervelessness|nerveless
neutral's|neutrals
neutrally|neutrals
nimrod's|nimrod
nimrods|nimrod
noontide's|noontide
obviated|obviate
obviates|obviate
obviating|obviate
obviation|obviate
occupancy's|occupancy
officiate|officiating
officiated|officiating
officiates|officiating
outhouse's|outhouse
outhouses|outhouse
outwits|outwit
outwork|outworks
outwork's|outworks
outworked|outworks
outworker|outworks
outworkers|outworks
outworking|outworks
padlock's|padlock
padlocked|padlock
padlocking|padlock
padlocks|padlock
palanquin's|palanquin
palanquins|palanquin
palatially|palatial
palfrey's|palfrey
palfreys|palfrey
palsies|palsied
palsy|palsied
palsy's|palsied
palsying|palsied
pamper|pampered
pampering|pampered
pampers|pampered
pancake|pancakes
pancake's|pancakes
pancaked|pancakes
pancaking|pancakes
papacies|papacy
papacy's|papacy
paramour's|paramour
paramours|paramour
parochially|parochial
parsley's|parsley
paymaster's|paymaster
paymasters|paymaster
pediment's|pediment
pediments|pediment
pennon|pennons
pennon's|pennons
perennial's|perennial
perennially|perennial
perennials|perennial
perpetuity's|perpetuity
personifications|personified
personifies|personified
personify|personified
personifying|personified
pertinacity's|pertinacity
pest's|pests
pester|pestered
pestering|pestered
pesters|pests
petrel's|petrel
petrels|petrel
pitfall|pitfalls
pitfall's|pitfalls
plaint's|plaint
plaints|plaint
plantain's|plantain
plotter|plotters
plotter's|plotters
polygamy's|polygamy
polytheism's|polytheism
poniard's|poniard
poniards|poniard
pontoon's|pontoon
portage's|portage
portaged|portage
portages|portage
portaging|portage
possum's|possum
possums|possum
posthumously|posthumous
precociously|precocious
precociousness|precocious
predilection's|predilection
predilections|predilection
predominance's|predominance
predominate|predominated
predominately|predominated
predominates|predominated
predominating|predominated
prig's|prig
prigs|prig
primate's|primate
primates|primate
prolongation's|prolongation
prolongations|prolongation
propagate|propagated
propagates|propagated
propagating|propagated
propagation|propagated
prophetesses|prophetess
proprietaries|proprietary
proprietary's|proprietary
proscription's|proscription
proscriptions|proscription
provender's|provender
pueblo's|pueblo
pueblos|pueblo
python's|python
pythons|python
qualm|qualms
qualm's|qualms
quartermasters|quartermaster's
quicksand's|quicksand
quicksands|quicksand
quinine's|quinine
raccoon's|raccoon
ramp's|ramp
ramping|ramp
ramps|ramp
ramrod's|ramrod
ramrods|ramrod
rankle|rankled
rankles|rankled
rankling|rankled
rapacity's|rapacity
rearguard's|rearguard
rearguards|rearguard
reconnoitered|reconnoiter
reconnoiters|reconnoiter
reedier|reedy
reediest|reedy
reediness|reedy
reprobate's|reprobate
reprobates|reprobate
rescue's|rescuers
rescuer's|rescuer
rescues|rescuers
retrograded|retrograde
retrogrades|retrograde
retrograding|retrograde
reveille's|reveille
reverence's|reverenced
reverences|reverenced
reverencing|reverenced
revile|reviled
revilement|reviled
reviler|reviled
revilers|reviled
reviles|reviled
reviling|reviled
revoke|revoked
revokes|revoked
revoking|revoked
rhea's|rhea
rheas|rhea
rind's|rind
rinds|rind
ringleader|ringleaders
ringleader's|ringleaders
riv|riven
rollicking's|rollicking
roping|roped
rosemary's|rosemary
rosette's|rosette
rosettes|rosette
rowboat's|rowboat
rowboats|rowboat
rump's|rump
rumply|rump
rumps|rump
rupee|rupees
rupee's|rupees
sapper|sappers
sardine|sardines
sardine's|sardines
satiate|satiated
satiates|satiated
satiating|satiated
satiation|satiated
scimitar's|scimitar
scimitars|scimitar
scow's|scow
scows|scow
scrimmage's|scrimmage
scrimmaged|scrimmage
scrimmages|scrimmage
scrimmaging|scrimmage
scrubbier|scrubby
scrubbiest|scrubby
scud's|scud
scuds|scud
seaboard's|seaboard
seaboards|seaboard
see's|seers
seller's|seller
servility's|servility
sesame's|sesame
sesames|sesame
shah's|shah
shank|shanks
shank's|shanks
shipboard's|shipboard
shipboards|shipboard
shuckses|shucks
siesta's|siesta
siestas|siesta
sir's|sirens
sitting's|sittings
skim's|skim
skims|skim
snag's|snag
snags|snag
snowshoe|snowshoes
snowshoe's|snowshoes
soothsayer's|soothsayer
soothsayers|soothsayer
spear's|speared
spearing|speared
specie's|specie
spendthrift's|spendthrift
spendthrifts|spendthrift
spindle's|spindle
spindled|spindle
spindles|spindle
spindling|spindle
splint|splints
splint's|splints
splinted|splints
splinting|splints
spoliation's|spoliation
squeakier|squeaky
squeakiest|squeaky
squeakiness|squeaky
staccato's|staccato
staccatos|staccato
stein's|stein
steiner|stein
steins|stein
storekeeper's|storekeeper
storekeepers|storekeeper
stringently|stringent
stucco's|stucco
stuccoed|stucco
stuccoing|stucco
succulent's|succulent
succulents|succulent
suzerain's|suzerain
suzerains|suzerain
suzerainty's|suzerainty
tableland's|tableland
tablelands|tableland
tabor's|tabor
tabors|tabor
taffrail's|taffrail
taffrails|taffrail
tartan's|tartan
tartans|tartan
teamster|teamsters
teamster's|teamsters
threescore's|threescore
threescores|threescore
thyme's|thyme
tiara's|tiara
tiaras|tiara
tincture's|tincture
tinctured|tincture
tinctures|tincture
tincturing|tincture
topmast's|topmast
topmasts|topmast
torridly|torrid
torridness|torrid
townsfolk's|townsfolk
traceries|tracery
tracery's|tracery
traitorously|traitorous
tranquility's|tranquility
transcend|transcends
transcended|transcends
transcending|transcends
transgresses|transgress
transgressing|transgress
truculently|truculent
tryst's|tryst
trysted|tryst
trysting|tryst
trysts|tryst
turbulence's|turbulence
turning's|turnings
turpentine's|turpentine
typhoon's|typhoon
typhoons|typhoon
unassumingly|unassuming
unbend|unbending
unbends|unbending
unconditionally|unconditional
unlovelier|unlovely
unloveliest|unlovely
unsightliest|unsightly
unsightliness|unsightly
usurpation's|usurpation
usury's|usury
vacillate|vacillating
vacillated|vacillating
vacillates|vacillating
vacillation|vacillating
vacillations|vacillating
vandal's|vandal
varmint's|varmint
varmints|varmint
vassalage's|vassalage
vaunt's|vaunt
vaunted|vaunt
vaunting|vaunt
vaunts|vaunt
vended|vend
vending|vend
vends|vend
venturesomely|venturesome
venturesomeness|venturesome
vestal's|vestal
vestals|vestal
viking's|viking
virulently|virulent
vizier's|vizier
viziers|vizier
waif's|waif
waifs|waif
watchword's|watchword
watchwords|watchword
watercourse's|watercourse
watershed's|watershed
watersheds|watershed
waterway's|waterway
weened|ween
weening|ween
weens|ween
welkin's|welkin
whalebone's|whalebone
whiz's|whiz
wildcat's|wildcat
wildcats|wildcat
winder's|winder
winders|winder
winkle's|winkle
winkled|winkle
winkles|winkle
winkling|winkle
winsomely|winsome
winsomeness|winsome
winsomer|winsome
winsomest|winsome
wold's|wold
wolds|wold
woodcraft's|woodcraft
wormwood's|wormwood
wrongful|wrongfully
wrongfulness|wrongfully
yam|yams
yam's|yams
yank's|yanked
yanking|yanked
yawl's|yawl
yawls|yawl
yearling's|yearling
yearlings|yearling
yule's|yule
yules|yule
zephyr's|zephyr
zephyrs|zephyr
zodiac's|zodiac
zodiacs|zodiac
""";

        private static IEnumerable<OrcishLexiconEntry> BuildVariousEbooksCorpusThirdCandidateEntries(IEnumerable<OrcishLexiconEntry> entries)
        {
            var acceptedEntries = entries.ToList();
            var sourceRoots = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var sourceOrdinal = 0;
            foreach (var english in VariousEbooksCorpusThirdSourceCandidateData.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var root = $"varuk-gor-{EncodeTwentyPageOrdinal(sourceOrdinal++)}";
                sourceRoots.Add(english, root);
                var candidate = new OrcishLexiconEntry(english, root, Tags: ["gutenberg", "various-ebooks-third-1500-candidate-batch", "generated", "review-promoted", "close-form-reviewed", $"family-{english}"]);
                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
            var nearKinOrdinal = 0;
            foreach (var line in VariousEbooksCorpusThirdNearKinCandidateData.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var fields = line.Split('|', 2, StringSplitOptions.TrimEntries);
                var english = fields[0];
                var sourceEnglish = fields[1];
                var candidate = new OrcishLexiconEntry(english, CreateThirtyPageNearKinForm(sourceRoots[sourceEnglish], english, nearKinOrdinal++), Tags: ["gutenberg", "various-ebooks-third-1500-near-kin", "near-kin", "derived-by-rule", "review-promoted", "close-form-reviewed", $"family-{sourceEnglish}"]);
                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
        }
    }
}
