namespace PlayerAssistant
{
    internal static partial class OrcishTranslatorUtility
    {
        private const string BlogFollowupSourceCandidateData = """
acrid
addled
administratively
aesthetic
affixed
agarics
alchemically
anima
array
arrowing
ash-drift
asp-headed
associations
attraction
aurochs
autumn
axe-arm
balancing
balmy
barnacles
batted
bearclaws
bedrock
beetle-like
benison
bile
biology
blasphemy
blunder
bodes
bone-cracker
bone-pile
bone-sands
bookshelf
bookshelves
borrow
bout
bowled
brash
breech
broodings
bucket-and-pulley
bugle
bugling
bunched
burials
cartography
caught
cavern-spiders
chagrined
charlatan
cherubic
children
chipped
choke
chute
cinematic
clansman
clansmen
clapped
clarified
clipped
clubbed
cobras
cold-lover
coldest
collection
colliding
combats
correspondence
corrugated
cosmopolitan
counter-weight
coyly
coyote
crank
crawlway
cro-magnon
cuffing
cutting
dabbed
damn
damp-gothic
dandelion
darkening
deathly
deep-sea
delight
delirious
deprecations
derived
devourer
dimmer
diplomatic
disappear
disconnected
discrete
diseased
disliking
dispersing
distracts
down-market
drainpipe
dredged
dumping
earthquake
echo-takers
eighty-eight
ejects
elevators
emerald-green
emphasis
encouragingly
enfolds
ensconsed
entanglements
envisioned
envisioning
erred
espionage
etc
ever-fleeing
evergreen
exacerbated
eye-blink
factional
fall-saboteurs
false
famine
farthest
fat
feebly
feudal
fifteen-hundred
figurative
fireless
flatten
foam
foot-deep
foreshadowing
forte
foundation-less
four-legged
four-way
foursome
freak
frost-den
frost-dens
frost-rimed
fruity
frustrate
frustrated
fungiculture
fur-lined
geological
ghost-neighborhood
glossy
gluttony
goat-headed
goatee
grave
gravely
graves
graveyard
gravity-chutes
gravity-train
green-edged
grey-skinned
greywater
grisly
ground-subsidence
hacks
hair-thin
hand-cranked
handicap
harbinger
haze
head-butt
heady
heedless
held
hide-covered
high-altitude
hindrance
humid
ice-giants
idol
inevitability
inevitable
ingress
inhale
inhaled
inquiry
instruments
interrogative
intolerable
intoned
inventory
invocation
iron-and-wood
juts
kissed
knife-sharp
lapsed
late-night
lead-lining
legs
lent
letters
libraries
life-mate
lifeblood
lift-credits
lift-tax
lift-wall
light-sensitive
lightless
lower-wealth
lug
makeshift
malign
man-sized
maritime
mash
mesmerizing
meta-rule
methodology
microclimate
mimics
mirror-city
miscreant
misplaced
mist-farming
mist-silk
mistakenly
momentary
monarch
moniker
monopoly
moss-lanterns
mostly-consumed
murals
muscled
mushroom-men
muzzle
mythic
neighborhood
neon
nerve
non-verbal
non-zero
obliterating
oligarchy
ominous
once-men
onyx
osteoarthritis
ouroboros
outcry
outline
outright
over-city
pall-carriers
partake
particulates
partner
partners
patted
pelt
pendent
percent
perceptible
persistent
petting
pickup
pleaded
porous
port
power-sharing
pragmatism
precipice
presaged
pressure-sensitive
prevailing
proclaimed
projection
provisioning
provocation
pulverized
punishable
putters
quaffes
quake
quick-sand
rain-line
re-chalk
realities
rebels
recap
recollection
reddening
rediscovered
redoubles
refinement
refrained
reject
rejoin
removes
replied
resin
revelatory
rightfully
ritualized
rotted
ruby-red
ruffling
runoff
salmon
salty
salvage-refining
sand
sang
satisfactory
scrabbled
scribes
seafood
seething
seventy
seventy-nine
sewage
shabby
shacks
sheddings
sheer
shortcut
shut
sigil
silver-plated
silver-veined
single-minded
sinker
sixty-two
sky-caskets
sky-stone
slanted
sled-plates
slide
slippery
sluice
slums
snap-cutter
snarling
soft-fleshed
sorcery
sorrow-laden
spark-stealer
sparring
spinels
spirit-world
spongy
spun
spurred
stacked
stalk-wood
stamina
star-leaf
state-sponsored
steam-powered
stellar
stirges
stoked
stone-dust
subconscious
successor-states
sully
sun-blinder
sun-lit
sunny
supervises
symbiosis
synchronized
synergy
ten-count
tenements
theocracy
theological
thoughtfulness
three-foot-deep
three-way
thuggery
thuggishly
thumb-sized
thwip
torpor
trajectory
trawlers
tread
treaties
triarch
triumvirate
twig
ululation
unauthorized
uncurls
under-ness
underearth
underfoot
undoer
uneasy
unexpected
unfolds
unsettling
unspecialized
unsurprised
unwraps
unzip
up-market
updrafts
upper-waste
vane
vanes
vehemently
verse
vivid
void-scar
well-being
well-concealed
whimpers
width
winch
winch-barons
winches
wiry
wistfully
wizard-priests
wove
wracked
yelped
zealots
zipped
""";

        private const string BlogFollowupNearKinCandidateData = """
acrider|acrid
acridly|acrid
acridness|acrid
addle|addled
addles|addled
addling|addled
aesthetics|aesthetic
affix|affixed
affix's|affixed
affixes|affixed
affixing|affixed
agaric|agarics
array's|array
arrayed|array
arraying|array
arrays|array
arrowed|arrowing
attraction's|attraction
attractions|attraction
auroch|aurochs
authorization|unauthorized
autumn's|autumn
autumns|autumn
balances|balancing
balmier|balmy
balminess|balmy
barnacle|barnacles
barnacle's|barnacles
barnacled|barnacles
batting|batted
bearclaw|bearclaws
bedrock's|bedrock
bedrocks|bedrock
bile's|bile
biology's|biology
blasphemies|blasphemy
blasphemy's|blasphemy
blunder's|blunder
blundered|blunder
blunderer|blunder
blunderers|blunder
blundering|blunder
blunders|blunder
bode|bodes
bookshelf's|bookshelf
borrowed|borrow
borrower|borrow
borrowers|borrow
borrowing|borrow
borrowings|borrow
borrows|borrow
bout's|bout
bouts|bout
bowl's|bowled
bowler|bowled
bowlers|bowled
brasher|brash
brashly|brash
breech's|breech
breeched|breech
breeches|breech
breeching|breech
brooding|broodings
bugle's|bugle
bugled|bugle
bugler|bugle
buglers|bugle
bugles|bugle
bunch|bunched
bunch's|bunched
bunches|bunched
bunching|bunched
burial's|burials
cartography's|cartography
cavern-spider|cavern-spiders
chagrin|chagrined
chagrin's|chagrined
chagrining|chagrined
chagrins|chagrined
charlatan's|charlatan
charlatans|charlatan
children's|children
chipping|chipped
choke's|choke
choker|choke
chokers|choke
chokes|choke
chute's|chute
chutes|chute
clansman's|clansman
clarification|clarified
clarifications|clarified
clarifies|clarified
clarify|clarified
clarifying|clarified
clip|clipped
clipping|clipped
clips|clipped
clubbing|clubbed
cobra's|cobras
cold's|coldest
coldly|coldest
colds|coldest
collection's|collection
collections|collection
collide|colliding
collided|colliding
collides|colliding
combat's|combats
combated|combats
combating|combats
combative|combats
correspondence's|correspondence
correspondences|correspondence
corrugate|corrugated
corrugates|corrugated
corrugating|corrugated
corrugation|corrugated
corrugations|corrugated
cosmopolitan's|cosmopolitan
cosmopolitans|cosmopolitan
coy|coyly
coyer|coyly
coyness|coyly
coyote's|coyote
coyotes|coyote
crank's|crank
cranked|crank
cranking|crank
cranks|crank
cuff|cuffing
cuff's|cuffing
cuffed|cuffing
cuffs|cuffing
cutting's|cutting
cuttingly|cutting
cuttings|cutting
dab|dabbed
dabbing|dabbed
dabs|dabbed
damn's|damn
damnable|damn
damning|damn
damns|damn
dandelion's|dandelion
dandelions|dandelion
darkened|darkening
darkener|darkening
darkeners|darkening
death's|deathly
delightful|delight
delighting|delight
delights|delight
deliriously|delirious
deliriousness|delirious
deprecation|deprecations
derivation|derived
derives|derived
deriving|derived
diplomatically|diplomatic
disappearing|disappear
disconnectedly|disconnected
disconnectedness|disconnected
discretely|discrete
discreteness|discrete
disliked|disliking
dislikes|disliking
disperse|dispersing
dispersed|dispersing
disperses|dispersing
dispersion|dispersing
drainpipe's|drainpipe
drainpipes|drainpipe
dredge|dredged
dredge's|dredged
dredger|dredged
dredgers|dredged
dredges|dredged
dredging|dredged
dump|dumping
dump's|dumping
dumped|dumping
dumper|dumping
dumpers|dumping
dumps|dumping
earthquake's|earthquake
earthquakes|earthquake
echo-taker|echo-takers
eject|ejects
ejected|ejects
ejecting|ejects
elevator|elevators
elevator's|elevators
enfold|enfolds
enfolded|enfolds
enfolding|enfolds
envision|envisioned
envisions|envisioned
err|erred
erring|erred
errs|erred
espionage's|espionage
evergreen's|evergreen
evergreens|evergreen
exacerbate|exacerbated
exacerbates|exacerbated
exacerbating|exacerbated
exacerbation|exacerbated
factionally|factional
fall-saboteur|fall-saboteurs
falsely|false
falseness|false
famine's|famine
famines|famine
farther|farthest
fat's|fat
fatness|fat
fats|fat
feeble|feebly
feudalism|feudal
feudally|feudal
figuratively|figurative
flattened|flatten
flattening|flatten
flattens|flatten
foam's|foam
foamed|foam
foaming|foam
foams|foam
foreshadow|foreshadowing
foreshadowed|foreshadowing
foreshadows|foreshadowing
forte's|forte
fortes|forte
foursome's|foursome
foursomes|foursome
freak's|freak
freaked|freak
freaking|freak
freaks|freak
fruitier|fruity
fruitiest|fruity
fruitiness|fruity
frustrates|frustrate
frustrating|frustrate
frustrations|frustrate
geologically|geological
glossier|glossy
glossies|glossy
glossiest|glossy
glossiness|glossy
glossy's|glossy
gluttony's|gluttony
goatee's|goatee
goatees|goatee
grave's|grave
graved|grave
graveness|grave
graver|grave
graveyard's|graveyard
graveyards|graveyard
graving|grave
gravity-chute|gravity-chutes
grisliness|grisly
hack|hacks
hack's|hacks
hacked|hacks
hacker|hacks
hackers|hacks
hacking|hacks
handicap's|handicap
handicaps|handicap
harbinger's|harbinger
harbingers|harbinger
haze's|haze
hazed|haze
hazer|haze
hazers|haze
hazes|haze
hazing|haze
hazings|haze
headier|heady
headiest|heady
headiness|heady
heedlessly|heedless
heedlessness|heedless
hindrance's|hindrance
hindrances|hindrance
humidly|humid
ice-giant|ice-giants
idol's|idol
idols|idol
inevitability's|inevitability
inevitable's|inevitable
ingresses|ingress
inhaling|inhale
inquiries|inquiry
inquiry's|inquiry
instrument|instruments
instrument's|instruments
instrumented|instruments
instrumenting|instruments
interrogative's|interrogative
interrogatively|interrogative
interrogatives|interrogative
intolerably|intolerable
intolerance|intolerable
intone|intoned
inventoried|inventory
inventories|inventory
inventory's|inventory
inventorying|inventory
invocations|invocation
jut|juts
jut's|juts
kiss|kissed
kissable|kissed
kisser|kissed
kissers|kissed
kisses|kissed
kissing|kissed
lapse|lapsed
lapse's|lapsed
lapses|lapsed
lapsing|lapsed
leg's|legs
lending|lent
lends|lent
letter's|letters
lettered|letters
letterer|letters
letterers|letters
lettering|letters
library's|libraries
lifeblood's|lifeblood
lift-credit|lift-credits
lug's|lug
lugs|lug
makeshift's|makeshift
makeshifts|makeshift
maligned|malign
maligning|malign
maligns|malign
mash's|mash
mashed|mash
masher|mash
mashers|mash
mashes|mash
mashing|mash
mesmerize|mesmerizing
mesmerized|mesmerizing
mesmerizer|mesmerizing
mesmerizers|mesmerizing
mesmerizes|mesmerizing
methodologies|methodology
methodology's|methodology
mimic|mimics
mimic's|mimics
miscreant's|miscreant
miscreants|miscreant
misplace|misplaced
misplacement|misplaced
misplaces|misplaced
misplacing|misplaced
momentariness|momentary
monarch's|monarch
moniker's|moniker
monikers|moniker
monopolies|monopoly
monopoly's|monopoly
moss-lantern|moss-lanterns
mural|murals
mural's|murals
muscle's|muscled
muscling|muscled
mushroom-man|mushroom-men
muzzle's|muzzle
muzzled|muzzle
muzzles|muzzle
muzzling|muzzle
mythical|mythic
mythically|mythic
neighborhood's|neighborhood
neighborhoods|neighborhood
neon's|neon
nerved|nerve
nerves|nerve
nerving|nerve
obliterate|obliterating
obliterated|obliterating
obliterates|obliterating
obliteration|obliterating
oligarchies|oligarchy
oligarchy's|oligarchy
ominously|ominous
ominousness|ominous
onyx's|onyx
onyxes|onyx
outcries|outcry
outcry's|outcry
outline's|outline
outlined|outline
outlines|outline
outlining|outline
pall-carrier|pall-carriers
partaker|partake
partakers|partake
partakes|partake
partaking|partake
particulate|particulates
particulate's|particulates
partner's|partner
partnered|partner
partnering|partner
pat|patted
pats|patted
patting|patted
pelt's|pelt
pelted|pelt
pelting|pelt
pelts|pelt
pendent's|pendent
pendents|pendent
percent's|percent
percents|percent
perceptibly|perceptible
persistently|persistent
petting's|petting
pickup's|pickup
pickups|pickup
plead|pleaded
pleader|pleaded
pleaders|pleaded
pleading|pleaded
pleadings|pleaded
pleads|pleaded
porousness|porous
port's|port
ported|port
porter|port
porting|port
ports|port
pragmatism's|pragmatism
precipice's|precipice
precipices|precipice
presage|presaged
presage's|presaged
presages|presaged
presaging|presaged
prevail|prevailing
prevailed|prevailing
prevails|prevailing
proclaiming|proclaimed
proclaims|proclaimed
projection's|projection
projections|projection
provision|provisioning
provocations|provocation
pulverize|pulverized
pulverizes|pulverized
pulverizing|pulverized
punish|punishable
punished|punishable
punishes|punishable
punishing|punishable
putter|putters
putter's|putters
puttered|putters
puttering|putters
quake's|quake
quaked|quake
quaking|quake
rebel|rebels
rebel's|rebels
recap's|recap
recaps|recap
recollections|recollection
redden|reddening
reddened|reddening
reddens|reddening
rediscover|rediscovered
rediscovering|rediscovered
redouble|redoubles
redoubling|redoubles
refinement's|refinement
refinements|refinement
refrain|refrained
refrain's|refrained
refraining|refrained
refrains|refrained
reject's|reject
rejected|reject
rejecting|reject
rejects|reject
rejoined|rejoin
rejoining|rejoin
rejoins|rejoin
replying|replied
resinous|resin
resins|resin
rightful|rightfully
rightfulness|rightfully
ritualize|ritualized
ritualizes|ritualized
ritualizing|ritualized
rots|rotted
ruffle|ruffling
ruffle's|ruffling
ruffled|ruffling
ruffles|ruffling
runoff's|runoff
runoffs|runoff
salmon's|salmon
salmons|salmon
saltier|salty
saltiest|salty
saltiness|salty
sand's|sand
sanded|sand
sander|sand
sanders|sand
sanding|sand
sands|sand
satisfactorily|satisfactory
satisfactoriness|satisfactory
scrabble|scrabbled
scrabble's|scrabbled
scrabbler|scrabbled
scrabblers|scrabbled
scrabbles|scrabbled
scrabbling|scrabbled
seafood's|seafood
seethe|seething
seethed|seething
seethes|seething
seventies|seventy
seventieth|seventy
seventy's|seventy
sewage's|sewage
shabbier|shabby
shabbiest|shabby
shabbiness|shabby
shack|shacks
shack's|shacks
shacked|shacks
shacking|shacks
sheer's|sheer
sheered|sheer
sheering|sheer
sheerness|sheer
sheers|sheer
shortcut's|shortcut
shortcuts|shortcut
shuts|shut
sinker's|sinker
sky-casket|sky-caskets
slant|slanted
slant's|slanted
slanting|slanted
slants|slanted
sled-plate|sled-plates
slide's|slide
slider|slide
sliders|slide
slipperiness|slippery
sluice's|sluice
sluiced|sluice
sluices|sluice
sluicing|sluice
slum|slums
slum's|slums
snarlingly|snarling
sorcery's|sorcery
spar|sparring
sparred|sparring
spars|sparring
spinel|spinels
spinning|spun
spongier|spongy
spongiest|spongy
sponginess|spongy
spurring|spurred
stack|stacked
stack's|stacked
stacking|stacked
stacks|stacked
stamina's|stamina
stoke|stoked
stoker|stoked
stokers|stoked
stokes|stoked
stoking|stoked
subconsciously|subconscious
subconsciousness|subconscious
sullied|sully
sullies|sully
sullying|sully
sunnier|sunny
sunniest|sunny
sunniness|sunny
supervise|supervises
supervised|supervises
supervising|supervises
supervision|supervises
supervisions|supervises
synchronize|synchronized
synchronizes|synchronized
synchronizing|synchronized
synergies|synergy
synergy's|synergy
tenement|tenements
tenement's|tenements
theocracies|theocracy
theocracy's|theocracy
theologically|theological
thuggery's|thuggery
thuggish|thuggishly
torpor's|torpor
trajectories|trajectory
trajectory's|trajectory
trawl|trawlers
trawl's|trawlers
trawled|trawlers
trawler|trawlers
trawling|trawlers
trawls|trawlers
tread's|tread
treading|tread
treads|tread
treaty|treaties
treaty's|treaties
triarchy|triarch
triumvirate's|triumvirate
triumvirates|triumvirate
twig's|twig
twigs|twig
ululation's|ululation
uncurl|uncurls
uncurled|uncurls
uncurling|uncurls
undo|undoer
undoes|undoer
uneasiest|uneasy
unexpectedly|unexpected
unexpectedness|unexpected
unfolded|unfolds
unfolding|unfolds
unsettle|unsettling
unsettled|unsettling
unsettles|unsettling
unwrap|unwraps
unwrapped|unwraps
unwrapping|unwraps
unzipped|unzip
unzipping|unzip
unzips|unzip
updraft|updrafts
updraft's|updrafts
vane's|vane
vehement|vehemently
verse's|verse
versed|verse
verses|verse
versing|verse
vividly|vivid
vividness|vivid
whimper|whimpers
whimper's|whimpers
whimpered|whimpers
whimpering|whimpers
width's|width
winch-baron|winch-barons
winch's|winch
winched|winch
winching|winch
wirier|wiry
wiriest|wiry
wiriness|wiry
wistful|wistfully
wistfulness|wistfully
wrack|wracked
wrack's|wracked
wracking|wracked
wracks|wracked
yelp|yelped
yelp's|yelped
yelping|yelped
yelps|yelped
zealot|zealots
zealot's|zealots
zip|zipped
zipping|zipped
zips|zipped
""";

        private static IEnumerable<OrcishLexiconEntry> BuildBlogFollowupCandidateEntries(
            IEnumerable<OrcishLexiconEntry> entries)
        {
            var acceptedEntries = entries.ToList();
            var sourceRoots = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var sourceOrdinal = 0;

            foreach (var english in BlogFollowupSourceCandidateData.Split(
                         ['\r', '\n'],
                         StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var root = $"brakz-{EncodeTwentyPageOrdinal(sourceOrdinal++)}";
                sourceRoots.Add(english, root);
                var candidate = new OrcishLexiconEntry(
                    english,
                    root,
                    Tags:
                    [
                        "blog",
                        "blog-followup-candidate-batch",
                        "generated",
                        "review-promoted",
                        "close-form-reviewed",
                        $"family-{english}"
                    ]);

                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }

            var nearKinOrdinal = 0;
            foreach (var line in BlogFollowupNearKinCandidateData.Split(
                         ['\r', '\n'],
                         StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var fields = line.Split('|', 2, StringSplitOptions.TrimEntries);
                var english = fields[0];
                var sourceEnglish = fields[1];
                var root = sourceRoots[sourceEnglish];
                var candidate = new OrcishLexiconEntry(
                    english,
                    CreateThirtyPageNearKinForm(root, english, nearKinOrdinal++),
                    Tags:
                    [
                        "blog",
                        "blog-followup-near-kin",
                        "near-kin",
                        "derived-by-rule",
                        "review-promoted",
                        "close-form-reviewed",
                        $"family-{sourceEnglish}"
                    ]);

                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
        }
    }
}
