namespace PlayerAssistant
{
    internal static partial class OrcishTranslatorUtility
    {
        private const string GutenbergCorpusFourthSourceCandidateData = """
abandoning
abandonment
abashed
abated
abhorrence
abiding
abject
ablaze
abolished
abolition
abominable
abound
above-mentioned
abstracted
absurdity
accompaniment
accomplishing
accosted
ached
acquitted
adjutant
admiralty
admittance
adrift
adverse
adviser
advocate
advocates
affectionately
affirm
affirmed
afresh
aghast
agreeably
agreeing
alms
alphabet
amateur
amazon
ambitions
ambulance
amended
analogy
anecdote
anecdotes
anglo-saxon
animal's
annihilated
anniversary
anonymous
another's
apologize
appalled
apparel
appliances
appointments
apprehensive
approbation
archipelago
ardor
aright
aristocracy
aristocratic
armament
arsenal
assemblage
assemblies
astounded
astounding
astride
astronomy
asunder
athletic
atlas
atrocities
attic
attorney
audacious
auspices
authentic
avarice
averse
aversion
avowed
bachelor
bail
ballad
ballads
balloon
bamboo
bananas
baptized
barbarism
barbed
barricade
basic
basil
battle-field
battlements
beastly
beaver
bedding
befell
begone
beheaded
belfry
belle
benches
benevolence
besought
bethought
betook
betwixt
bewitched
bidden
billy
bin
bird's
bivouac
blacks
bleak
bled
blot
blotted
blurred
boundless
bourbon
bracelets
bridal
bridegroom
brig
brightened
brilliancy
brilliantly
broadside
brood
brother-in-law
brushwood
buffaloes
buggy
bulletin
burgundy
bus
butterflies
butterfly
buzz
buzzing
bye
cab
calamities
calculate
camp-fire
candidate
candidates
cannibals
canst
capitulation
carelessness
cartridge
cartridges
casement
casks
caste
cataract
causeway
cavalier
ceaseless
cement
censure
census
cessation
chairman
chamberlain
chancellor
charger
charitable
charter
chastity
chat
chauffeur
cheat
cheated
chestnut
chevalier
chocolate
choicest
choir
chopped
chum
chums
churchyard
circumference
civilian
civilians
clement
climax
cloister
cloudy
co-operation
coachman
cod
colleague
colleagues
cologne
colt
comedy
comic
commend
commended
commentaries
commentary
commissary
commissioner
commissioners
committing
commodore
commons
compelling
compiled
compliance
compose
composing
compositions
comprehensive
compulsion
conceit
conclusive
condemnation
condensed
conductor
confederate
confederates
confessor
confirmation
confiscated
conflagration
conformity
congratulate
congratulated
conscientious
conservative
constancy
constitutions
consummate
contemptible
contemptuous
contemptuously
contention
continuance
continuation
continuity
contrasted
convict
convicted
convicts
convulsively
cooper
cope
copious
cork
coronation
corpus
correspond
corresponded
cottages
countess
court-martial
courtier
courtiers
covenant
covert
cowardice
crafty
critic
critics
crowding
cruelties
crusade
cuckoo
cur
cutlass
czar
dad
daddy
damsel
dauntless
daytime
dazzled
dealer
dealings
dean
deceit
decorations
defect
defective
defects
deferred
deficient
delicately
delirium
dell
delta
deluge
democracy
democratic
denial
denounced
dependence
deplorable
deputation
derelict
derision
descriptive
desertion
despondency
despotism
destroyer
destroyers
detachments
detective
deuce
devilish
diabolical
diction
dictionary
diffused
dilemma
dingy
dint
disdain
disgusting
distinctions
diverse
diversion
divorce
doe
dog's
doll
dot
doublet
dragoons
drawers
drawing-room
drawings
drawled
dreamy
drenched
drought
drowsy
duchess
dully
dunno
durst
dwindled
dye
dyed
earthen
eccentric
ecclesiastics
eclipse
ecstasy
eddies
editors
educational
elastic
elbows
elementary
emancipation
embankment
emigrants
emigration
emphatic
empress
engrossed
enjoined
enriched
enrolled
ensign
entreaties
entreaty
enumerated
epidemic
episcopal
epistle
epitaph
epithet
equestrian
erection
eruption
espied
essays
ether
ethical
ethics
evacuated
evacuation
evinced
exacted
exacting
exaggeration
exaltation
excavated
excavation
excelled
excellence
excellency
excessively
executioner
exposition
extravagance
fairyland
falcon
famished
fanaticism
fanciful
fanning
far-off
fated
father-in-law
fatherland
fawn
federal
fellow-citizens
ferns
fervent
fervently
festivities
fetters
feud
fictitious
fiddle
fierceness
fife
fig
figs
filed
firearms
first-rate
fitful
flamed
flannel
flapping
flashlight
flatter
flattered
flax
fleece
flitted
foothold
forbearance
forecastle
forefinger
foreman
foreseen
foretold
forfeit
forfeited
forgetful
forgetfulness
forthcoming
forty-eight
forum
fragrance
framework
fraternity
fraught
freeman
friar
friars
frigate
frock
froze
fullest
gaiety
gal
gall
gangway
garret
gazette
gee
genial
gentry
germ
giant's
gin
glen
glimmer
glimmering
glitter
glittered
goblet
goldsmith
good-morning
good-will
gourd
governess
graham
grammar
granddaughter
grandfather's
graphic
grievances
groped
groping
grouped
grown-up
guinea
guineas
gulch
gully
gunner
gunners
gust
hadst
half-hour
hallucination
ham
hammock
hampered
hand-to-hand
handwriting
hapless
harassed
hart
haughtily
haunches
hazy
head-quarters
headland
hearers
heaviest
heiress
hem
hemisphere
hens
hereby
hermit
hermitage
hiding-place
hoe
holiness
homely
hopped
hordes
horrified
horsemanship
hose
hostages
hove
how's
hugged
humane
humph
hunter's
husky
hypothesis
hysterical
idly
idolatry
illumined
illustrate
imaginative
imitate
imitated
imitating
immortality
immovable
imp
impetus
impious
implacable
importation
imported
impostor
impotent
impracticable
improbable
improper
improvised
impudence
incantations
indirectly
infamy
inference
inferred
infirm
inflamed
informant
inhuman
initiation
injurious
inmost
innocently
inseparable
inspector
instructive
insurance
insure
insurgents
inter
interment
intimacy
intimated
intimately
intimation
intrinsic
introductory
invalid
involuntary
issues
isthmus
italics
ivy
jammed
jug
jury
keg
kettle
khaki
kinsman
kinsmen
kitten
knave
knaves
knitting
lagoon
landlady
languid
lass
laurel
lava
lazily
leafy
lease
leeward
legislation
legislative
legislature
lemon
lengthened
leopard
lessened
liberality
liberated
lieutenant-colonel
life's
lime
listeners
livelihood
livery
loaves
lonesome
longitude
lover's
lovingly
ludicrous
lull
lunatic
luncheon
lurid
lustily
lusty
luxuriant
lyre
maddened
mademoiselle
madman
magnetic
maimed
maize
major-general
maker
makers
malady
mamma
man-of-war
manfully
mangled
manifold
market-place
marred
mart
martyrdom
masculine
materially
mathematics
mattress
maxim
maxims
mechanic
medal
medals
meddle
meek
meekly
meridian
merited
meritorious
methinks
metrical
metropolis
midsummer
midway
mien
mightily
millionaire
mind's
minutely
miser
miserably
misled
mistaking
misunderstood
moan
moaned
moaning
moat
moccasins
models
modestly
mole
momentous
monarchy
moody
moon's
morbid
morn
morning's
mortification
mosquito
mosquitoes
municipal
munitions
musketry
mutilated
nameless
narrator
nationality
nature's
natures
naughty
nautical
nave
needless
new-born
nightingale
non-commissioned
noose
northerly
northwards
notch
noteworthy
noticeable
nourished
novels
novelty
nowadays
nuisance
nun
nuns
nursery
nymph
nymphs
oaken
oats
oblige
oblong
obnoxious
obsolete
obstinacy
ode
odious
odyssey
officer's
oftener
old-time
omit
oneself
onset
oration
oratory
orbit
orchestra
ordinance
ordnance
originality
ornamental
orthodox
otter
outburst
outlook
overcoat
overflowing
overhung
overjoyed
oxygen
oyster
oysters
pagan
pal
pall
pallor
pamphlet
pang
pangs
panorama
pantry
papal
parley
parliamentary
parrot
parson
particle
particles
partisans
partition
partook
partridge
pastime
pastor
pastoral
paternal
pathos
patronage
pavilion
peaceable
peacock
peal
pears
peas
peasantry
pecuniary
penance
pens
peopled
performances
performer
performers
perseverance
personification
personnel
perusal
pervaded
phone
piazza
piers
pillage
piteous
piteously
pitiable
pitiless
placid
plaintive
plausible
playful
plebeian
plots
plucky
plumage
plural
pocket-book
poetic
poetical
policemen
pompous
pooh
poplar
porridge
portico
possessor
post-office
posterity
potter
poultry
powerfully
precipitate
predicament
preferable
pregnant
prelates
premier
premises
preparatory
presidency
prestige
presumption
pretensions
primeval
printing
prints
privacy
privy
pro
productions
productive
progressed
progressive
prologue
promenade
pronunciation
propaganda
propeller
prophetic
propped
proprietors
prosecute
prosecuted
prosecution
prow
psychology
publications
publish
publishing
pulpit
pumpkin
pup
puppy
purgatory
puritan
purposely
pyramids
quay
quickened
quickness
quitting
quotes
quoth
quoting
racial
radical
raiment
ranch
rapids
rapture
rattlesnake
reap
rebuke
receiver
recital
reconcile
reconciled
rector
red-hot
redeem
reef
reformed
refugees
regimental
regularity
relaxation
reliance
relish
reminiscences
renounce
repentance
repulsive
repute
requesting
restaurant
resting-place
retinue
revival
rhetoric
ridicule
rig
right-hand
rigidly
ripped
river's
roadside
robin
roger
rollers
rouge
rout
rubbish
rudder
ruffian
ruffians
ruinous
runaway
ruse
rustic
rye
sacrament
sagacity
saith
salient
salutation
sample
sandals
sandstone
sane
sanguinary
sanguine
sash
satin
savagery
savoy
sayings
scaffold
scant
scarcity
scarf
schoolmaster
scientist
scientists
scolded
scrape
scraped
scraps
scruple
scruples
scrupulous
sea-shore
secular
seer
seine
selecting
self-control
semblance
semicircle
senate
senator
senators
sentimental
sequel
sermon
sermons
session
sew
sewed
sewing
sexes
shave
shaved
shawl
shew
shilling
shun
shutting
sidewalk
sill
similarity
singer
singers
singly
sinner
sitting-room
skiff
skilfully
skinned
slackened
slapped
sledge
sleek
sleeper
sleepless
slippers
slit
sloop
sly
snorted
snug
socks
sod
solace
soldiery
solemnity
solicitude
son-in-law
soothe
soothed
south-east
sown
spade
spartan
speakers
specified
speechless
sportsman
squirrel
squirrels
staid
standpoint
standstill
staple
starlight
starry
statesman
statesmen
statute
statutes
steeple
stiffened
stifled
stifling
stimulus
stockade
story-teller
stoutly
stragglers
straggling
strata
striped
strung
studio
stunted
stupidity
sue
suitor
suitors
sultan
summary
sumptuous
sun's
suns
sup
superficial
superfluous
superseded
supplemented
suppliant
supplication
surged
surly
surrey
susceptible
swarthy
sweetheart
swerved
systematic
tact
tape
tawny
temperate
temporal
tennis
tenor
tenure
terrestrial
thanksgiving
thatched
theater
theology
therefrom
thereto
therewith
thirdly
thirty-six
thirty-two
three-quarters
thunderbolt
ticket
tickets
tickled
timidity
tinge
tiresome
tissue
tolerable
tolerably
tomahawk
torpedo
tout
towered
trackless
trailed
trapper
tremulous
triangle
triangular
tribunal
tribune
triumphal
trivial
trooper
troopers
trough
trout
truck
trucks
tumultuous
turban
turbulent
turmoil
turner
turret
twain
twenty-seven
twenty-six
twenty-three
twinkle
twinkled
twixt
umbrella
unanimous
unanimously
unbounded
uncanny
unclean
uncouth
underbrush
undue
unequal
unfit
unhurt
unimportant
unmarried
unpopular
unreal
unspeakable
unsteady
uppermost
upside
urn
utility
vacancy
vacation
valet
valid
variant
variously
vase
vases
vat
vehemence
veranda
verb
vexation
vicar
viceroy
vicissitudes
victors
victuals
vie
villa
vineyards
violin
virtually
visage
vista
voluntarily
wad
waded
wading
wakened
walled
wallet
wanderer
warnings
wast
watchman
wayside
wearisome
wedded
wee
well-nigh
wench
westerly
whereabouts
whereat
whereon
whirlpool
whiskers
whit
wholesale
whoop
whosoever
wig
winter's
wireless
withheld
wonderingly
worsted
wot
would-be
wouldst
wreckage
wright
wring
wroth
yearning
yore
zest
""";

        private const string GutenbergCorpusFourthNearKinCandidateData = """
abandonment's|abandonment
abashedly|abashed
abate|abated
abatement|abated
abates|abated
abating|abated
abhorrence's|abhorrence
abidingly|abiding
abjectly|abject
abjectness|abject
abolish|abolished
abolishes|abolished
abolishing|abolished
abolition's|abolition
abounded|abound
abounding|abound
abounds|abound
abstractedly|abstracted
abstractedness|abstracted
absurdities|absurdity
absurdity's|absurdity
accompaniment's|accompaniment
accompaniments|accompaniment
accomplishes|accomplishing
accost|accosted
accost's|accosted
accosting|accosted
accosts|accosted
ache's|ached
aches|ached
adjutant's|adjutant
adjutants|adjutant
admiralty's|admiralty
admittance's|admittance
adversely|adverse
adverseness|adverse
adverser|adverse
adversest|adverse
adviser's|adviser
advocate's|advocate
advocated|advocate
advocating|advocate
affirming|affirm
affirms|affirm
alphabet's|alphabet
alphabets|alphabet
amateur's|amateur
amateurs|amateur
amazon's|amazon
amazons|amazon
ambition's|ambitions
ambulance's|ambulance
ambulances|ambulance
amend|amended
amendable|amended
amending|amended
amendment|amended
amends|amended
analogies|analogy
analogy's|analogy
anecdote's|anecdote
annihilate|annihilated
annihilates|annihilated
annihilating|annihilated
anniversaries|anniversary
anniversary's|anniversary
anonymously|anonymous
apologized|apologize
apologizes|apologize
apologizing|apologize
appall|appalled
appalls|appalled
apparel's|apparel
appareled|apparel
appareling|apparel
apparels|apparel
appliance|appliances
appliance's|appliances
appointment's|appointments
apprehensively|apprehensive
apprehensiveness|apprehensive
approbation's|approbation
archipelago's|archipelago
archipelagos|archipelago
ardor's|ardor
ardors|ardor
aristocracies|aristocracy
aristocracy's|aristocracy
armament's|armament
arsenal's|arsenal
arsenals|arsenal
assemblage's|assemblage
assemblages|assemblage
astound|astounded
astoundingly|astounding
astounds|astounded
astronomy's|astronomy
athletics|athletic
atlases|atlas
atrocity|atrocities
atrocity's|atrocities
attic's|attic
attics|attic
attorney's|attorney
attorneys|attorney
audaciously|audacious
audaciousness|audacious
auspice|auspices
auspice's|auspices
avarice's|avarice
aversion's|aversion
aversions|averse
avowedly|avowed
bachelor's|bachelor
bachelors|bachelor
bail's|bail
bailable|bail
bailed|bail
bailing|bail
bails|bail
ballad's|ballad
balloon's|balloon
ballooned|balloon
ballooning|balloon
balloons|balloon
bamboo's|bamboo
bamboos|bamboo
banana|bananas
banana's|bananas
baptize|baptized
baptizer|baptized
baptizers|baptized
baptizes|baptized
baptizing|baptized
barb|barbed
barb's|barbed
barbarism's|barbarism
barbarisms|barbarism
barbers|barbed
barbing|barbed
barbs|barbed
barricade's|barricade
barricaded|barricade
barricades|barricade
barricading|barricade
basic's|basic
basics|basic
basil's|basil
battlement|battlements
battlement's|battlements
beastlier|beastly
beastliest|beastly
beastliness|beastly
beastly's|beastly
beaver's|beaver
beavered|beaver
beavering|beaver
beavers|beaver
bedding's|bedding
behead|beheaded
beheading|beheaded
beheads|beheaded
belfries|belfry
belfry's|belfry
belle's|belle
belles|belle
bench's|benches
benched|benches
benching|benches
benevolence's|benevolence
benevolences|benevolence
bewitch|bewitched
bewitches|bewitched
bewitching|bewitched
bewitchment|bewitched
billies|billy
billy's|billy
bin's|bin
bins|bin
birder|bird's
birders|bird's
bivouac's|bivouac
bivouacs|bivouac
black's|blacks
blacked|blacks
blackens|blacks
blacker|blacks
blackest|blacks
blacking|blacks
blackly|blacks
bleaker|bleak
bleakest|bleak
bleakly|bleak
bling|bled
blot's|blot
blots|blot
boundlessly|boundless
boundlessness|boundless
bourbon's|bourbon
bourbons|bourbon
bracelet|bracelets
bracelet's|bracelets
bridal's|bridal
bridals|bridal
bridegroom's|bridegroom
bridegrooms|bridegroom
brig's|brig
brighten|brightened
brightener|brightened
brighteners|brightened
brightening|brightened
brigs|brig
brilliancy's|brilliancy
brilliant's|brilliantly
brilliants|brilliantly
broadside's|broadside
broadsided|broadside
broadsides|broadside
broadsiding|broadside
brood's|brood
brooded|brood
brooder|brood
brooders|brood
broods|brood
brushwood's|brushwood
buggier|buggy
buggies|buggy
buggiest|buggy
buggy's|buggy
bulletin's|bulletin
bulletined|bulletin
bulletining|bulletin
bulletins|bulletin
burgundies|burgundy
burgundy's|burgundy
buses|bus
butterflied|butterflies
butterfly's|butterflies
butterflying|butterflies
buzz's|buzz
buzzed|buzz
buzzer|buzz
buzzers|buzz
buzzes|buzz
bye's|bye
byes|bye
cab's|cab
caber|cab
cabers|cab
cabs|cab
calamity's|calamities
calculates|calculate
calculative|calculate
candidate's|candidate
cannibal|cannibals
cannibal's|cannibals
capitulation's|capitulation
cartridge's|cartridge
casement's|casement
casements|casement
cask|casks
cask's|casks
caste's|caste
castes|caste
castings|caste
cataract's|cataract
cataracts|cataract
causeway's|causeway
causeways|causeway
cavalier's|cavalier
cavalierly|cavalier
cavaliers|cavalier
ceaselessly|ceaseless
ceaselessness|ceaseless
cement's|cement
cemented|cement
cementer|cement
cementers|cement
cementing|cement
cements|cement
censurable|censure
censure's|censure
censured|censure
censurer|censure
censurers|censure
censures|censure
censuring|censure
censused|census
censuses|census
censusing|census
cessation's|cessation
cessations|cessation
chairman's|chairman
chamberlain's|chamberlain
chamberlains|chamberlain
chancellor's|chancellor
chancellors|chancellor
charger's|charger
chargers|charger
charitableness|charitable
chartered|charter
chartering|charter
charters|charter
chastity's|chastity
chat's|chat
chats|chat
chauffeur's|chauffeur
chauffeured|chauffeur
chauffeuring|chauffeur
chauffeurs|chauffeur
cheat's|cheat
cheater|cheat
cheaters|cheat
cheating|cheat
cheats|cheat
chestnut's|chestnut
chestnuts|chestnut
chevalier's|chevalier
chevaliers|chevalier
chocolate's|chocolate
chocolates|chocolate
choice's|choicest
choicer|choicest
choir's|choir
choirs|choir
chum's|chum
churchyard's|churchyard
churchyards|churchyard
circumference's|circumference
circumferences|circumference
civilian's|civilian
clement's|clement
clemently|clement
clements|clement
climax's|climax
climaxed|climax
climaxes|climax
climaxing|climax
cloister's|cloister
cloistered|cloister
cloistering|cloister
cloisters|cloister
cloudier|cloudy
cloudiest|cloudy
cloudiness|cloudy
coachman's|coachman
cod's|cod
cods|cod
colleague's|colleague
cologne's|cologne
colognes|cologne
colt's|colt
colts|colt
comedies|comedy
comedy's|comedy
comic's|comic
comics|comic
commendable|commend
commending|commend
commends|commend
commentary's|commentaries
commissaries|commissary
commissary's|commissary
commissioner's|commissioner
commodore's|commodore
commodores|commodore
compellingly|compelling
compile|compiled
compiler|compiled
compilers|compiled
compiles|compiled
compiling|compiled
compliance's|compliance
composes|compose
comprehensive's|comprehensive
comprehensively|comprehensive
comprehensiveness|comprehensive
comprehensives|comprehensive
compulsion's|compulsion
compulsions|compulsion
conceit's|conceit
conceited|conceit
conceits|conceit
conclusively|conclusive
conclusiveness|conclusive
condemnation's|condemnation
condemnations|condemnation
condense|condensed
condenser|condensed
condensers|condensed
condenses|condensed
condensing|condensed
conductor's|conductor
conductors|conductor
confederate's|confederate
confessor's|confessor
confessors|confessor
confirmation's|confirmation
confirmations|confirmation
confiscate|confiscated
confiscates|confiscated
confiscating|confiscated
confiscation|confiscated
confiscations|confiscated
conflagration's|conflagration
conflagrations|conflagration
conformity's|conformity
congratulates|congratulate
congratulating|congratulate
congratulation|congratulate
conscientiously|conscientious
conscientiousness|conscientious
conservative's|conservative
conservatively|conservative
conservatives|conservative
constancy's|constancy
consummated|consummate
consummately|consummate
consummates|consummate
consummating|consummate
consummation|consummate
consummations|consummate
contemptuousness|contemptuous
contention's|contention
contentions|contention
continuance's|continuance
continuances|continuance
continuation's|continuation
continuations|continuation
continuities|continuity
continuity's|continuity
contrast's|contrasted
convict's|convict
convicting|convict
convulsive|convulsively
cooper's|cooper
coopered|cooper
coopering|cooper
cope's|cope
copes|cope
copiously|copious
copiousness|copious
corked|cork
corking|cork
corks|cork
coronation's|coronation
coronations|coronation
corresponds|correspond
cottager|cottages
cottagers|cottages
cottaging|cottages
countesses|countess
courtier's|courtier
covenant's|covenant
covenanted|covenant
covenanting|covenant
covenants|covenant
covert's|covert
covertly|covert
covertness|covert
coverts|covert
cowardice's|cowardice
craftier|crafty
craftiest|crafty
craftiness|crafty
critic's|critic
crowd's|crowding
cruelty's|cruelties
crusade's|crusade
crusaded|crusade
crusades|crusade
crusading|crusade
cuckoo's|cuckoo
cuckoos|cuckoo
cur's|cur
curs|cur
cutlasses|cutlass
czar's|czar
czars|czar
dad's|dad
daddies|daddy
daddy's|daddy
dads|dad
damsel's|damsel
damsels|damsel
dauntlessly|dauntless
dauntlessness|dauntless
daytime's|daytime
dazzle|dazzled
dazzle's|dazzled
dazzler|dazzled
dazzlers|dazzled
dazzles|dazzled
deal's|dealings
dealer's|dealer
dealers|dealings
dean's|dean
deceit's|deceit
deceits|deceit
defect's|defect
defected|defect
defecting|defect
defective's|defective
defectively|defective
defectiveness|defective
defectives|defective
delirium's|delirium
deliriums|delirium
dell's|dell
dells|dell
delta's|delta
deltas|delta
deluge's|deluge
deluged|deluge
deluges|deluge
deluging|deluge
democracies|democracy
democracy's|democracy
denial's|denial
denials|denial
denounce|denounced
denouncement|denounced
denounces|denounced
denouncing|denounced
dependence's|dependence
deputation's|deputation
deputations|deputation
derelict's|derelict
derelicts|derelict
derision's|derision
descriptively|descriptive
descriptiveness|descriptive
desertion's|desertion
desertions|desertion
despondency's|despondency
despotism's|despotism
destroyer's|destroyer
detachment's|detachments
detective's|detective
detectives|detective
deuce's|deuce
deuces|deuce
devilishly|devilish
devilishness|devilish
diabolically|diabolical
diction's|diction
dictionaries|dictionary
dictionary's|dictionary
diffuse|diffused
diffusely|diffused
diffuseness|diffused
diffuses|diffused
diffusing|diffused
diffusion|diffused
diffusive|diffused
dilemma's|dilemma
dilemmas|dilemma
dingier|dingy
dingiest|dingy
dinginess|dingy
dint's|dint
disdain's|disdain
disdained|disdain
disdaining|disdain
disdains|disdain
disgustingly|disgusting
distinction's|distinctions
diversely|diverse
diverseness|diverse
diversion's|diversion
diversions|diverse
divorce's|divorce
divorced|divorce
divorcement|divorce
divorces|divorce
divorcing|divorce
doe's|doe
does|doe
doll's|doll
dolled|doll
dolling|doll
dolls|doll
dot's|dot
doted|dot
doter|dot
doters|dot
doting|dot
dots|dot
doublet's|doublet
doublets|doublet
dragoon|dragoons
dragoon's|dragoons
dragooned|dragoons
dragooning|dragoons
draw's|drawers
drawl|drawled
drawl's|drawled
drawling|drawled
drawls|drawled
dreamier|dreamy
dreamiest|dreamy
dreaminess|dreamy
drench|drenched
drenches|drenched
drenching|drenched
drought's|drought
droughts|drought
drowsier|drowsy
drowsiest|drowsy
duchesses|duchess
dwindle|dwindled
dwindles|dwindled
dwindling|dwindled
dye's|dye
dyer|dye
dyers|dye
dyes|dye
eccentric's|eccentric
eccentrics|eccentric
ecclesiastic|ecclesiastics
ecclesiastic's|ecclesiastics
eclipse's|eclipse
eclipsed|eclipse
eclipses|eclipse
eclipsing|eclipse
ecstasies|ecstasy
ecstasy's|ecstasy
eddied|eddies
eddy|eddies
eddy's|eddies
eddying|eddies
editor|editors
editor's|editors
educationally|educational
elastic's|elastic
elastics|elastic
elbow's|elbows
elbowed|elbows
elbowing|elbows
emancipation's|emancipation
embankment's|embankment
embankments|embankment
emigrant|emigrants
emigrant's|emigrants
emigration's|emigration
empresses|empress
engross|engrossed
engrosses|engrossed
engrossing|engrossed
engrossment|engrossed
enjoin|enjoined
enjoining|enjoined
enjoins|enjoined
enrich|enriched
enriches|enriched
enriching|enriched
enrichment|enriched
enroll|enrolled
enrolling|enrolled
enrollment|enrolled
enrolls|enrolled
ensign's|ensign
ensigns|ensign
entreaty's|entreaties
enumerate|enumerated
enumerates|enumerated
enumerating|enumerated
enumeration|enumerated
enumerations|enumerated
epidemic's|epidemic
epidemics|epidemic
epistle's|epistle
epistles|epistle
epitaph's|epitaph
epithet's|epithet
epithets|epithet
equestrian's|equestrian
equestrians|equestrian
erection's|erection
erections|erection
eruption's|eruption
eruptions|eruption
espies|espied
espy|espied
espying|espied
essay|essays
essay's|essays
essayed|essays
essayer|essays
essayers|essays
essaying|essays
ether's|ether
ethically|ethical
evacuate|evacuated
evacuates|evacuated
evacuating|evacuated
evacuation's|evacuation
evacuations|evacuated
evince|evinced
evinces|evinced
evincing|evinced
exacter|exacted
exactest|exacted
exactingly|exacting
exactness|exacted
exacts|exacted
exaggeration's|exaggeration
exaltation's|exaltation
excavate|excavated
excavates|excavated
excavating|excavated
excavation's|excavation
excellence's|excellence
excellencies|excellency
excellency's|excellency
executioner's|executioner
exposition's|exposition
expositions|exposition
extravagance's|extravagance
extravagances|extravagance
fairyland's|fairyland
fairylands|fairyland
falcon's|falcon
falconer|falcon
falconers|falcon
falcons|falcon
famish|famished
famishes|famished
famishing|famished
fanaticism's|fanaticism
fancifully|fanciful
fancifulness|fanciful
fatherland's|fatherland
fatherlands|fatherland
fating|fated
fawn's|fawn
fawned|fawn
fawner|fawn
fawners|fawn
fawning|fawn
fawns|fawn
federal's|federal
federally|federal
federals|federal
fern|ferns
fern's|ferns
festivity|festivities
festivity's|festivities
fetter|fetters
fettered|fetters
fettering|fetters
feud's|feud
feuded|feud
feuding|feud
feuds|feud
fictitiously|fictitious
fiddle's|fiddle
fiddled|fiddle
fiddler|fiddle
fiddlers|fiddle
fiddles|fiddle
fiddling|fiddle
fife's|fife
fifer|fife
fifers|fife
fifes|fife
fig's|fig
figment|fig
file|filed
files|filed
filing|filed
firearm|firearms
firearm's|firearms
fitfully|fitful
fitfulness|fitful
flame's|flamed
flamer|flamed
flamers|flamed
flamings|flamed
flannel's|flannel
flanneled|flannel
flanneling|flannel
flannels|flannel
flashlight's|flashlight
flashlights|flashlight
flatterer|flatter
flatterers|flatter
flatters|flatter
flax's|flax
flaxen|flax
fleece's|fleece
fleeced|fleece
fleecer|fleece
fleecers|fleece
fleeces|fleece
fleecing|fleece
foothold's|foothold
footholds|foothold
forbearance's|forbearance
forecastle's|forecastle
forecastles|forecastle
forefinger's|forefinger
forefingers|forefinger
foreman's|foreman
forfeit's|forfeit
forfeiting|forfeit
forfeits|forfeit
forgetfully|forgetful
forthcoming's|forthcoming
forum's|forum
forums|forum
fragrance's|fragrance
fragrances|fragrance
framework's|framework
frameworks|framework
fraternities|fraternity
fraternity's|fraternity
freeman's|freeman
friar's|friar
frigate's|frigate
frigates|frigate
frocks|frock
full's|fullest
fulled|fullest
fullers|fullest
fulling|fullest
fulls|fullest
gaiety's|gaiety
gal's|gal
gall's|gall
galled|gall
galling|gall
galls|gall
gals|gal
gangway's|gangway
gangways|gangway
garret's|garret
garrets|garret
gazette's|gazette
gazetted|gazette
gazettes|gazette
gazetting|gazette
geed|gee
gees|gee
genially|genial
gentries|gentry
gentry's|gentry
germ's|germ
germs|germ
gin's|gin
gins|gin
glen's|glen
glens|glen
glimmer's|glimmer
glimmered|glimmer
glimmering's|glimmering
glimmerings|glimmer
glimmers|glimmer
glitter's|glitter
glitters|glitter
goblet's|goblet
goblets|goblet
goldsmith's|goldsmith
gourd's|gourd
gourds|gourd
governesses|governess
graham's|graham
grahams|graham
grammar's|grammar
grammars|grammar
granddaughter's|granddaughter
granddaughters|granddaughter
grandfathered|grandfather's
grandfathering|grandfather's
grandfatherly|grandfather's
grandfathers|grandfather's
graphic's|graphic
graphics|graphic
grievance|grievances
grievance's|grievances
grope|groped
grope's|groped
groper|groped
gropers|groped
gropes|groped
grouper|grouped
groupers|grouped
grouping|grouped
groupings|grouped
guinea's|guinea
gulch's|gulch
gulches|gulch
gullies|gully
gully's|gully
gunner's|gunner
gust's|gust
gusted|gust
gusting|gust
gusts|gust
hallucination's|hallucination
ham's|ham
hammock's|hammock
hammocks|hammock
hamper|hampered
hamper's|hampered
hampering|hampered
hampers|hampered
hams|ham
handwriting's|handwriting
haplessly|hapless
haplessness|hapless
harass|harassed
harasser|harassed
harassers|harassed
harasses|harassed
harassing|harassed
harassment|harassed
hart's|hart
harts|hart
haunch|haunches
haunch's|haunches
hazier|hazy
haziest|hazy
haziness|hazy
headland's|headland
headlands|headland
hearer|hearers
hearer's|hearers
heiresses|heiress
hem's|hem
hemisphere's|hemisphere
hemispheres|hemisphere
hems|hem
hermit's|hermit
hermitage's|hermitage
hermitages|hermitage
hermits|hermit
hes|hens
hing|hens
hings|hens
hoe's|hoe
hoes|hoe
homelier|homely
homeliest|homely
homeliness|homely
horde's|hordes
horded|hordes
hording|hordes
horrifies|horrified
horrify|horrified
horsemanship's|horsemanship
hose's|hose
hosed|hose
hoses|hose
hosing|hose
hostage|hostages
hostage's|hostages
hows|how's
humanely|humane
humaneness|humane
humphed|humph
humphing|humph
huskier|husky
huskies|husky
huskiest|husky
huskiness|husky
husky's|husky
hysterically|hysterical
id's|idly
idolatry's|idolatry
ids|idly
illuminable|illumined
illumine|illumined
illumines|illumined
illumining|illumined
illustrated|illustrate
illustrates|illustrate
illustrating|illustrate
illustration|illustrate
illustrations|illustrate
illustrative|illustrate
imaginatively|imaginative
imitates|imitate
imitations|imitate
imitative|imitate
immortality's|immortality
imp's|imp
imper|imp
impetuses|impetus
impiously|impious
impiousness|impious
import|imported
import's|imported
importable|imported
importation's|importation
importations|importation
importer|imported
importers|imported
importing|imported
imports|imported
impostor's|impostor
impostors|impostor
impotently|impotent
improperly|improper
improvise|improvised
improviser|improvised
improvisers|improvised
improvises|improvised
improvising|improvised
imps|imp
impudence's|impudence
incantation|incantations
incantation's|incantations
indirect|indirectly
infamies|infamy
infamy's|infamy
inference's|inference
inferences|inference
inflame|inflamed
inflames|inflamed
inflaming|inflamed
informant's|informant
informants|informant
inhumanly|inhuman
initiation's|initiation
innocent's|innocently
innocents|innocently
inseparable's|inseparable
inseparables|inseparable
inspector's|inspector
inspectors|inspector
instructively|instructive
insurable|insure
insurance's|insurance
insurances|insurance
insured|insure
insurer|insure
insurers|insure
insures|insure
insurgent|insurgents
insurgent's|insurgents
insuring|insure
interment's|interment
inters|inter
intimacies|intimacy
intimacy's|intimacy
intimate's|intimated
intimates|intimated
intimating|intimated
intimation's|intimation
intimations|intimated
invalid's|invalid
invalided|invalid
invaliding|invalid
invalidly|invalid
invalids|invalid
involuntariness|involuntary
issue|issues
issue's|issues
issued|issues
issuing|issues
isthmuses|isthmus
ivied|ivy
ivies|ivy
ivy's|ivy
jug's|jug
jugs|jug
juries|jury
jury's|jury
keg's|keg
kegs|keg
kettle's|kettle
kettles|kettle
khaki's|khaki
khakis|khaki
kinsman's|kinsman
kitten's|kitten
kittens|kitten
knave's|knave
knitting's|knitting
lagoon's|lagoon
lagoons|lagoon
landladies|landlady
landlady's|landlady
languidly|languid
languidness|languid
lasses|lass
laurel's|laurel
laurels|laurel
lava's|lava
leafier|leafy
leafiest|leafy
lease's|lease
leased|lease
leases|lease
leasing|lease
leeward's|leeward
leewards|leeward
legislation's|legislation
legislatively|legislative
legislature's|legislature
legislatures|legislature
lemon's|lemon
lemons|lemon
lengthening|lengthened
leopard's|leopard
leopards|leopard
lessening|lessened
liberality's|liberality
liberate|liberated
liberates|liberated
liberating|liberated
lifer|life's
lifers|life's
lime's|lime
limed|lime
limes|lime
liming|lime
listen's|listeners
listenable|listeners
livelihood's|livelihood
livelihoods|livelihood
liveries|livery
livery's|livery
lonesomely|lonesome
lonesomeness|lonesome
longitude's|longitude
longitudes|longitude
ludicrously|ludicrous
ludicrousness|ludicrous
lull's|lull
lulled|lull
lulling|lull
lulls|lull
lunatic's|lunatic
lunatics|lunatic
luncheon's|luncheon
luncheons|luncheon
luridly|lurid
luridness|lurid
lustier|lusty
lustiest|lusty
lustiness|lusty
luxuriantly|luxuriant
lyre's|lyre
lyres|lyre
madden|maddened
maddens|maddened
mademoiselle's|mademoiselle
mademoiselles|mademoiselle
madman's|madman
maim|maimed
maiming|maimed
maims|maimed
maize's|maize
maizes|maize
maker's|maker
maladies|malady
malady's|malady
mamma's|mamma
manful|manfully
mangle|mangled
mangle's|mangled
mangler|mangled
manglers|mangled
mangles|mangled
mangling|mangled
manifold's|manifold
manifolded|manifold
manifolding|manifold
manifolds|manifold
mart's|mart
marten|mart
martens|mart
marts|mart
martyrdom's|martyrdom
masculine's|masculine
masculines|masculine
material's|materially
mattresses|mattress
maxim's|maxim
mechanic's|mechanic
medal's|medal
meddled|meddle
meddler|meddle
meddlers|meddle
meddles|meddle
meeker|meek
meekest|meek
meekness|meek
meridian's|meridian
meridians|meridian
meritoriously|meritorious
meritoriousness|meritorious
metrically|metrical
metropolises|metropolis
midsummer's|midsummer
midway's|midway
midways|midway
mien's|mien
millionaire's|millionaire
millionaires|millionaire
minute's|minutely
minuted|minutely
minuteness|minutely
minuter|minutely
minutest|minutely
minuting|minutely
mistakable|mistaking
mistake's|mistaking
moan's|moan
moaner|moan
moaners|moan
moans|moan
moat's|moat
moated|moat
moats|moat
moccasin|moccasins
moccasin's|moccasins
model|models
model's|models
modeled|models
modeler|models
modelers|models
modeling|models
modelings|models
mole's|mole
moles|mole
momentously|momentous
momentousness|momentous
monarchies|monarchy
monarchy's|monarchy
moodier|moody
moodiest|moody
moodiness|moody
moody's|moody
morbidly|morbid
morbidness|morbid
morn's|morn
morns|morn
mortification's|mortification
mosquito's|mosquito
municipal's|municipal
municipally|municipal
municipals|municipal
munition|munitions
munition's|munitions
munitioned|munitions
munitioning|munitions
musketry's|musketry
mutilate|mutilated
mutilates|mutilated
mutilating|mutilated
mutilations|mutilated
namelessly|nameless
narrator's|narrator
narrators|narrator
nationalities|nationality
nationality's|nationality
naughtier|naughty
naughtiest|naughty
naughtiness|naughty
nautically|nautical
nave's|nave
naves|nave
needlessly|needless
needlessness|needless
nightingale's|nightingale
nightingales|nightingale
noose's|noose
nooses|noose
northerlies|northerly
northerly's|northerly
notch's|notch
notched|notch
notches|notch
notching|notch
noteworthiness|noteworthy
nourish|nourished
nourishes|nourished
nourishing|nourished
novel|novels
novel's|novels
novelties|novelty
novelty's|novelty
nuisance's|nuisance
nuisances|nuisance
nun's|nun
nurseries|nursery
nursery's|nursery
nymph's|nymph
oak's|oaken
obliges|oblige
obliging|oblige
oblong's|oblong
oblongs|oblong
obnoxiously|obnoxious
obnoxiousness|obnoxious
obsoleted|obsolete
obsoletes|obsolete
obsoleting|obsolete
obstinacy's|obstinacy
ode's|ode
odes|ode
odiously|odious
odiousness|odious
odyssey's|odyssey
odysseys|odyssey
oftenest|oftener
omits|omit
onset's|onset
onsets|onset
oration's|oration
oratories|oratory
oratory's|oratory
orbit's|orbit
orbited|orbit
orbiter|orbit
orbiters|orbit
orbiting|orbit
orbits|orbit
orchestra's|orchestra
orchestras|orchestra
ordinance's|ordinance
ordinances|ordinance
ordnance's|ordnance
originality's|originality
otter's|otter
otters|otter
outburst's|outburst
outbursts|outburst
outlook's|outlook
outlooks|outlook
overcoat's|overcoat
overcoats|overcoat
overflow|overflowing
overflow's|overflowing
overflowed|overflowing
overflows|overflowing
overjoy|overjoyed
overjoying|overjoyed
overjoys|overjoyed
oxygen's|oxygen
oyster's|oyster
pagan's|pagan
pagans|pagan
pal's|pal
pall's|pall
palled|pall
palling|pall
pallor's|pallor
palls|pall
pally|pal
pals|pal
pamphlet's|pamphlet
pamphlets|pamphlet
pang's|pang
panorama's|panorama
panoramas|panorama
pantries|pantry
pantry's|pantry
parley's|parley
parleyed|parley
parleying|parley
parleys|parley
parrot's|parrot
parroted|parrot
parroting|parrot
parrots|parrot
parson's|parson
parsons|parson
particle's|particle
partisan|partisans
partisan's|partisans
partition's|partition
partitioned|partition
partitioning|partition
partitions|partition
partridge's|partridge
partridges|partridge
pastime's|pastime
pastimes|pastime
pastor's|pastor
pastoral's|pastoral
pastorals|pastoral
pastors|pastor
paternally|paternal
patronage's|patronage
patronages|patronage
pavilion's|pavilion
pavilions|pavilion
pea|peas
pea's|peas
peacock's|peacock
peacocks|peacock
peal's|peal
pealed|peal
pealing|peal
peals|peal
pear|pears
pear's|pears
pearly|pears
peasantry's|peasantry
penance's|penance
penances|penance
peopling|peopled
performance's|performances
performer's|performer
perseverance's|perseverance
personification's|personification
personnel's|personnel
perusal's|perusal
perusals|perusal
pervade|pervaded
pervades|pervaded
pervading|pervaded
pest|pens
phone's|phone
phoned|phone
phones|phone
phoning|phone
pi's|piers
piazza's|piazza
piazzas|piazza
pied|piers
piing|piers
pillage's|pillage
pillaged|pillage
pillager|pillage
pillagers|pillage
pillages|pillage
pillaging|pillage
ping|pens
pings|pens
pis|piers
piteousness|piteous
pitilessly|pitiless
pitilessness|pitiless
placidly|placid
plaintively|plaintive
playfully|playful
playfulness|playful
plebeian's|plebeian
plebeians|plebeian
plot's|plots
pluckier|plucky
pluckiest|plucky
pluckiness|plucky
plumage's|plumage
plural's|plural
plurals|plural
poetically|poetical
poetics|poetic
pompously|pompous
pompousness|pompous
pooh's|pooh
poohed|pooh
poohing|pooh
poplar's|poplar
poplars|poplar
porridge's|porridge
portico's|portico
possessor's|possessor
possessors|possessor
posterity's|posterity
potter's|potter
pottered|potter
pottering|potter
potters|potter
poultry's|poultry
precipitate's|precipitate
precipitated|precipitate
precipitately|precipitate
precipitates|precipitate
precipitating|precipitate
precipitation|precipitate
precipitations|precipitate
predicament's|predicament
predicaments|predicament
preferment|preferable
prelate's|prelates
premier's|premier
premiered|premier
premiering|premier
premiers|premier
premise|premises
premise's|premises
premised|premises
premising|premises
presidencies|presidency
presidency's|presidency
prestige's|prestige
presumption's|presumption
presumptions|presumption
print|prints
print's|prints
printed|prints
printing's|printing
printings|printing
privacy's|privacy
privier|privy
privies|privy
priviest|privy
privy's|privy
pro's|pro
production's|productions
productively|productive
progresses|progressed
progressing|progressed
progressive's|progressive
progressively|progressive
progressiveness|progressive
progressives|progressive
prologue's|prologue
prologues|prologue
promenade's|promenade
promenaded|promenade
promenades|promenade
promenading|promenade
pronunciation's|pronunciation
pronunciations|pronunciation
propaganda's|propaganda
propeller's|propeller
propellers|propeller
proprietor's|proprietors
pros|pro
prosecutes|prosecute
prosecuting|prosecute
prosecution's|prosecution
prosecutions|prosecute
prow's|prow
prows|prow
psychologies|psychology
psychology's|psychology
publication|publications
publication's|publications
published|publish
publishes|publish
publishing's|publishing
pulpit's|pulpit
pulpits|pulpit
pumpkin's|pumpkin
pumpkins|pumpkin
pup's|pup
puppies|puppy
puppy's|puppy
pups|pup
purgatories|purgatory
purgatory's|purgatory
puritan's|puritan
puritans|puritan
purpose's|purposely
purposed|purposely
purposing|purposely
pyramided|pyramids
pyramiding|pyramids
quay's|quay
quays|quay
quicken|quickened
quickening|quickened
quo|quoth
quote|quotes
quoted|quotes
racially|racial
radical's|radical
radically|radical
radicals|radical
raiment's|raiment
ranch's|ranch
ranched|ranch
rancher|ranch
ranchers|ranch
ranches|ranch
ranching|ranch
rapid's|rapids
rapider|rapids
rapidest|rapids
rapidness|rapids
rapture's|rapture
raptures|rapture
rattlesnake's|rattlesnake
rattlesnakes|rattlesnake
reaped|reap
reaper|reap
reapers|reap
reaping|reap
reaps|reap
rebuke's|rebuke
rebuked|rebuke
rebukes|rebuke
rebuking|rebuke
receiver's|receiver
recital's|recital
recitals|recital
reconcilable|reconcile
reconciles|reconcile
reconciling|reconcile
rector's|rector
rectors|rector
redeemable|redeem
redeemer|redeem
redeemers|redeem
reef's|reef
reefed|reef
reefer|reef
reefers|reef
reefing|reef
reefs|reef
refugee|refugees
refugee's|refugees
regularities|regularity
regularity's|regularity
relaxation's|relaxation
relaxations|relaxation
reliance's|reliance
relish's|relish
relished|relish
relishes|relish
relishing|relish
reminiscence|reminiscences
reminiscence's|reminiscences
renounced|renounce
renouncement|renounce
renounces|renounce
renouncing|renounce
repentance's|repentance
repulsively|repulsive
repulsiveness|repulsive
reputable|repute
repute's|repute
reputes|repute
reputing|repute
request|requesting
requested|requesting
requester|requesting
restaurant's|restaurant
restaurants|restaurant
retinue's|retinue
retinues|retinue
revival's|revival
revivals|revival
rhetoric's|rhetoric
ridicule's|ridicule
ridiculed|ridicule
ridicules|ridicule
ridiculing|ridicule
rig's|rig
rigidness|rigidly
rigs|rig
roadside's|roadside
roadsides|roadside
robin's|robin
robins|robin
roger's|roger
rogered|roger
rogering|roger
rogers|roger
roll's|rollers
rollings|rollers
rouge's|rouge
rouged|rouge
rouges|rouge
rouging|rouge
rout's|rout
router|rout
routers|rout
routs|rout
rubbish's|rubbish
rubbished|rubbish
rubbishes|rubbish
rubbishing|rubbish
rudder's|rudder
rudders|rudder
ruffian's|ruffian
ruffianly|ruffian
ruinously|ruinous
runaway's|runaway
runaways|runaway
ruse's|ruse
ruses|ruse
rustic's|rustic
rustics|rustic
rye's|rye
sacrament's|sacrament
sacraments|sacrament
sagacity's|sagacity
salient's|salient
saliently|salient
salients|salient
salutation's|salutation
salutations|salutation
sample's|sample
sampled|sample
sampler|sample
samplers|sample
samples|sample
sampling|sample
samplings|sample
sandal|sandals
sandal's|sandals
sandstone's|sandstone
sanely|sane
saner|sane
sanest|sane
sanguinely|sanguine
sash's|sash
sashes|sash
satin's|satin
savageries|savagery
savagery's|savagery
savoy's|savoy
savoys|savoy
saying's|sayings
scaffold's|scaffold
scaffolding|scaffold
scaffolds|scaffold
scanted|scant
scantest|scant
scanting|scant
scants|scant
scarcities|scarcity
scarcity's|scarcity
scarf's|scarf
scarfed|scarf
scarfing|scarf
scarfs|scarf
schoolmaster's|schoolmaster
schoolmasters|schoolmaster
scientist's|scientist
scold|scolded
scold's|scolded
scolding|scolded
scoldings|scolded
scolds|scolded
scrap's|scraped
scrape's|scrape
scraper|scraped
scrapers|scraped
scrapings|scraped
scruple's|scruple
scrupled|scruple
scrupling|scruple
scrupulously|scrupulous
scrupulousness|scrupulous
seer's|seer
seine's|seine
seined|seine
seiner|seine
seiners|seine
seines|seine
seining|seine
select|selecting
selected|selecting
selective|selecting
selects|selecting
semblance's|semblance
semblances|semblance
semicircle's|semicircle
semicircles|semicircle
senate's|senate
senates|senate
senator's|senator
sentimentally|sentimental
sequel's|sequel
sequels|sequel
sermon's|sermon
session's|session
sessions|session
sewing's|sewing
sews|sew
sex|sexes
sex's|sexes
sexed|sexes
sexing|sexes
shave's|shave
shaver|shave
shavers|shave
shaves|shave
shaving|shave
shawl's|shawl
shawls|shawl
shewed|shew
shewing|shew
shews|shew
shilling's|shilling
shuns|shun
sidewalk's|sidewalk
sidewalks|sidewalk
sill's|sill
sills|sill
similarities|similarity
similarity's|similarity
sing's|singers
singable|singers
singer's|singer
sinner's|sinner
sinners|sinner
skiff's|skiff
skiffs|skiff
slackening|slackened
sledge's|sledge
sledged|sledge
sledges|sledge
sledging|sledge
sleeked|sleek
sleeker|sleek
sleekest|sleek
sleeking|sleek
sleekly|sleek
sleekness|sleek
sleeks|sleek
sleeper's|sleeper
sleeplessly|sleepless
sleeplessness|sleepless
slier|sly
sliest|sly
slipper|slippers
slipper's|slippers
slit's|slit
slits|slit
sloop's|sloop
sloops|sloop
slyly|sly
snort|snorted
snort's|snorted
snorter|snorted
snorters|snorted
snorting|snorted
snug's|snug
snugly|snug
snugness|snug
snugs|snug
sock|socks
sock's|socks
socked|socks
socking|socks
sod's|sod
sods|sod
solace's|solace
solaced|solace
solaces|solace
solacing|solace
soldiery's|soldiery
solemnities|solemnity
solemnity's|solemnity
solicitude's|solicitude
sooth|soothed
sooth's|soothed
soother|soothed
soothers|soothed
soothes|soothed
spade's|spade
spaded|spade
spades|spade
spading|spade
spartan's|spartan
spartans|spartan
speakings|speakers
specification|specified
specifications|specified
specifier|specified
specifiers|specified
specifies|specified
specify|specified
specifying|specified
speechlessly|speechless
speechlessness|speechless
sportsman's|sportsman
squirrel's|squirrel
squirreled|squirrel
squirreling|squirrel
staider|staid
staidest|staid
staidly|staid
staidness|staid
standpoint's|standpoint
standpoints|standpoint
standstill's|standstill
standstills|standstill
staple's|staple
stapled|staple
stapler|staple
staplers|staple
staples|staple
stapling|staple
starlight's|starlight
starrier|starry
starriest|starry
statesman's|statesman
statute's|statute
steeple's|steeple
steeples|steeple
stiffener|stiffened
stiffeners|stiffened
stiffening|stiffened
stifle|stifled
stifles|stifled
stiflingly|stifling
stiflings|stifled
stockade's|stockade
stockaded|stockade
stockades|stockade
stockading|stockade
stout's|stoutly
stouter|stoutly
stoutest|stoutly
stoutness|stoutly
stouts|stoutly
straggle|stragglers
straggled|stragglers
straggler|stragglers
straggles|stragglers
strip's|striped
striping|striped
studio's|studio
studios|studio
stunt|stunted
stunt's|stunted
stunting|stunted
stunts|stunted
stupidities|stupidity
stupidity's|stupidity
sue's|sue
sued|sue
sues|sue
suing|sue
suitor's|suitor
sultan's|sultan
sultans|sultan
summaries|summary
summary's|summary
sumptuously|sumptuous
sumptuousness|sumptuous
sup's|sup
superficially|superficial
superfluously|superfluous
superfluousness|superfluous
supers|sup
supersede|superseded
supersedes|superseded
superseding|superseded
supplement's|supplemented
supplementing|supplemented
supplements|supplemented
suppliant's|suppliant
suppliants|suppliant
supplication's|supplication
sups|sup
surge's|surged
surging|surged
surlier|surly
surliest|surly
surliness|surly
surrey's|surrey
surreys|surrey
swarthier|swarthy
swarthiest|swarthy
sweetheart's|sweetheart
sweethearts|sweetheart
swerve|swerved
swerve's|swerved
swerves|swerved
swerving|swerved
tact's|tact
tape's|tape
tapes|tape
tawnier|tawny
tawniest|tawny
tawny's|tawny
temperately|temperate
temporally|temporal
tenor's|tenor
tenors|tenor
tenure's|tenure
tenured|tenure
tenures|tenure
tenuring|tenure
terrestrial's|terrestrial
terrestrially|terrestrial
terrestrials|terrestrial
thanksgiving's|thanksgiving
thanksgivings|thanksgiving
thatch|thatched
thatch's|thatched
thatcher|thatched
thatchers|thatched
thatches|thatched
thatching|thatched
theater's|theater
theaters|theater
theologies|theology
theology's|theology
third's|thirdly
thirds|thirdly
thunderbolt's|thunderbolt
thunderbolts|thunderbolt
ticket's|ticket
ticketed|ticket
ticketing|ticket
tickle|tickled
tickle's|tickled
tickler|tickled
ticklers|tickled
tickles|tickled
tickling|tickled
timidity's|timidity
tinge's|tinge
tinges|tinge
tiresomely|tiresome
tiresomeness|tiresome
tissue's|tissue
tissues|tissue
tomahawk's|tomahawk
tomahawked|tomahawk
tomahawking|tomahawk
tomahawks|tomahawk
torpedo's|torpedo
torpedoed|torpedo
torpedoing|torpedo
tout's|tout
touted|tout
touting|tout
touts|tout
tower's|towered
trail's|trailed
trailer|trailed
trailers|trailed
trapper's|trapper
trappers|trapper
tremulously|tremulous
tremulousness|tremulous
triangle's|triangle
triangles|triangle
triangularly|triangular
tribunal's|tribunal
tribunals|tribunal
tribune's|tribune
tribunes|tribune
trivially|trivial
troop's|troopers
trooper's|trooper
trough's|trough
trout's|trout
trouts|trout
truck's|truck
trucked|truck
trucker|truck
truckers|truck
trucking|truck
tumultuously|tumultuous
turban's|turban
turbaned|turban
turbans|turban
turbulently|turbulent
turmoil's|turmoil
turmoils|turmoil
turner's|turner
turret's|turret
turreted|turret
turrets|turret
twain's|twain
twinkle's|twinkle
twinkles|twinkle
twinklings|twinkle
umbrella's|umbrella
umbrellas|umbrella
unbound|unbounded
uncanniest|uncanny
uncleaned|unclean
uncleaner|unclean
uncleanest|unclean
uncleanness|unclean
uncouthly|uncouth
underbrush's|underbrush
unequaled|unequal
unequally|unequal
unfits|unfit
unsteadier|unsteady
unsteadiest|unsteady
unsteadiness|unsteady
upside's|upside
upsides|upside
urn's|urn
urns|urn
utilities|utility
utility's|utility
vacancies|vacancy
vacancy's|vacancy
vacation's|vacation
vacationed|vacation
vacationer|vacation
vacationers|vacation
vacationing|vacation
vacations|vacation
valet's|valet
valeted|valet
valeting|valet
valets|valet
validly|valid
variant's|variant
variants|variant
vase's|vase
vat's|vat
vats|vat
vehemence's|vehemence
veranda's|veranda
verandas|veranda
verb's|verb
verbs|verb
vexation's|vexation
vexations|vexation
vicar's|vicar
vicars|vicar
viceroy's|viceroy
viceroys|viceroy
vicissitude|vicissitudes
vicissitude's|vicissitudes
victor|victors
victor's|victors
victual|victuals
victual's|victuals
victualed|victuals
victualing|victuals
vied|vie
vies|vie
villa's|villa
villas|villa
vineyard|vineyards
vineyard's|vineyards
violin's|violin
violins|violin
virtual|virtually
visage's|visage
visages|visage
vista's|vista
vistas|vista
wad's|wad
wader|wad
wads|wad
waken|wakened
wakening|wakened
wakens|wakened
wall's|walled
wallet's|wallet
wallets|wallet
walling|walled
wanderer's|wanderer
watchman's|watchman
wayside's|wayside
waysides|wayside
wearisomely|wearisome
wee's|wee
weer|wee
wees|wee
weest|wee
wench's|wench
wenches|wench
westerlies|westerly
westerly's|westerly
whirlpool's|whirlpool
whirlpools|whirlpool
whisk|whiskers
whisk's|whiskers
whisked|whiskers
whisker|whiskers
whisking|whiskers
whisks|whiskers
whit's|whit
whited|whit
whiten|whit
whitens|whit
whiter|whit
whitest|whit
whiting|whit
whitings|whit
whits|whit
wholesale's|wholesale
wholesaled|wholesale
wholesaler|wholesale
wholesalers|wholesale
wholesales|wholesale
wholesaling|wholesale
whoop's|whoop
whooped|whoop
whooper|whoop
whoopers|whoop
whooping|whoop
whoops|whoop
wig's|wig
wigs|wig
wintered|winter's
wintering|winter's
wirelesses|wireless
worsted's|worsted
wreckage's|wreckage
wright's|wright
wrights|wright
wring's|wring
wringer|wring
wringers|wring
wringing|wring
wrings|wring
yearning's|yearning
yore's|yore
zest's|zest
zests|zest
""";

        private static IEnumerable<OrcishLexiconEntry> BuildGutenbergCorpusFourthCandidateEntries(IEnumerable<OrcishLexiconEntry> entries)
        {
            var acceptedEntries = entries.ToList();
            var sourceRoots = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var sourceOrdinal = 0;
            foreach (var english in GutenbergCorpusFourthSourceCandidateData.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var root = $"guthnar-{EncodeTwentyPageOrdinal(sourceOrdinal++)}";
                sourceRoots.Add(english, root);
                var candidate = new OrcishLexiconEntry(english, root, Tags: ["gutenberg", "gutenberg-fourth-corpus-candidate-batch", "generated", "review-promoted", "close-form-reviewed", $"family-{english}"]);
                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
            var nearKinOrdinal = 0;
            foreach (var line in GutenbergCorpusFourthNearKinCandidateData.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var fields = line.Split('|', 2, StringSplitOptions.TrimEntries);
                var english = fields[0];
                var sourceEnglish = fields[1];
                var candidate = new OrcishLexiconEntry(english, CreateThirtyPageNearKinForm(sourceRoots[sourceEnglish], english, nearKinOrdinal++), Tags: ["gutenberg", "gutenberg-fourth-corpus-near-kin", "near-kin", "derived-by-rule", "review-promoted", "close-form-reviewed", $"family-{sourceEnglish}"]);
                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
        }
    }
}
