namespace PlayerAssistant
{
    internal static partial class OrcishTranslatorUtility
    {
        private const string VariousEbooksCorpusSecondSourceCandidateData = """
abridged
accredited
afternoon's
aide
alibi
alienated
allegorical
almond
almonds
alto
amnesty
amour
amours
anthem
arcade
assorted
astrologer
astrology
backwoods
baptismal
bate
bed-room
bight
bigotry
bivouacked
blackbird
blessedness
blockaded
booby
bookseller
booksellers
bur
burr
buttress
buttresses
canister
canny
capers
caretaker
cashmere
celibacy
cession
chamois
chandler
chastened
chattels
cherubim
chine
chump
church's
circlet
circumlocution
coercion
conducive
cop
cottonwood
couplet
criterion
crucifixion
cud
cupidity
currant
cymbals
daft
dastardly
decreasing
deerskin
delusive
devotees
devotional
dike
discrepancy
diver
dogmatic
dragon's
drat
dreamless
duenna
earthworks
eating-house
endorsed
endowments
epigram
epitome
epochs
erudition
every-day
exemplified
extolled
fastnesses
fathomless
fatter
fay
felon
ferryman
fetish
fillet
flecked
fruition
futurity
gainsay
gamekeeper
gentility
gingerbread
giraffe
gloating
glowered
glowering
gossamer
grandpa
gruel
gymnastic
gymnastics
hair's
haired
half-moon
hawser
high-minded
high-spirited
highness's
highwaymen
hilarious
hill's
hill-side
homecoming
howbeit
howsoever
humanly
husbandry
idiom
immature
incendiary
inclusive
indelible
indigenous
infirmary
intercede
interrogatories
intrepidity
intricacies
invidious
irrespective
jog
jubilee
jumper
jutted
kernel
knight-errant
lag
laity
lam
lave
leprosy
liaison
lief
lieutenant-general
lint
lodging-house
loo
lumbered
lye
magnolia
manna
marksman
maroon
minion
minster
molestation
mote
multiplicity
nary
nativity
netting
nohow
odium
old-world
omnipotence
opus
orations
ostensible
outdone
outgrown
panegyric
pasturage
paternoster
patriarchs
pee
pelican
pent-up
persecutors
pertinent
plat
pontifical
prayer-book
preamble
predestined
proscribed
putty
quack
quota
rear-guard
rebuild
rebuilding
regaled
requite
retention
rhapsody
rigor
rill
roan
roe
rood
ruff
rumpled
satyrs
scrip
scriptural
self-restraint
seraglio
setter
shepherdess
shewn
showman
sibyl
similitude
skeptical
skunk
somersault
something's
sonny
sorter
soulless
southerner
spangled
squash
stances
sterility
stigma
straitened
tally
tanner
teacher's
thoroughbred
threshing
tine
tinsel
tit
toga
tortoiseshell
tot
tulips
undeniably
unrelenting
unseeing
unsound
valorous
verity
vicarious
votive
wend
whoa
wide-awake
wind's
witch's
woodpecker
woody
wordless
""";

        private const string VariousEbooksCorpusSecondNearKinCandidateData = """
abridge|abridged
abridges|abridged
abridging|abridged
accredit|accredited
accrediting|accredited
accredits|accredited
aide's|aide
aides|aide
alibi's|alibi
alibied|alibi
alibiing|alibi
alibis|alibi
alienate|alienated
alienates|alienated
alienating|alienated
alienation|alienated
allegorically|allegorical
almond's|almond
alto's|alto
altos|alto
amnestied|amnesty
amnesties|amnesty
amnesty's|amnesty
amnestying|amnesty
amour's|amour
anthem's|anthem
anthems|anthem
arcade's|arcade
arcades|arcade
assort|assorted
assorting|assorted
assorts|assorted
astrologer's|astrologer
astrologers|astrologer
astrology's|astrology
bated|bate
bates|bate
bating|bate
bight's|bight
bights|bight
bigotries|bigotry
bigotry's|bigotry
blackbird's|blackbird
blackbirds|blackbird
blockade's|blockaded
blockader|blockaded
blockaders|blockaded
blockading|blockaded
boobies|booby
booby's|booby
bookseller's|bookseller
bur's|bur
burr's|burr
burred|burr
burring|burr
burrs|burr
burs|bur
buttressed|buttress
buttressing|buttress
canister's|canister
canisters|canister
cannier|canny
canniest|canny
caper|capers
caretaker's|caretaker
caretakers|caretaker
cashmere's|cashmere
celibacy's|celibacy
cession's|cession
cessions|cession
chandler's|chandler
chandlers|chandler
chasten|chastened
chastening|chastened
chastens|chastened
chattel|chattels
chattel's|chattels
chine's|chine
chines|chine
chump's|chump
chumps|chump
circlet's|circlet
circlets|circlet
circumlocution's|circumlocution
circumlocutions|circumlocution
coercion's|coercion
cop's|cop
coped|cop
copings|cop
cops|cop
cottonwood's|cottonwood
cottonwoods|cottonwood
couplet's|couplet
couplets|couplet
criterion's|criterion
crucifixion's|crucifixion
crucifixions|crucifixion
cud's|cud
cuds|cud
cupidity's|cupidity
currant's|currant
currants|currant
cymbal|cymbals
cymbal's|cymbals
dafter|daft
daftest|daft
daftly|daft
daftness|daft
dastard|dastardly
dastard's|dastardly
dastards|dastardly
decreasingly|decreasing
deerskin's|deerskin
delusively|delusive
devotee's|devotees
devotional's|devotional
devotionals|devotional
dike's|dike
diked|dike
dikes|dike
diking|dike
discrepancies|discrepancy
discrepancy's|discrepancy
diver's|diver
duenna's|duenna
duennas|duenna
earthwork|earthworks
earthwork's|earthworks
endorse|endorsed
endorsement|endorsed
endorser|endorsed
endorsers|endorsed
endorses|endorsed
endorsing|endorsed
endowment's|endowments
epigram's|epigram
epigrams|epigram
epitome's|epitome
epitomes|epitome
erudition's|erudition
exemplification|exemplified
exemplifications|exemplified
exemplifies|exemplified
exemplify|exemplified
exemplifying|exemplified
fay's|fay
fayer|fay
fayest|fay
fays|fay
felon's|felon
felons|felon
ferryman's|ferryman
fetish's|fetish
fetishes|fetish
fillet's|fillet
filleted|fillet
filleting|fillet
fillets|fillet
fleck|flecked
fleck's|flecked
flecking|flecked
flecks|flecked
fruition's|fruition
futurities|futurity
futurity's|futurity
gainsayer|gainsay
gainsayers|gainsay
gainsaying|gainsay
gainsays|gainsay
gamekeeper's|gamekeeper
gamekeepers|gamekeeper
gentility's|gentility
gingerbread's|gingerbread
giraffe's|giraffe
giraffes|giraffe
gloatingly|gloating
glower's|glowered
gossamer's|gossamer
grandpa's|grandpa
grandpas|grandpa
gruel's|gruel
gruelings|gruel
hawser's|hawser
hawsers|hawser
hilariously|hilarious
hilariousness|hilarious
homecoming's|homecoming
homecomings|homecoming
humaner|humanly
humanest|humanly
humanness|humanly
husbandry's|husbandry
idiom's|idiom
idioms|idiom
immaturely|immature
incendiaries|incendiary
incendiary's|incendiary
inclusively|inclusive
inclusiveness|inclusive
infirmaries|infirmary
infirmary's|infirmary
interceded|intercede
intercedes|intercede
interceding|intercede
interrogatory|interrogatories
interrogatory's|interrogatories
intrepidity's|intrepidity
intricacy's|intricacies
invidiously|invidious
invidiousness|invidious
jog's|jog
jogs|jog
jubilee's|jubilee
jubilees|jubilee
jumper's|jumper
kernel's|kernel
kernels|kernel
lag's|lag
lager|lag
lagers|lag
lags|lag
laity's|laity
lam's|lam
lams|lam
laves|lave
leprosy's|leprosy
liaison's|liaison
liaisons|liaison
liefer|lief
liefest|lief
linted|lint
linting|lint
lumber's|lumbered
lumberer|lumbered
lumberers|lumbered
lumbers|lumbered
lye's|lye
magnolia's|magnolia
magnolias|magnolia
manna's|manna
marksman's|marksman
maroon's|maroon
marooned|maroon
marooning|maroon
maroons|maroon
minion's|minion
minster's|minster
minsters|minster
molestation's|molestation
motes|mote
multiplicities|multiplicity
multiplicity's|multiplicity
nativities|nativity
nativity's|nativity
netting's|netting
odium's|odium
omnipotence's|omnipotence
opuses|opus
panegyric's|panegyric
panegyrics|panegyric
pasturage's|pasturage
paternoster's|paternoster
paternosters|paternoster
pee's|pee
peed|pee
pees|pee
pelican's|pelican
pelicans|pelican
persecutor|persecutors
persecutor's|persecutors
pertinently|pertinent
plat's|plat
plated|plat
platen|plat
platens|plat
plats|plat
pontifically|pontifical
preamble's|preamble
preambled|preamble
preambles|preamble
preambling|preamble
predestine|predestined
predestines|predestined
predestining|predestined
proscribe|proscribed
proscribing|proscribed
puttied|putty
putties|putty
putty's|putty
puttying|putty
quack's|quack
quacked|quack
quacking|quack
quacks|quack
quota's|quota
quotas|quota
rebuilds|rebuild
regaling|regaled
requited|requite
requiter|requite
requiters|requite
requites|requite
requiting|requite
retention's|retention
rhapsodies|rhapsody
rhapsody's|rhapsody
rigor's|rigor
rigors|rigor
rill's|rill
rills|rill
roan's|roan
roans|roan
roe's|roe
roes|roe
rood's|rood
roods|rood
ruff's|ruff
ruffed|ruff
ruffing|ruff
ruffly|ruff
ruffs|ruff
rumple|rumpled
rumple's|rumpled
rumples|rumpled
rumpling|rumpled
satyr|satyrs
satyr's|satyrs
scrip's|scrip
scrips|scrip
seraglio's|seraglio
seraglios|seraglio
setter's|setter
shepherdesses|shepherdess
showman's|showman
sibyl's|sibyl
sibyls|sibyl
similitude's|similitude
skeptically|skeptical
skunk's|skunk
skunked|skunk
skunking|skunk
skunks|skunk
somersault's|somersault
somersaulted|somersault
somersaulting|somersault
somersaults|somersault
sonnies|sonny
sonny's|sonny
sorter's|sorter
sorters|sorter
soullessly|soulless
soullessness|soulless
southerner's|southerner
southerners|southerner
spangle|spangled
spangle's|spangled
spangles|spangled
spangling|spangled
squash's|squash
squashes|squash
squashing|squash
stance's|stances
sterility's|sterility
stigma's|stigma
stigmas|stigma
straitening|straitened
tallied|tally
tallier|tally
talliers|tally
tallies|tally
tally's|tally
tallying|tally
tanner's|tanner
tanners|tanner
thoroughbred's|thoroughbred
thoroughbreds|thoroughbred
thresh|threshing
thresh's|threshing
threshed|threshing
thresher|threshing
threshers|threshing
threshes|threshing
tine's|tine
tines|tine
tinsel's|tinsel
tinseled|tinsel
tinseling|tinsel
tinsels|tinsel
tit's|tit
tits|tit
toga's|toga
togaed|toga
togas|toga
tortoiseshell's|tortoiseshell
tortoiseshells|tortoiseshell
tot's|tot
toted|tot
toting|tot
tots|tot
tulip|tulips
tulip's|tulips
unrelentingly|unrelenting
unseeingly|unseeing
unsounder|unsound
unsoundest|unsound
unsoundly|unsound
unsoundness|unsound
valorously|valorous
verities|verity
verity's|verity
vicariously|vicarious
vicariousness|vicarious
wended|wend
wending|wend
wends|wend
witched|witch's
witching|witch's
woodier|woody
woodies|woody
woodiest|woody
woodiness|woody
woodpecker's|woodpecker
woodpeckers|woodpecker
woody's|woody
wordlessly|wordless
""";

        private static IEnumerable<OrcishLexiconEntry> BuildVariousEbooksCorpusSecondCandidateEntries(IEnumerable<OrcishLexiconEntry> entries)
        {
            var acceptedEntries = entries.ToList();
            var sourceRoots = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var sourceOrdinal = 0;
            foreach (var english in VariousEbooksCorpusSecondSourceCandidateData.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var root = $"varuk-dra-{EncodeTwentyPageOrdinal(sourceOrdinal++)}";
                sourceRoots.Add(english, root);
                var candidate = new OrcishLexiconEntry(english, root, Tags: ["gutenberg", "various-ebooks-second-1000-candidate-batch", "generated", "review-promoted", "close-form-reviewed", $"family-{english}"]);
                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
            var nearKinOrdinal = 0;
            foreach (var line in VariousEbooksCorpusSecondNearKinCandidateData.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var fields = line.Split('|', 2, StringSplitOptions.TrimEntries);
                var english = fields[0];
                var sourceEnglish = fields[1];
                var candidate = new OrcishLexiconEntry(english, CreateThirtyPageNearKinForm(sourceRoots[sourceEnglish], english, nearKinOrdinal++), Tags: ["gutenberg", "various-ebooks-second-1000-near-kin", "near-kin", "derived-by-rule", "review-promoted", "close-form-reviewed", $"family-{sourceEnglish}"]);
                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
        }
    }
}
