namespace PlayerAssistant
{
    internal static partial class OrcishTranslatorUtility
    {
        private const string GutenbergCorpusSecondSourceCandidateData = """
abraham
abundantly
acceptance
accurately
aforesaid
agency
albert
ark
astern
astray
author's
automobile
bait
baker
bales
baptism
baths
beset
breakers
buck
bud
bunk
bureau
busily
butler
calculations
chaplain
chariot
cheery
childish
circus
clambered
commented
compensation
conspirators
constitutional
consul
continental
crater
daniel
dat
dick
director
disgusted
doctrines
dotted
douglas
drivers
eden
entreated
excursion
executive
fan
footnote
forgiven
forsake
forty-five
frail
freight
fruitful
gladness
good-by
governments
grabbed
grade
grassy
haggard
hebrew
hedges
hudson
isaac
jean
jersey
jim
joe
judicial
jupiter
keel
kent
lamb
laughingly
lincoln
loan
look-out
loveliness
michael
minded
modesty
mourn
mused
nick
non
oval
overtook
package
papa
parlor
patriot
pebbles
pencil
perfume
perspiration
photograph
pier
pilgrims
planets
processes
prophecy
prosper
protestant
queried
raced
rebellious
refreshed
reluctance
repent
requirements
robinson
schooner
scots
scottish
sentences
shipped
silvery
skipper
sow
starboard
stephen
suburbs
sundry
surf
taylor
telegram
telescope
tenants
tested
testified
testify
thereon
treasurer
turkish
undergone
vigor
vindictive
volcano
wail
watery
whereof
wherewith
wholesome
windward
worthless
wrinkled
wrung
yacht
yarn
youngster
""";

        private const string GutenbergCorpusSecondNearKinCandidateData = """
abraham's|abraham
acceptance's|acceptance
acceptances|acceptance
agencies|agency
agency's|agency
albert's|albert
ark's|ark
arks|ark
authored|author's
authoring|author's
automobile's|automobile
automobiled|automobile
automobiles|automobile
automobiling|automobile
bait's|bait
baited|bait
baiting|bait
baits|bait
baker's|baker
bale|bales
bale's|bales
baled|bales
baler|bales
balers|bales
baling|bales
baptism's|baptism
baptisms|baptism
besets|beset
break's|breakers
breakable|breakers
breaker|breakers
buck's|buck
bucked|buck
bucking|buck
bucks|buck
bud's|bud
buds|bud
bunked|bunk
bunking|bunk
bunks|bunk
bureau's|bureau
bureaus|bureau
butler's|butler
butlers|butler
chaplain's|chaplain
chaplains|chaplain
chariot's|chariot
chariots|chariot
cheerier|cheery
cheeriest|cheery
cheeriness|cheery
childishly|childish
childishness|childish
circuses|circus
clamber|clambered
clamber's|clambered
clamberer|clambered
clamberers|clambered
clambering|clambered
clambers|clambered
comment|commented
comment's|commented
commenting|commented
comments|commented
compensation's|compensation
conspirator|conspirators
conspirator's|conspirators
constitutional's|constitutional
constitutionally|constitutional
constitutionals|constitutional
consul's|consul
consuls|consul
continental's|continental
continentals|continental
crater's|crater
cratered|crater
cratering|crater
daniel's|daniel
daniels|daniel
dat's|dat
dick's|dick
dickens|dick
dicker|dick
dickers|dick
dicks|dick
director's|director
directors|director
disgustedly|disgusted
doctrine's|doctrines
drive's|drivers
drivings|drivers
eden's|eden
entreat|entreated
entreating|entreated
entreats|entreated
excursion's|excursion
excursions|excursion
executive's|executive
executives|executive
fan's|fan
fans|fan
footnote's|footnote
footnoted|footnote
footnotes|footnote
footnoting|footnote
forsakes|forsake
forsaking|forsake
frailer|frail
frailest|frail
frailly|frail
frailness|frail
freight's|freight
freighted|freight
freighter|freight
freighters|freight
freighting|freight
freights|freight
fruitfully|fruitful
fruitfulness|fruitful
government's|governments
graded|grade
grades|grade
grading|grade
grassier|grassy
grassiest|grassy
haggardly|haggard
haggardness|haggard
hebrew's|hebrew
hebrews|hebrew
hedge's|hedges
hedged|hedges
hedger|hedges
hedgers|hedges
hedging|hedges
hudson's|hudson
isaac's|isaac
jean's|jean
jeans|jean
jersey's|jersey
jerseys|jersey
jim's|jim
joe's|joe
judicially|judicial
jupiter's|jupiter
keel's|keel
keeled|keel
keeling|keel
keels|keel
kent's|kent
lamb's|lamb
lambed|lamb
lambing|lamb
lambs|lamb
laughing's|laughingly
lincoln's|lincoln
lincolns|lincoln
loan's|loan
loaned|loan
loaner|loan
loaners|loan
loaning|loan
loans|loan
michael's|michael
mindedness|minded
modesty's|modesty
mourned|mourn
mourner|mourn
mourners|mourn
mourns|mourn
muse|mused
muse's|mused
musing|mused
musings|mused
nick's|nick
nicked|nick
nicker|nick
nickers|nick
nicking|nick
nicks|nick
oval's|oval
ovals|oval
packaged|package
packages|package
packaging|package
papa's|papa
papas|papa
parlor's|parlor
parlors|parlor
patriot's|patriot
patriots|patriot
pebble|pebbles
pebble's|pebbles
pebbled|pebbles
pebbling|pebbles
pencil's|pencil
penciled|pencil
penciling|pencil
pencilings|pencil
pencils|pencil
perfume's|perfume
perfumed|perfume
perfumer|perfume
perfumers|perfume
perfumes|perfume
perfuming|perfume
perspiration's|perspiration
photograph's|photograph
photographed|photograph
photographer|photograph
photographers|photograph
photographing|photograph
pier's|pier
pilgrim|pilgrims
pilgrim's|pilgrims
planet's|planets
processed|processes
processing|processes
prophecies|prophecy
prophecy's|prophecy
prospered|prosper
prospering|prosper
prospers|prosper
protestant's|protestant
protestants|protestant
queries|queried
query|queried
query's|queried
querying|queried
race's|raced
racer|raced
racers|raced
rebelliously|rebellious
rebelliousness|rebellious
refresh|refreshed
refresher|refreshed
refreshers|refreshed
refreshes|refreshed
refreshment|refreshed
reluctance's|reluctance
repented|repent
repenting|repent
repents|repent
requirement's|requirements
robinson's|robinson
schooner's|schooner
schooners|schooner
scot|scots
scot's|scots
scottish's|scottish
sentence|sentences
sentence's|sentences
sentenced|sentences
sentencing|sentences
skipper's|skipper
skippered|skipper
skippering|skipper
skippers|skipper
sowed|sow
sowing|sow
sows|sow
starboard's|starboard
stephen's|stephen
stephens|stephen
suburb|suburbs
suburb's|suburbs
sundries|sundry
surf's|surf
surfed|surf
surfer|surf
surfers|surf
surfing|surf
surfs|surf
taylor's|taylor
telegram's|telegram
telegrams|telegram
telescope's|telescope
telescoped|telescope
telescopes|telescope
telescoping|telescope
tenant|tenants
tenant's|tenants
tenanted|tenants
tenanting|tenants
test|tested
testifier|testified
testifiers|testified
testifies|testified
testifying|testified
testing|tested
tests|tested
treasurer's|treasurer
turkish's|turkish
vigor's|vigor
vindictively|vindictive
vindictiveness|vindictive
volcano's|volcano
wail's|wail
wailed|wail
wailer|wail
wailers|wail
wails|wail
waterier|watery
wateriest|watery
wateriness|watery
wholesomeness|wholesome
windward's|windward
worthlessly|worthless
worthlessness|worthless
wrinkle|wrinkled
wrinkle's|wrinkled
wrinkles|wrinkled
wrinkling|wrinkled
yacht's|yacht
yachted|yacht
yachting|yacht
yachts|yacht
yarn's|yarn
yarns|yarn
youngster's|youngster
youngsters|youngster
""";

        private static IEnumerable<OrcishLexiconEntry> BuildGutenbergCorpusSecondCandidateEntries(IEnumerable<OrcishLexiconEntry> entries)
        {
            var acceptedEntries = entries.ToList();
            var sourceRoots = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var sourceOrdinal = 0;
            foreach (var english in GutenbergCorpusSecondSourceCandidateData.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var root = $"guthruk-{EncodeTwentyPageOrdinal(sourceOrdinal++)}";
                sourceRoots.Add(english, root);
                var candidate = new OrcishLexiconEntry(english, root, Tags: ["gutenberg", "gutenberg-second-corpus-candidate-batch", "generated", "review-promoted", "close-form-reviewed", $"family-{english}"]);
                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
            var nearKinOrdinal = 0;
            foreach (var line in GutenbergCorpusSecondNearKinCandidateData.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var fields = line.Split('|', 2, StringSplitOptions.TrimEntries);
                var english = fields[0];
                var sourceEnglish = fields[1];
                var candidate = new OrcishLexiconEntry(english, CreateThirtyPageNearKinForm(sourceRoots[sourceEnglish], english, nearKinOrdinal++), Tags: ["gutenberg", "gutenberg-second-corpus-near-kin", "near-kin", "derived-by-rule", "review-promoted", "close-form-reviewed", $"family-{sourceEnglish}"]);
                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
        }
    }
}
