namespace PlayerAssistant
{
    internal static partial class OrcishTranslatorUtility
    {
        private const string BlogHighYieldSourceCandidateData = """
abjuration
acknowledgement
aegis
aeration
aerator
after-effects
aftermath
ajar
akashic
alchemically-treated
amber-lit
analysis
analyzing
anonymity
anti-venom
anti-venoms
antitoxin
anybody
appetite
appraisal
armpits
arrest
ascent
assets
attentiveness
attenuate
attenuated
audacity
auras
awning
axis
axle
bagged
barrister
bash
bastion
batteries
battery
beading
beast-grease
beast-kings
beast-magic
bicep
big-brother
big-gift-bringers
big-horn
big-light
big-man
biters
bitter-shelf
black-powder
blood-bind
blood-blinder
blood-link
blood-silence
bloodshot
bloodstones
bloodstream
blowout
blue-burning
bolt-hole
bomb
bored-looking
brackish
brass-and-crystal
brass-and-glass
braying
breach-tool
breakdown
breathless
breathtaking
briar
broader
bronze-and-iron
bronze-shod
budge
bulwark
bump
byproduct
caches
calculated
calculation
caliber
canopic
capitalizes
card-sharp
cat-golems
catacombs
cave-ins
cedar-scented
charred
chasm
chatty
chest-piece
chitin
chittering
chlorine-ozone
circumvent
clad
clatter-clatter
cleft
click-clack
clog
clogs
cloven
code
cogs
collusion
comet
conceived
concoction
condescending
conditioned
confess
confetti
confines
congealed
conjuration
consecutive
conspiracy
conspired
construct-husks
conviction
copper-banded
copper-grease
corrosive
counter-chant
counter-mechanism
counter-weighted
coursed
cowardly
cowl
crate
credibility
crisp
croaks
crook
cross-bows
cross-legged
cross-references
crow-feather
crow-feathers
crumpled
crusty
crystal-aligned
crystal-clear
curator
custody
cynical
dandies
dandy
dark-aged
data
daydreams
dazes
dead-bolted
dead-drop
deadbolt
deadbolts
declaration
decodes
deep-green
deepening
describes
deserters
deserves
destitute
deterrent
dials
diluting
dirge
dirt-caked
disaffected
disengages
disk
dismantle
disturbance
disuse
dizzying
doesn
double-winged
down-tunnel
drain-grates
draughts
drawer
drawstring
dribble
drive-chain
drive-chains
dry-well
dual-lock
dust-choked
dust-free
dust-scented
dynasty
eavesdropping
elephant-carved
elixirs
eloquence
embedded
embellished
embezzlement
empower
encrusted
epoch
escapement
ever-burning
evocation
ex-oh-door-ray
exaggerated
exceptions
exchange
execute
executed
expectant
extortioners
extracted
eye-stones
fail-safe
fallback
false-bottom
feline-like
fermented
fiery
filth
fine-honed
fire-sticks
firmament
fish-filled
fish-shaped
fizzling
floodgates
floor-plate
floor-slot
floor-to-ceiling
fluidity
font
forewarning
formidable
foul-smelling
four-foot
foyer
fungally
galleon
gallows
gambit
gamble
gang
gargling
gatekeepers
geologic
ghast
ghast-priest
ghasts
ghost-floor
glasses
gluttonous
goblin-steel
gold-linen
gold-threaded
gong
grandmaster
graven
gray-robed
graying
grease-slicked
green-purple
green-stone
greenish-purple
grenade
grid
grim-faced
grinned
grit
grits
groove
grooves
grotto
grueling
guardianship
gurgling
hairline
half-drawn
half-step
hammer-blow
hand-off
handwritten
harmonize
haughty
head-bolts
heart-feeding
heart-jade
heat-fire
heaven
heavy-artillery
heavy-link
heavy-plate
heist
heresy
hexagonal
high-caste
high-end
high-grade
high-quality
high-tensile
high-tier
high-vibration
hikes
hiking
hitches
hitching
honey-colored
hooves
hot-breath
hungers
hydrate
hydraulic
ibis-headed
ibis-symbol
ichor
imminent
incense
incontinence
indisposed
inert
innocence
inquired
instinctual
intake
intel
interface
intuition
iris
iron-jaws
irons
jam
jangled
jemmy
jolts
judgmental
key-slot
khopeshes
kick-plate
knot
kraken
labeled
lancing
latent
laughs
lead-lined
leakage
leather-bound
leathery
ledge
left-hand
legalities
lever-lock
liberation
liberators
lidless
life-sized
life-support
life-tribute
lifeline
light-well
lilies
linked
liturgical
livid
locksmith
logical
long-dead
long-unused
low-light
low-slung
loyalties
lunar
magisterial
magistrates
mahogany
majesty
malice
mandala
mandala-door
mane
marque
mechanisms
mega-dungeon
memory-essence
memory-stream
memory-tank
metal-clad
metal-on-metal
metallically
metalsmith
microscopic
mid-motion
mid-pounce
mid-shave
midday
midnight-blue
milk-stalk
milky
millimeters
millisecond
mimicking
mini-kingdom
minor
mint
mode
monitor
monolith
monolithic
mountain-goat
mouthpiece
murky
murmurs
museum
mushroom-thicket
native-level
network
nightmare
nips
nobleman
nocking
nocks
non-thothian
notation
numbing-silt
oblivious
obsidian
obsidian-clad
obsidian-shod
occurrence
ocular
oil-soaked
oil-treated
one-two
open-air
oppressive
opulent
organic
outlive
over-max
overdrive
overhang
overheard
oversized
overstay
pactsworn
pale-green
pale-skins
panacea
panic-response
panicking
paraded
paralysis-inducing
passport
paste
patchwork
patina
pauldron
pauldrons
pedigree
pendant
persuasion
pestle
phylactery
pinch
pinches
pinning
pious
pipe-crawlers
pipe-tunnels
platter
plaza
plenum
plinth
plucked
plummets
plums
polearms
portly
pottery
pounce
pound
powder-sealed
prayerful
pre-combat
pre-made
preemptive
preen
prelude
presentation
pressure-stabilization
pressure-vents
pries
project
projected
projecting
protrusion
provenance
prowl
prudent
pry
psychically
putrid
questionable
quieter
radio
rag
rags
rails
rainbow
raptors
razor-rock
re-attunes
re-packs
reagent
reagents
reappearance
reasserts
rebranding
recalculated
recognition
recoils
reconsidering
recordings
redlines
refined
reflex
refreshing
regen
regrouping
rejuvenation
replacing
replica
representation
repurposed
residual
resonances
resounding
respite
restorative
restrain
restrained
resume
rim
rolled-up
rooftops
rubber
ruin-walker
ruin-walkers
rumbling
sack-like
sacrificial
sacrilege
safeguard
salt-streaked
salvo
sarcophagus
satrapies
saturated
sauntering
saviors
savory
scan
scanning
scaring
scholar-kings
scrap-metal
screen
scriptoriums
scroll-rack
scuppers
secluded
secrecy
seizure
self-deprecating
semi-precious
sensors
sentiment
sentinel
sentinels
sequence
seven-foot
seven-lashed
shadow-delineated
shadow-path
shadow-stalkers
shadow-wardens
shadow-wearing
shale
shanties
shantytown
sharp-eyed
shears
sheaths
shimmer
shock-spear
shoulder-charge
shove
shredding
shrill
shrivels
shushed
side-archive
silences
silo
silver-bound
singed
single-file
siren
skin-bags
slime-coated
slime-covered
sling-stones
slipknot
slippery-stairs
slotted
slouch
sludge
sludge-moss
slumped
slumps
smear
smears
smirk
smokeless
smoky
smothered
smudge
snared
snarls
snick
snipe
sniper
socket
solo-roleplay
soot-blackened
soot-covered
soot-paste
soot-stained
sorcerers
soul-chains
soul-core
soul-shriven
sound-snarers
sparse
spectral
spiritus
spontaneously
spore-cloud
springboards
sputters
squatted
squirming
stabbed
stabilization
staff-bearing
stale
standoff
static
steepened
stir
stirs
stitched-flesh
stitched-ones
stone-lined
stone-on-stone
storage
stored
storehouse
stores
strap
string
stung
sub-structure
sublevel
sun-bleached
sun-pendant
sun-scribed
sun-slayer
supposition
surety
surgeon
surgery
surgical
surreal
sync
syncs
t-junction
tall-magistrate
tall-things
tax-men
telekinetic
tempted
tempting
tendons
thaumaturgic
thief-trained
thistle
thought-bleed
three-dimensional
three-toed
throat-joint
thud-splash
thump-hiss
thunderclap
thunderous
thunderstorm
thunks
timely
toe-kick
toll-gate
tomb-dust
tomb-guardian
tomb-like
tonsured
toxins
trace
track-rails
trackers
transporting
tributes
trip
trunk-shaped
turd
turgid
tusk-instrument
twenty-foot-tall
tying
unadorned
unblinking
unbuckles
unchanged
uncharacteristically
uncharged
unchecked
unconcealed
unconcern
unconvinced
undertaking
unfurled
unguent-enhanced
unkind
unlatch
unpleasant
unpolished
unsealing
unsheathed
unslung
unspoken
untangling
untie
untimely
unwind
unwise
upper-level
uptake
urine
usurp
vent-screamer
verbalizes
vestry
vigilante
violet-gas
void-dust
wager
waist-high
watch-fire
watcher
way-station
weight-based
weight-sensitive
weirs
weld
well-funded
well-guarded
well-known
well-maintained
whatsoever
whipped
whisper-cap
white-furred
whittling
winces
wire-wrapped
withered
withstand
woe
woodsmoke
world-spanning
wry
yew
""";

        private const string BlogHighYieldNearKinCandidateData = """
abjuration's|abjuration
aeration's|aeration
aerator's|aerator
aerators|aerator
aftermath's|aftermath
analyze|analyzing
analyzed|analyzing
analyzes|analyzing
anonymity's|anonymity
antitoxin's|antitoxin
antitoxins|antitoxin
anybodies|anybody
anybody's|anybody
appetite's|appetite
appetites|appetite
appraisal's|appraisal
appraisals|appraisal
armpit|armpits
armpit's|armpits
arrest's|arrest
arrested|arrest
arresting|arrest
arrests|arrest
ascent's|ascent
ascents|ascent
asset|assets
asset's|assets
attenuates|attenuate
attenuating|attenuate
attenuation|attenuate
audacity's|audacity
aura's|auras
awning's|awning
axle's|axle
axles|axle
bagging|bagged
barrister's|barrister
barristers|barrister
bash's|bash
bashed|bash
bashes|bash
bashing|bash
bastion's|bastion
battery's|batteries
beading's|beading
beast-king|beast-kings
bicep's|bicep
biceps|bicep
bite's|biters
biter|biters
bloodstone|bloodstones
bloodstream's|bloodstream
bloodstreams|bloodstream
blowout's|blowout
blowouts|blowout
bomb's|bomb
bombed|bomb
bomber|bomb
bombers|bomb
bombing|bomb
bombings|bomb
bombs|bomb
brackishness|brackish
bray|braying
bray's|braying
brayed|braying
brays|braying
breakdown's|breakdown
breakdowns|breakdown
breathlessly|breathless
breathlessness|breathless
breathtakingly|breathtaking
broaden|broader
broadens|broader
broadest|broader
broadness|broader
budged|budge
budges|budge
budging|budge
bulwark's|bulwark
bulwarks|bulwark
bump's|bump
bumped|bump
bumper|bump
bumpers|bump
bumping|bump
bumps|bump
byproduct's|byproduct
byproducts|byproduct
cache's|caches
cached|caches
caching|caches
calculatedly|calculated
calculation's|calculation
caliber's|caliber
calibers|caliber
capitalize|capitalizes
capitalized|capitalizes
capitalizing|capitalizes
cat-golem|cat-golems
catacomb|catacombs
catacomb's|catacombs
cave-in|cave-ins
char|charred
charring|charred
chars|charred
chasm's|chasm
chasms|chasm
chattier|chatty
chattiest|chatty
chattiness|chatty
chitin's|chitin
circumvented|circumvent
circumventing|circumvent
circumvents|circumvent
cleft's|cleft
clefts|cleft
coded|code
coder|code
coders|code
codes|code
coding|code
cog|cogs
cog's|cogs
collusion's|collusion
comet's|comet
comets|comet
conceivable|conceived
conceive|conceived
conceives|conceived
conceiving|conceived
concoction's|concoction
concoctions|concoction
condescendingly|condescending
conditioning|conditioned
confetti's|confetti
congeal|congealed
congealing|congealed
congealment|congealed
congeals|congealed
conjuration's|conjuration
conjurations|conjuration
consecutively|consecutive
conspiracies|conspiracy
conspiracy's|conspiracy
conspire|conspired
conspiring|conspired
conviction's|conviction
convictions|conviction
corrosive's|corrosive
corrosively|corrosive
corrosives|corrosive
coward|cowardly
coward's|cowardly
cowards|cowardly
cowl's|cowl
cowling|cowl
cowlings|cowl
cowls|cowl
crate's|crate
crated|crate
crates|crate
crating|crate
credibility's|credibility
crisp's|crisp
crisped|crisp
crisper|crisp
crispest|crisp
crisping|crisp
crisply|crisp
crispness|crisp
crisps|crisp
croak|croaks
croak's|croaks
croaked|croaks
croaking|croaks
crook's|crook
crooking|crook
crooks|crook
crumple|crumpled
crumple's|crumpled
crumples|crumpled
crumpling|crumpled
crustier|crusty
crustiest|crusty
crustiness|crusty
curator's|curator
curators|curator
custody's|custody
cynically|cynical
dandier|dandies
dandiest|dandies
dandy's|dandies
daydream|daydreams
daydream's|daydreams
daydreamed|daydreams
daydreamer|daydreams
daydreamers|daydreams
daydreaming|daydreams
daze|dazes
daze's|dazes
dazed|dazes
dazing|dazes
deadbolt's|deadbolt
declaration's|declaration
declarations|declaration
deepened|deepening
destitution|destitute
deterrent's|deterrent
deterrents|deterrent
dial|dials
dial's|dials
dialed|dials
dialing|dials
dilute|diluting
diluted|diluting
dilutes|diluting
dilution|diluting
dilutions|diluting
dirge's|dirge
dirges|dirge
disk's|disk
disks|disk
disturbance's|disturbance
disturbances|disturbance
dizzied|dizzying
dizzier|dizzying
dizzies|dizzying
dizziest|dizzying
dizziness|dizzying
dizzy|dizzying
drawer's|drawer
drawstring's|drawstring
drawstrings|drawstring
dribble's|dribble
dribbled|dribble
dribbler|dribble
dribblers|dribble
dribbles|dribble
dribbling|dribble
dynasties|dynasty
dynasty's|dynasty
elixir's|elixirs
eloquence's|eloquence
embellish|embellished
embellishes|embellished
embellishing|embellished
embellishment|embellished
embezzlement's|embezzlement
empowered|empower
empowering|empower
empowerment|empower
empowers|empower
encrust|encrusted
encrusting|encrusted
encrusts|encrusted
epoch's|epoch
escapement's|escapement
escapements|escapement
evocation's|evocation
evocations|evocation
exaggeratedly|exaggerated
exception|exceptions
exception's|exceptions
exchange's|exchange
exchanges|exchange
executes|execute
executing|execute
execution|execute
expectantly|expectant
extortion|extortioners
extortion's|extortioners
extortioner|extortioners
extract|extracted
extract's|extracted
extracting|extracted
extracts|extracted
eye-stone|eye-stones
fierier|fiery
fieriest|fiery
fieriness|fiery
filth's|filth
fire-stick|fire-sticks
firmament's|firmament
firmaments|firmament
fizzle|fizzling
fizzle's|fizzling
fizzled|fizzling
fizzles|fizzling
floodgate|floodgates
floodgate's|floodgates
fluidity's|fluidity
font's|font
fonts|font
forewarn|forewarning
forewarned|forewarning
forewarns|forewarning
foyer's|foyer
foyers|foyer
galleon's|galleon
galleons|galleon
gambit's|gambit
gambits|gambit
gamble's|gamble
gambled|gamble
gang's|gang
ganged|gang
ganging|gang
gangs|gang
gargle|gargling
gargle's|gargling
gargled|gargling
gargles|gargling
gatekeeper|gatekeepers
gatekeeper's|gatekeepers
gluttonously|gluttonous
gong's|gong
gonged|gong
gonging|gong
gongs|gong
gray's|graying
grayed|graying
grays|graying
grenade's|grenade
grenades|grenade
grid's|grid
grids|grid
grit's|grit
groove's|groove
grooved|groove
grooving|groove
grotto's|grotto
gruelingly|grueling
guardianship's|guardianship
gurgle|gurgling
gurgle's|gurgling
gurgled|gurgling
gurgles|gurgling
hairline's|hairline
hairlines|hairline
harmonized|harmonize
harmonizer|harmonize
harmonizers|harmonize
harmonizes|harmonize
harmonizing|harmonize
haughtier|haughty
haughtiest|haughty
haughtiness|haughty
heaven's|heaven
heavenly|heaven
heavens|heaven
heist's|heist
heisted|heist
heisting|heist
heists|heist
heresies|heresy
heresy's|heresy
hike|hikes
hike's|hikes
hiked|hikes
hiker|hikes
hikers|hikes
hiking's|hiking
hitch|hitches
hitched|hitches
hunger's|hungers
hungered|hungers
hungering|hungers
hydrated|hydrate
hydrates|hydrate
hydrating|hydrate
hydration|hydrate
hydraulics|hydraulic
imminently|imminent
incense's|incense
incensed|incense
incenses|incense
incensing|incense
inertly|inert
inertness|inert
innocence's|innocence
inquire|inquired
inquirer|inquired
inquirers|inquired
intel's|intel
interface's|interface
interfaced|interface
interfaces|interface
interfacing|interface
intuitions|intuition
irises|iris
iron's|irons
ironed|irons
ironing|irons
jam's|jam
jangle|jangled
jangle's|jangled
jangler|jangled
janglers|jangled
jangles|jangled
jangling|jangled
jemmied|jemmy
jemmies|jemmy
jemmying|jemmy
jolt|jolts
jolt's|jolts
jolted|jolts
jolter|jolts
jolters|jolts
jolting|jolts
judgmentally|judgmental
khopesh|khopeshes
knot's|knot
labeling|labeled
labels|labeled
lance's|lancing
lanced|lancing
lancer|lancing
lancers|lancing
leakage's|leakage
leakages|leakage
ledge's|ledge
ledges|ledge
legality|legalities
legality's|legalities
liberation's|liberation
liberator|liberators
liberator's|liberators
lifeline's|lifeline
lifelines|lifeline
lily|lilies
lily's|lilies
link|linked
link's|linked
linker|linked
linking|linked
links|linked
liturgically|liturgical
lividly|livid
locksmith's|locksmith
logically|logical
magisterially|magisterial
magistrate's|magistrates
mahoganies|mahogany
mahogany's|mahogany
majesties|majesty
majesty's|majesty
malice's|malice
mandala's|mandala
mandalas|mandala
mane's|mane
maned|mane
manes|mane
marque's|marque
marques|marque
mechanism's|mechanisms
midday's|midday
milkier|milky
milkiest|milky
milkiness|milky
millimeter|millimeters
millimeter's|millimeters
millisecond's|millisecond
milliseconds|millisecond
minor's|minor
minors|minor
mint's|mint
minter|mint
minters|mint
minting|mint
mints|mint
mode's|mode
modes|mode
monitor's|monitor
monitored|monitor
monitoring|monitor
monitors|monitor
monolith's|monolith
mouthpiece's|mouthpiece
mouthpieces|mouthpiece
murkier|murky
murkiest|murky
murkiness|murky
murmur|murmurs
murmur's|murmurs
murmurer|murmurs
murmurers|murmurs
murmurings|murmurs
museum's|museum
museums|museum
network's|network
networked|network
networking|network
networks|network
nightmare's|nightmare
nightmares|nightmare
nip|nips
nip's|nips
nobleman's|nobleman
nock|nocking
nocked|nocking
notation's|notation
notations|notation
obliviously|oblivious
obliviousness|oblivious
obsidian's|obsidian
occurrence's|occurrence
occurrences|occurrence
ocular's|ocular
oculars|ocular
oppressively|oppressive
oppressiveness|oppressive
opulently|opulent
organic's|organic
organics|organic
outlived|outlive
outlives|outlive
outliving|outlive
overdrive's|overdrive
overdrives|overdrive
overhang's|overhang
overhanging|overhang
overhangs|overhang
overstayed|overstay
overstaying|overstay
overstays|overstay
pale-skin|pale-skins
panacea's|panacea
panaceas|panacea
parade|paraded
parade's|paraded
parader|paraded
paraders|paraded
parades|paraded
parading|paraded
passport's|passport
passports|passport
paste's|paste
pasted|paste
pastes|paste
pasting|paste
patchwork's|patchwork
patchworks|patchwork
patina's|patina
patinas|patina
pedigree's|pedigree
pedigreed|pedigree
pedigrees|pedigree
pendant's|pendant
pendants|pendant
persuasion's|persuasion
persuasions|persuasion
pestle's|pestle
pestled|pestle
pestles|pestle
pestling|pestle
phylacteries|phylactery
phylactery's|phylactery
pinch's|pinch
pinched|pinch
pinching|pinch
piously|pious
piousness|pious
pipe-crawler|pipe-crawlers
platter's|platter
platters|platter
plaza's|plaza
plazas|plaza
plenums|plenum
plinth's|plinth
pluck|plucked
pluck's|plucked
plucking|plucked
plucks|plucked
plum|plums
plum's|plums
plummet|plummets
plummet's|plummets
plummeted|plummets
plummeting|plummets
portlier|portly
portliest|portly
portliness|portly
potteries|pottery
pottery's|pottery
pounce's|pounce
pounced|pounce
pounces|pounce
pouncing|pounce
pound's|pound
pounded|pound
prayerfully|prayerful
preemptively|preemptive
preened|preen
preening|preen
preens|preen
prelude's|prelude
preludes|prelude
presentation's|presentation
presentations|presentation
pried|pries
prier|pries
priers|pries
project's|project
protrusion's|protrusion
protrusions|protrusion
provenance's|provenance
provenances|provenance
prowl's|prowl
prowled|prowl
prowler|prowl
prowlers|prowl
prowling|prowl
prowls|prowl
prudently|prudent
pry's|pries
prying|pries
psychical|psychically
question's|questionable
quiet's|quieter
quieten|quieter
quietens|quieter
quieting|quieter
quietness|quieter
quiets|quieter
radio's|radio
radioed|radio
radioing|radio
radios|radio
rag's|rag
rail|rails
railed|rails
railing|rails
rainbow's|rainbow
raptor|raptors
recording's|recordings
refreshingly|refreshing
regroup|regrouping
regrouped|regrouping
regroups|regrouping
rejuvenation's|rejuvenation
replica's|replica
replicas|replica
residual's|residual
residuals|residual
resonance's|resonances
resoundingly|resounding
restorative's|restorative
restoratives|restorative
resume's|resume
resumed|resume
resumes|resume
resuming|resume
rim's|rim
rims|rim
rooftop|rooftops
rooftop's|rooftops
rubber's|rubber
rubbers|rubber
rumbling's|rumbling
sacrificially|sacrificial
sacrilege's|sacrilege
sacrileges|sacrilege
safeguard's|safeguard
safeguarded|safeguard
safeguarding|safeguard
safeguards|safeguard
salvo's|salvo
salvos|salvo
saturate|saturated
saturates|saturated
saturating|saturated
saunter|sauntering
saunter's|sauntering
sauntered|sauntering
saunters|sauntering
savior|saviors
savior's|saviors
savorier|savory
savories|savory
savoriest|savory
savoriness|savory
savory's|savory
scan's|scan
scans|scan
scared|scaring
scholar-king|scholar-kings
screen's|screen
screened|screen
screening|screen
screenings|screen
screens|screen
scupper|scuppers
scupper's|scuppers
scuppered|scuppers
scuppering|scuppers
seclude|secluded
secludes|secluded
secluding|secluded
secrecy's|secrecy
seizure's|seizure
seizures|seizure
sensor|sensors
sensor's|sensors
sentiment's|sentiment
sentiments|sentiment
sentinel's|sentinel
sequence's|sequence
sequenced|sequence
sequencer|sequence
sequencers|sequence
sequences|sequence
sequencing|sequence
shadow-stalker|shadow-stalkers
shadow-warden|shadow-wardens
shale's|shale
shanty|shanties
shanty's|shanties
shantytown's|shantytown
shantytowns|shantytown
shear|shears
shear's|shears
sheared|shears
shearer|shears
shearers|shears
shearing|shears
shimmer's|shimmer
shimmered|shimmer
shimmers|shimmer
shove's|shove
shoved|shove
shoves|shove
shoving|shove
shrilled|shrill
shriller|shrill
shrillest|shrill
shrilling|shrill
shrillness|shrill
shrills|shrill
shrivel|shrivels
shriveled|shrivels
shriveling|shrivels
shush|shushed
shushes|shushed
shushing|shushed
silence's|silences
silencer|silences
silencers|silences
silencing|silences
silo's|silo
silos|silo
singe|singed
singeing|singed
singes|singed
siren's|siren
sling-stone|sling-stones
slipknot's|slipknot
slipknots|slipknot
slouch's|slouch
slouched|slouch
sloucher|slouch
slouchers|slouch
slouches|slouch
slouching|slouch
sludge's|sludge
slump|slumped
slump's|slumped
slumping|slumped
smear's|smear
smeared|smear
smearing|smear
smirk's|smirk
smirked|smirk
smirking|smirk
smirks|smirk
smokier|smoky
smokiest|smoky
smokiness|smoky
smother|smothered
smother's|smothered
smothering|smothered
smothers|smothered
smudge's|smudge
smudged|smudge
smudges|smudge
smudging|smudge
snare|snared
snare's|snared
snares|snared
snaring|snared
snarl|snarls
snarled|snarls
snicked|snick
snicking|snick
snicks|snick
snipe's|snipe
sniper's|sniper
snipes|snipe
socket's|socket
sockets|socket
sorcerer|sorcerers
sorcerer's|sorcerers
soul-chain|soul-chains
sound-snarer|sound-snarers
sparsely|sparse
sparseness|sparse
sparser|sparse
sparsest|sparse
spontaneous|spontaneously
springboard|springboards
springboard's|springboards
sputter|sputters
sputter's|sputters
sputtered|sputters
sputtering|sputters
squirm|squirming
squirm's|squirming
squirmed|squirming
squirms|squirming
stab|stabbed
stabilization's|stabilization
stabs|stabbed
staled|stale
staleness|stale
staler|stale
stales|stale
stalest|stale
staling|stale
standoff's|standoff
standoffs|standoff
static's|static
statics|static
steepening|steepened
stir's|stir
stitched-one|stitched-ones
storage's|storage
store|stored
storehouse's|storehouse
storehouses|storehouse
storing|stored
string's|string
stringed|string
stringer|string
stringers|string
stringing|string
strings|string
supposition's|supposition
suppositions|supposition
sureties|surety
surety's|surety
surgeon's|surgeon
surgeons|surgeon
surgeries|surgery
surgery's|surgery
surgically|surgical
sync's|sync
synced|sync
syncing|sync
tax-man|tax-men
tempt|tempted
tempter|tempted
tempters|tempted
temptingly|tempting
tempts|tempted
tendon|tendons
tendon's|tendons
thistle's|thistle
thistles|thistle
thunderclap's|thunderclap
thunderclaps|thunderclap
thunderstorm's|thunderstorm
thunderstorms|thunderstorm
thunk|thunks
timelier|timely
timeliest|timely
timeliness|timely
tonsure|tonsured
tonsure's|tonsured
tonsures|tonsured
tonsuring|tonsured
toxin|toxins
toxin's|toxins
trace's|trace
traced|trace
tracer|trace
tracers|trace
traces|trace
tracings|trace
track-rail|track-rails
track's|trackers
tracked|trackers
tracker|trackers
transport|transporting
transport's|transporting
transportable|transporting
transported|transporting
transporter|transporting
transporters|transporting
transports|transporting
tribute|tributes
trip's|trip
triply|trip
trips|trip
turd's|turd
turds|turd
turgidly|turgid
unblinkingly|unblinking
undertaking's|undertaking
unfurl|unfurled
unfurling|unfurled
unkindest|unkind
unlatched|unlatch
unlatches|unlatch
unlatching|unlatch
unsealed|unsealing
unseals|unsealing
unsheathe|unsheathed
unsheathes|unsheathed
unsheathing|unsheathed
unsling|unslung
unslinging|unslung
unslings|unslung
untangle|untangling
untangled|untangling
untangles|untangling
untied|untie
unties|untie
untimeliest|untimely
unwinding|unwind
unwinds|unwind
unwisely|unwise
unwiser|unwise
unwisest|unwise
unwound|unwind
uptake's|uptake
uptakes|uptake
urine's|urine
usurped|usurp
usurper|usurp
usurpers|usurp
usurping|usurp
usurps|usurp
verbalize|verbalizes
verbalized|verbalizes
verbalizing|verbalizes
vestries|vestry
vestry's|vestry
vigilante's|vigilante
vigilantes|vigilante
wager's|wager
wagered|wager
wagerer|wager
wagerers|wager
wagering|wager
watcher's|watcher
weir|weirs
weir's|weirs
weld's|weld
weldable|weld
welded|weld
welder|weld
welders|weld
welding|weld
welds|weld
whipping|whipped
whittle|whittling
whittled|whittling
whittler|whittling
whittlers|whittling
whittles|whittling
wince|winces
wince's|winces
winced|winces
wincing|winces
wither|withered
witherings|withered
withstanding|withstand
withstands|withstand
woe's|woe
woes|woe
wryly|wry
yew's|yew
yews|yew
""";

        private static IEnumerable<OrcishLexiconEntry> BuildBlogHighYieldCandidateEntries(
            IEnumerable<OrcishLexiconEntry> entries)
        {
            var acceptedEntries = entries.ToList();
            var sourceRoots = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var sourceOrdinal = 0;

            foreach (var english in BlogHighYieldSourceCandidateData.Split(
                         ['\r', '\n'],
                         StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var root = $"ghraz-{EncodeTwentyPageOrdinal(sourceOrdinal++)}";
                sourceRoots.Add(english, root);
                var candidate = new OrcishLexiconEntry(
                    english,
                    root,
                    Tags:
                    [
                        "blog",
                        "blog-high-yield-candidate-batch",
                        "generated",
                        "review-promoted",
                        "close-form-reviewed",
                        $"family-{english}"
                    ]);

                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }

            var nearKinOrdinal = 0;
            foreach (var line in BlogHighYieldNearKinCandidateData.Split(
                         ['\r', '\n'],
                         StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var fields = line.Split('|', 2, StringSplitOptions.TrimEntries);
                var english = fields[0];
                var sourceEnglish = fields[1];
                var root = sourceRoots[sourceEnglish];
                var candidate = new OrcishLexiconEntry(
                    english,
                    CreateThirtyPageNearKinForm(root, english, nearKinOrdinal++),
                    Tags:
                    [
                        "blog",
                        "blog-high-yield-near-kin",
                        "near-kin",
                        "derived-by-rule",
                        "review-promoted",
                        "close-form-reviewed",
                        $"family-{sourceEnglish}"
                    ]);

                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
        }
    }
}
