namespace PlayerAssistant
{
    internal static partial class OrcishTranslatorUtility
    {
        private const string BlogMixedHighYieldSourceCandidateData = """
adventurer-penned
ailment
aisles
all-at-once
alley
analgesic
animism
announces
appetizer
apple-eating
appreciatively
archers
assassinate
atelier
atmospheric
aught
augmentations
authoritative
backtrack
backtracking
bailiwick
banked
bearskin
bindings
biomechanicals
blankly
blindly
blood-scented
bloodstain
blue-white
bone-spears
bottom-right
brass-capped
brass-lined
bringer
brutality
build-up
buttocks
cacophony
catalyst
chute-link
cinnabar
cliff-side
coexist
cold-blooded
colossi
conical
conifer
containment
conversing
counter-litany
coursing
cowled
crabwalks
cross-slash
cubit
cylindrical
decoction
deep-seated
deflates
delays
demoralization
depressed
destabilizing
dining
diorite
disadvantage
dismisses
disorient
disoriented
disposition
distorted
divvies
divvy
door-frame
dossiers
draped
draping
drowns
drowsiness
dual
east-flowing
elephant-head
elucidates
emergent
emperor
encroached
encroaching
envious
establishment
extorting
extortionists
extorts
eying
fireflies
firepit
fish-motif
flails
flesh-stitcher
flopping
focal
forcibly
forefront
foreseeable
frog-men
gleaners
gnaw
good-aligned
goons
grandmothers
gray-white
greatness
green-hued
green-tinted
grey-and-white
grey-white
grizzled
guildhall
h-shaped
haematite
hale
half-buried
half-finished
half-inch
half-merged
handholds
hard-tack
hasten
hasty
hat
hazardous
heart-piston
heretics
heritage
hermetically
high-priest
historical-liturgical
hitter
honey-glazed
hopelessness
hopper
hoppers
hourly
hypnotic
ill-spent
immersed
impart
impishly
imply
improvable
in-between
in-the-moment
inactivated
infuses
inheritors
ink-bound
insisting
interleave
interleaved
interplay
interpretation
interregnum
interspecies
intrusion
jackal
juice
knuckle-walking
landslides
leaden
levied
liberties
liquid-like
lock-picks
long-ago
long-time
lower-ranking
luminance
malfunctioning
man-made
mana
many-limbed
martyr
mega-dungeons
megafauna
melees
memorialize
mended
mercurial
mercury
metaphysical
micro-cuneiform
mid-turn
minister
misaligned
misery
misfortune
mitigates
moose-on-a-boulder
mortuary
motions
moue
moues
mulch
mummification
napped
neck-brace
neck-seam
neolithic
night-time
nightly
non-divine
north-running
occasion
offhand
olive-green
omitted
once-mighty
operational
oracular
overlord
overmuscled
pack-mates
pact-sworn
pad
paleolithic
paranoid
patience
peculiar
permeating
phlegmy
pick-lock
pickpocket
pleadingly
plumed
popped
power-hungry
precedents
priceless
push-and-slide
quest-giver
re-routing
re-stabilize
reasonably
recharging
reckless
red-nail
red-tinged
refill
remarks
remonstrated
resignation
resin-caked
resin-coated
resin-hardened
resin-soaked
retching
retroactively
rewind
rimed
roadway
rust-eaten
rust-snow
safe-keeping
sagged
salt-caked
salt-hardened
salt-sealed
sated
saucers
scanned
screwed
scrutinizes
seclusion
self-consciousness
self-damage
severance
shamanism
shapeless
sharp-whistles
shelf-door
shelf-fungus
shitting
shorthand
silver-furred
silver-maned
siphoning
skitter
slow-moving
slug
soars
soda
sought-after
soul-chilling
soul-obols
specials
spider-webbed
spiderweb
spiderwebs
spore-burst
spore-grenade
spore-pods
stagnating
stalk-blind
stink-bomb
stone-blocked
stone-bug
stone-carved
stone-clad
strider
striders
sub-basement
sub-floor
subversive
suffused
sun-gold
sundered
supernaturals
suppression
surveillance
swamp-stink
swarthy-looking
swordstroke
sympathetic
tacky
tactile
tail-tip
takeovers
ten-foot
terracotta
terse
three-beat
three-legged
throb
thump
thumps
tortoise-shell
totemism
toy
trauma
treatise
trencher
trip-wires
tsunamis
tubby
turnips
uncomfortably
unfair
uninjured
unkindly
unmoving
unstrung
unsurprisingly
vain
verticality
veteran-mercenary
vitals
volcanism
wades
wailing
watchers
well-read
well-rewarded
well-spoken
well-versed
wheel-lock
whirring
white-gold
white-knuckled
white-noise
wildly
willow
wraiths
ziggurat
""";

        private const string BlogMixedHighYieldNearKinCandidateData = """
ailment's|ailment
ailments|ailment
aisle|aisles
aisle's|aisles
alley's|alley
alleys|alley
analgesic's|analgesic
analgesics|analgesic
animism's|animism
announce|announces
announced|announces
announcement|announces
announcer|announces
announcers|announces
announcing|announces
appetizer's|appetizer
appetizers|appetizer
assassinated|assassinate
assassinates|assassinate
assassinating|assassinate
assassination|assassinate
assassinations|assassinate
atelier's|atelier
ateliers|atelier
atmospherics|atmospheric
aught's|aught
aughts|aught
augmentation|augmentations
augmentation's|augmentations
authoritatively|authoritative
authoritativeness|authoritative
backtracked|backtrack
backtracks|backtrack
bailiwick's|bailiwick
bailiwicks|bailiwick
bank|banked
bank's|banked
bankable|banked
banker|banked
bankers|banked
banking|banked
bearskin's|bearskin
bearskins|bearskin
binding's|bindings
biomechanical|biomechanicals
blind's|blindly
blinder|blindly
blinders|blindly
blindest|blindly
bloodstain's|bloodstain
bloodstained|bloodstain
bloodstains|bloodstain
bone-spear|bone-spears
bringer's|bringer
brutalities|brutality
brutality's|brutality
buttock|buttocks
buttock's|buttocks
cacophonies|cacophony
cacophony's|cacophony
catalyst's|catalyst
catalysts|catalyst
cinnabar's|cinnabar
coexisted|coexist
coexisting|coexist
coexists|coexist
colossus|colossi
conically|conical
conifer's|conifer
conifers|conifer
containment's|containment
crabwalk|crabwalks
crabwalked|crabwalks
crabwalking|crabwalks
cubit's|cubit
cubits|cubit
deflate|deflates
deflated|deflates
deflating|deflates
deflation|deflates
delaying|delays
dined|dining
diners|dining
disposition's|disposition
dispositions|disposition
distort|distorted
distorter|distorted
distorting|distorted
divvied|divvies
divvy's|divvies
divvying|divvies
dossier|dossiers
dossier's|dossiers
drape|draped
drape's|draped
draper|draped
drapers|draped
drapes|draped
drownings|drowns
elucidate|elucidates
elucidated|elucidates
elucidating|elucidates
elucidation|elucidates
elucidations|elucidates
emperor's|emperor
emperors|emperor
encroach|encroached
encroaches|encroached
encroachment|encroached
enviously|envious
enviousness|envious
establishment's|establishment
extort|extorting
extorted|extorting
extortionist|extortionists
extortionist's|extortionists
firefly|fireflies
firefly's|fireflies
flail|flails
flail's|flails
flailed|flails
focally|focal
forefront's|forefront
forefronts|forefront
foresee|foreseeable
foreseer|foreseeable
foreseers|foreseeable
foresees|foreseeable
frog-man|frog-men
glean|gleaners
gleaned|gleaners
gleaner|gleaners
gleaning|gleaners
gleanings|gleaners
gleans|gleaners
gnawed|gnaw
gnawing|gnaw
gnaws|gnaw
goon|goons
goon's|goons
grandmother|grandmothers
grandmother's|grandmothers
grandmotherly|grandmothers
grizzle|grizzled
grizzles|grizzled
grizzling|grizzled
guildhall's|guildhall
guildhalls|guildhall
hale's|hale
haled|hale
haler|hale
hales|hale
halest|hale
haling|hale
handhold|handholds
handhold's|handholds
hastened|hasten
hastening|hasten
hastier|hasty
hastiest|hasty
hastiness|hasty
hat's|hat
hats|hat
hazardously|hazardous
heretic's|heretics
heritage's|heritage
heritages|heritage
hermetical|hermetically
hitter's|hitter
hitters|hitter
hopper's|hopper
hour's|hourly
hypnotic's|hypnotic
hypnotics|hypnotic
immerse|immersed
immerses|immersed
immersing|immersed
immersive|immersed
imparted|impart
imparting|impart
imparts|impart
impish|impishly
impishness|impishly
implications|imply
implied|imply
implies|imply
implying|imply
infuse|infuses
infusing|infuses
inheritor|inheritors
inheritor's|inheritors
insistingly|insisting
interleaves|interleave
interleaving|interleave
interplay's|interplay
interpretation's|interpretation
interpretations|interpretation
interregnum's|interregnum
interregnums|interregnum
intrusion's|intrusion
intrusions|intrusion
jackal's|jackal
jackals|jackal
juice's|juice
juiced|juice
juicer|juice
juicers|juice
juices|juice
juicing|juice
landslide's|landslides
landsliding|landslides
lead's|leaden
leaded|leaden
levies|levied
levy|levied
levy's|levied
levying|levied
liberty|liberties
liberty's|liberties
lock-pick|lock-picks
malfunction|malfunctioning
malfunction's|malfunctioning
malfunctioned|malfunctioning
malfunctions|malfunctioning
martyr's|martyr
martyred|martyr
martyring|martyr
martyrs|martyr
melee's|melees
memorialized|memorialize
memorializes|memorialize
memorializing|memorialize
mend|mended
mend's|mended
mender|mended
menders|mended
mends|mended
mercurially|mercurial
mercuries|mercury
mercury's|mercury
metaphysically|metaphysical
minister's|minister
ministered|minister
ministering|minister
ministers|minister
miseries|misery
misery's|misery
misfortune's|misfortune
misfortunes|misfortune
mitigate|mitigates
mitigated|mitigates
mitigating|mitigates
mitigation|mitigates
mortuaries|mortuary
mortuary's|mortuary
moue's|moue
mulch's|mulch
mulched|mulch
mulches|mulch
mulching|mulch
mummification's|mummification
nap|napped
napping|napped
naps|napped
night's|nightly
occasion's|occasion
occasioned|occasion
occasioning|occasion
occasions|occasion
operationally|operational
overlord's|overlord
overlords|overlord
pack-mate|pack-mates
pad's|pad
pads|pad
paleolithic's|paleolithic
paranoid's|paranoid
paranoids|paranoid
patience's|patience
peculiarly|peculiar
permeate|permeating
permeated|permeating
permeates|permeating
permeation|permeating
pickpocket's|pickpocket
pickpockets|pickpocket
pleading's|pleadingly
precedent|precedents
precedent's|precedents
recklessly|reckless
recklessness|reckless
refill's|refill
refillable|refill
remarking|remarks
remonstrate|remonstrated
remonstrates|remonstrated
remonstrating|remonstrated
resignation's|resignation
resignations|resignation
retch|retching
retched|retching
retches|retching
retroactive|retroactively
rewind's|rewind
rewindable|rewind
roadway's|roadway
roadways|roadway
sate|sated
sates|sated
sating|sated
saucer|saucers
screw|screwed
screwing|screwed
screws|screwed
scrutinize|scrutinizes
scrutinizing|scrutinizes
seclusion's|seclusion
severance's|severance
severances|severance
shapelessly|shapeless
shapelessness|shapeless
shorthand's|shorthand
shorthanded|shorthand
siphon|siphoning
siphon's|siphoning
siphoned|siphoning
siphons|siphoning
skittered|skitter
skitters|skitter
slug's|slug
slugs|slug
soar|soars
soar's|soars
soared|soars
soaring|soars
soda's|soda
sodas|soda
soul-obol|soul-obols
special's|specials
specially|specials
spiderweb's|spiderweb
spore-pod|spore-pods
stagnate|stagnating
stagnated|stagnating
stagnates|stagnating
stagnation|stagnating
subversive's|subversive
subversively|subversive
subversiveness|subversive
subversives|subversive
suffuse|suffused
suffuses|suffused
suffusing|suffused
suffusion|suffused
sunder|sundered
sundering|sundered
sunders|sundered
suppression's|suppression
surveillance's|surveillance
tackier|tacky
tackiest|tacky
tackiness|tacky
takeover|takeovers
takeover's|takeovers
terracotta's|terracotta
tersely|terse
terseness|terse
terser|terse
tersest|terse
throb's|throb
throbs|throb
thump's|thump
thumped|thump
toy's|toy
toyed|toy
toying|toy
toys|toy
trauma's|trauma
traumas|trauma
treatise's|treatise
treatises|treatise
trencher's|trencher
trenchers|trencher
trip-wire|trip-wires
tsunami|tsunamis
tsunami's|tsunamis
tubbier|tubby
tubbiest|tubby
turnip|turnips
turnip's|turnips
unfairer|unfair
unfairest|unfair
unfairly|unfair
unfairness|unfair
unkindliest|unkindly
unstring|unstrung
unstringing|unstrung
unstrings|unstrung
vainer|vain
vainest|vain
vainly|vain
wade|wades
wade's|wades
wailing's|wailing
watch's|watchers
watchable|watchers
wild's|wildly
wilder|wildly
wildest|wildly
wildness|wildly
willow's|willow
willows|willow
""";

        private static IEnumerable<OrcishLexiconEntry> BuildBlogMixedHighYieldCandidateEntries(
            IEnumerable<OrcishLexiconEntry> entries)
        {
            var acceptedEntries = entries.ToList();
            var sourceRoots = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var sourceOrdinal = 0;

            foreach (var english in BlogMixedHighYieldSourceCandidateData.Split(
                         ['\r', '\n'],
                         StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var root = $"skraz-{EncodeTwentyPageOrdinal(sourceOrdinal++)}";
                sourceRoots.Add(english, root);
                var candidate = new OrcishLexiconEntry(
                    english,
                    root,
                    Tags:
                    [
                        "blog",
                        "blog-mixed-high-yield-candidate-batch",
                        "generated",
                        "review-promoted",
                        "close-form-reviewed",
                        $"family-{english}"
                    ]);

                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }

            var nearKinOrdinal = 0;
            foreach (var line in BlogMixedHighYieldNearKinCandidateData.Split(
                         ['\r', '\n'],
                         StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var fields = line.Split('|', 2, StringSplitOptions.TrimEntries);
                var english = fields[0];
                var sourceEnglish = fields[1];
                var root = sourceRoots[sourceEnglish];
                var candidate = new OrcishLexiconEntry(
                    english,
                    CreateThirtyPageNearKinForm(root, english, nearKinOrdinal++),
                    Tags:
                    [
                        "blog",
                        "blog-mixed-high-yield-near-kin",
                        "near-kin",
                        "derived-by-rule",
                        "review-promoted",
                        "close-form-reviewed",
                        $"family-{sourceEnglish}"
                    ]);

                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
        }
    }
}
