namespace PlayerAssistant
{
    internal static partial class OrcishTranslatorUtility
    {
        private const string GutenbergCorpusSourceCandidateData = """
abode
abrupt
accents
accession
accommodation
accomplishment
accordance
accursed
achievements
adieu
administered
admirably
advisable
affections
affliction
afloat
aft
agricultural
airs
alarming
alleged
allegiance
allotted
allusion
almighty
amen
amuse
amused
anew
annoyed
anon
anxiously
apartment
apartments
appalling
apparition
apprehension
apprehensions
approve
approved
apt
archbishop
ardent
artillery
arts
ashore
assailed
assertion
assuredly
astonished
astonishing
astonishment
asylum
attachment
attendance
attentions
attire
attired
aunt
avenue
awful
awfully
babe
baby
baffled
bah
banner
banquet
barbarous
barn
battalion
battalions
bayonets
beads
beer
begged
beheld
behold
berth
beseech
bewildered
bid
bids
biggest
bishop
bishops
blank
bliss
bloodshed
bombardment
bonnet
booty
bosom
boughs
bower
breadth
breast
breasts
bride
brigade
brightness
brink
brisk
brother's
buffalo
bush
bushes
buttons
cabin
cabinet
calf
canal
cane
captain's
car
cardinal
cared
carriage
carriages
cars
casualties
cent
cents
champagne
chap
charity
cheerful
cheerfully
cherished
child's
chivalry
cigar
cigarette
clasped
clergyman
clung
coach
college
collision
colonel
commandant
commander-in-chief
committee
companies
comparative
comparatively
compel
complaint
complaints
complexion
composure
conception
concerning
concerns
concrete
confessed
confession
confidential
confined
confinement
congress
consecrated
considerations
consistent
consolation
conspicuous
consternation
consultation
continuous
contrary
contrived
controversy
convent
coolness
cordially
corporal
correspondent
costume
couch
countenance
countrymen
county
courageous
cove
crazy
cream
creed
creek
criticism
cruise
cruising
dainty
dam
dame
darling
daughter's
dawned
daybreak
dazzling
deaf
decidedly
department
deprive
deprived
desirable
desirous
detained
devoid
didst
diet
dignified
dignity
dining-room
disclosed
dish
dishes
dismal
dismay
disorder
disturb
ditch
doctor
doctor's
doctors
doings
dollar
dollars
dominion
dominions
dost
doth
doubly
doubtful
doubtless
dove
drama
dramatic
dreary
drunken
duel
duly
dumb
dusky
earl
earth's
earthly
effectual
effectually
ejaculated
election
eloquent
embarked
embarrassed
embarrassment
embassy
eminence
eminent
encamped
endowed
enemy's
engagement
engines
enlightened
enlisted
enmity
enthusiastic
envelope
ere
esteem
esteemed
etiquette
everlasting
excite
exclusive
exertion
exertions
exhibition
expedient
expelled
expressions
extremity
eyed
factory
faculties
faculty
fain
fairest
falsehood
fastened
favorable
fellow's
feminine
ferry
fidelity
fitted
flag
flags
flew
flock
flocks
flour
fond
forbade
forefathers
foremost
forenoon
fowl
fowls
fragrant
frankly
friend's
fright
fringe
fruitless
fugitive
fugitives
fundamental
furnish
furnished
futile
gaily
gale
gallant
gallantly
gallantry
gallop
galloped
galloping
garment
garments
gay
geese
general's
generals
genius
gentlemen
gilt
girl's
glee
gloomily
glowed
god's
good-bye
good-night
goose
gorge
gorgeous
gospel
governors
gown
gracious
graciously
gratified
gratify
grievous
grimly
guilty
gulf
gun
gunpowder
guns
habitation
half-past
half-way
harbor
hare
hark
hast
hastily
hatchet
hath
heart's
heartily
hearty
heath
heathen
hen
hence
highness
highway
hind
historic
hither
hitherto
hoarse
hoarsely
holiday
homeward
honesty
hopeless
horse's
hospital
hotel
housekeeper
hurrah
hymn
idiot
idle
ignorance
ignorant
illustrious
imaginary
impelled
impenetrable
imperfect
impetuous
implored
impossibility
impregnable
impudent
impulse
incessant
incessantly
inclination
inconvenience
independence
indications
indignation
indispensable
indulge
infancy
infant
inferior
ingenuity
inmates
insensible
insolence
insolent
insults
insurrection
interference
interposed
interpreter
interview
invaders
irregular
irresistible
irritated
isle
jealousy
jolly
joyful
joyfully
joyous
justly
kindled
kindred
king's
knelt
knives
lace
lady's
lain
lame
lamentations
landlord
lark
latitude
lawn
lawyer
lecture
leisure
leisurely
lesson
lessons
liberal
literary
lively
locality
lofty
longed
loosened
lord's
luggage
lump
luxurious
madam
madame
magnificence
majestic
manhood
manned
mansion
mar
mare
marine
marquis
marriage
marvel
massacre
mast
master's
masts
mat
meadow
melancholy
memorial
mess
messenger
messengers
mice
mingled
ministry
mirth
mischief
miserable
missionary
mistress
mob
moment's
monotonous
monotony
monsieur
moonlight
mother's
motioned
motor
mourning
multitude
murderous
music
musicians
musket
muskets
mutiny
naked
namely
naught
navy
nay
neglect
neglected
nineteenth
nobly
noisy
numberless
nurse
oar
oars
objected
objection
objections
obligations
obscurity
obstinate
offspring
old-fashioned
one-half
opinion
oppressed
ordained
oriental
ornament
ornaments
ought
outrage
outset
overtake
packet
paddle
pail
palace
palaces
panting
par
paradise
parapet
parish
parliament
passion
passions
pathetic
patriotic
patriotism
peculiarity
peered
peninsula
penny
perchance
perils
perpendicular
persecuted
persecution
personage
petition
philosopher
physician
piano
pictured
picturesque
piety
pink
pioneers
pistol
pistols
pitiful
pity
planks
plea
plentiful
poem
poems
poet
poetry
poets
policeman
policy
pomp
ponderous
pope
prairie
precaution
precautions
preference
prejudice
preparations
president
pretext
prince's
princely
principal
principally
probable
procession
professed
professor
promontory
prophet
proportion
proportions
proposal
propriety
prostrate
province
provinces
provincial
prudence
pursuers
pursuits
quaint
quarrel
queen's
queer
quit
raged
railroad
railway
rainy
ramparts
rapidity
rascal
ravine
recourse
reform
refuge
regiment
regiments
regretted
regulations
rein
rejoice
rejoiced
rejoicing
reproach
republic
resolute
resounded
retorted
revolt
revolutionary
ribbon
rice
rifle
rifles
rigging
ripe
romantic
roses
rosy
rouse
roused
royalty
rubbed
ruddy
rude
rum
salary
salute
saluted
salvation
saturday
scandal
scanty
scarce
scarcely
scare
scenery
scorn
scornfully
scoundrel
seaman
seamen
secretary
securely
senseless
sensible
september
seventh
shady
shalt
shameful
shillings
ship's
shipping
showers
shrank
sighted
sights
silly
sincerity
sinister
sixteenth
sleepy
slim
smote
snapped
so-called
sobbed
sobbing
sofa
sojourn
solitary
son's
sorely
sorrow
sorrowful
sorrows
sovereignty
spake
speaker
spectacle
spectators
sped
speedily
speedy
spirited
splendid
splendor
sprinkled
squadron
stammered
stately
stead
steed
steeds
steer
steered
steering
sterling
steward
stockings
stormy
straightway
strained
strait
straits
streamed
streaming
strenuous
strewn
strife
stripped
strode
strove
stump
stupendous
subjection
submission
subordinate
subsistence
sullen
sunday
sunshine
superintendent
surmounted
suspense
swam
swan
swung
telegraph
telephone
tempest
tender
tenderly
tenderness
tenth
terrace
terrible
terrific
testimony
thereupon
thicket
thither
thou
thrill
thrilling
thyself
tidings
token
ton
tons
tore
torrent
tramp
tranquil
trench
trenches
trinity
triumphant
trod
tropical
troublesome
trumpet
trumpets
tumult
tune
turf
twelfth
twinkling
uncommon
undertaken
undertook
unhappy
uniform
uniforms
union
unite
united
unity
unjust
unnecessary
unworthy
uplifted
uproar
upwards
utterance
vanquished
vegetable
velocity
verge
verily
veritable
vexed
vigilance
vile
virtuous
voyage
voyages
vulgar
waistcoat
wan
wanderings
warmly
wearily
wedding
weird
welfare
wept
wheat
whence
whilst
whites
whither
wilt
withal
withdrawal
wives
woman's
wooded
workmen
worldly
wreck
wrecked
wretch
wretches
wrongs
yea
year's
yer
yoke
yonder
youths
""";

        private const string GutenbergCorpusNearKinCandidateData = """
abode's|abode
abodes|abode
abrupter|abrupt
abruptest|abrupt
abruptness|abrupt
accent's|accents
accented|accents
accenting|accents
accession's|accession
accessioned|accession
accessioning|accession
accessions|accession
accommodation's|accommodation
accomplishment's|accomplishment
accomplishments|accomplishment
accordance's|accordance
accursedness|accursed
achievement's|achievements
adieu's|adieu
adieus|adieu
administer|administered
administering|administered
administers|administered
affliction's|affliction
afflictions|affliction
afters|aft
agriculturally|agricultural
air's|airs
aired|airs
airing|airs
airings|airs
alarmingly|alarming
allegedly|alleged
allegiance's|allegiance
allot|allotted
allots|allotted
allotting|allotted
allusion's|allusion
allusions|allusion
almighty's|almighty
amen's|amen
amenable|amen
amuses|amuse
annoy|annoyed
annoys|annoyed
anons|anon
anxiousness|anxiously
apartment's|apartment
appallingly|appalling
apparition's|apparition
apparitions|apparition
apprehension's|apprehension
approves|approve
approving|approve
aptest|apt
aptly|apt
aptness|apt
archbishop's|archbishop
archbishops|archbishop
ardently|ardent
art's|arts
artillery's|artillery
assail|assailed
assailable|assailed
assailing|assailed
assails|assailed
assertion's|assertion
assured's|assuredly
assureds|assuredly
astonish|astonished
astonishes|astonished
astonishingly|astonishing
astonishment's|astonishment
asylum's|asylum
asylums|asylum
attachment's|attachment
attendance's|attendance
attendances|attendance
attire's|attire
attires|attire
attiring|attire
aunt's|aunt
aunts|aunt
avenue's|avenue
avenues|avenue
awfulness|awful
babe's|babe
babes|babe
babied|baby
babier|baby
babies|baby
babiest|baby
baby's|baby
babying|baby
baffle|baffled
baffle's|baffled
bafflement|baffled
baffler|baffled
bafflers|baffled
baffles|baffled
baffling|baffled
banner's|banner
banners|banner
banquet's|banquet
banqueted|banquet
banqueter|banquet
banqueters|banquet
banqueting|banquet
banquets|banquet
barbarously|barbarous
barn's|barn
barns|barn
battalion's|battalion
bayonet|bayonets
bayonet's|bayonets
bayoneted|bayonets
bayoneting|bayonets
bead|beads
bead's|beads
beaded|beads
beer's|beer
beholden|behold
beholding|behold
beholds|behold
berth's|berth
berthed|berth
berthing|berth
beseecher|beseech
beseechers|beseech
beseeches|beseech
beseeching|beseech
bewilder|bewildered
bewildering|bewildered
bewilderment|bewildered
bewilders|bewildered
bid's|bid
biding|bid
bishop's|bishop
blank's|blank
blanked|blank
blanker|blank
blankest|blank
blanking|blank
blankness|blank
blanks|blank
bloodshed's|bloodshed
bombardment's|bombardment
bombardments|bombardment
bonnet's|bonnet
bonnets|bonnet
booties|booty
booty's|booty
bosoms|bosom
bough|boughs
bower's|bower
breadth's|breadth
breast's|breast
breasted|breast
breasting|breast
bride's|bride
brides|bride
brigade's|brigade
brigades|brigade
brink's|brink
brinks|brink
brisked|brisk
brisker|brisk
briskest|brisk
brisking|brisk
briskly|brisk
briskness|brisk
brisks|brisk
brotherly|brother's
buffalo's|buffalo
buffaloed|buffalo
buffaloing|buffalo
bush's|bush
bushed|bush
bushing|bush
bushings|bush
button|buttons
buttoned|buttons
buttoning|buttons
cabin's|cabin
cabinet's|cabinet
cabinets|cabinet
cabins|cabin
calf's|calf
canal's|canal
canals|canal
cane's|cane
canes|cane
car's|car
cardinal's|cardinal
cardinally|cardinal
cardinals|cardinal
carer|car
carers|car
caring|car
carriage's|carriage
casualty|casualties
casualty's|casualties
cent's|cent
champagne's|champagne
champagnes|champagne
chap's|chap
chaps|chap
charities|charity
charity's|charity
cherish|cherished
cherishes|cherished
cherishing|cherished
chivalry's|chivalry
cigar's|cigar
cigarette's|cigarette
cigarettes|cigarette
cigars|cigar
clasp|clasped
clasping|clasped
clasps|clasped
clergyman's|clergyman
coach's|coach
coached|coach
coaches|coach
coaching|coach
college's|college
colleges|college
collision's|collision
collisions|collision
colonel's|colonel
colonels|colonel
commandant's|commandant
commandants|commandant
committee's|committee
committees|committee
company's|companies
comparative's|comparative
comparatives|comparative
compels|compel
complaint's|complaint
complexion's|complexion
complexioned|complexion
complexions|complexion
composure's|composure
conception's|conception
conceptions|conception
concrete's|concrete
concreted|concrete
concretely|concrete
concreteness|concrete
concretes|concrete
concreting|concrete
concretion|concrete
concretions|concrete
confessedly|confessed
confession's|confession
confessions|confession
confidentially|confidential
confinement's|confinement
confinements|confinement
congresses|congress
consecrate|consecrated
consecrates|consecrated
consecrating|consecrated
consistently|consistent
consolation's|consolation
consolations|consolation
conspicuously|conspicuous
conspicuousness|conspicuous
consternation's|consternation
consultation's|consultation
consultations|consultation
continuously|continuous
contraries|contrary
contrariness|contrary
contrary's|contrary
contrive|contrived
contriver|contrived
contrivers|contrived
contrives|contrived
contriving|contrived
controversies|controversy
controversy's|controversy
convent's|convent
convents|convent
cordial's|cordially
cordials|cordially
corporal's|corporal
corporals|corporal
correspondent's|correspondent
correspondents|correspondent
costume's|costume
costumed|costume
costumer|costume
costumers|costume
costumes|costume
costuming|costume
couch's|couch
couched|couch
couches|couch
couching|couch
countenanced|countenance
countenances|countenance
countenancing|countenance
counties|county
countryman|countrymen
county's|county
courageously|courageous
courageousness|courageous
cove's|cove
coves|cove
crazier|crazy
crazies|crazy
craziest|crazy
craziness|crazy
crazy's|crazy
cream's|cream
creamed|cream
creamer|cream
creamers|cream
creaming|cream
creams|cream
creed's|creed
creeds|creed
creek's|creek
creeks|creek
criticism's|criticism
criticisms|criticism
cruise's|cruise
cruised|cruise
cruiser|cruise
cruisers|cruise
cruises|cruise
daintier|dainty
dainties|dainty
daintiest|dainty
daintiness|dainty
dainty's|dainty
dam's|dam
dame's|dame
dames|dame
damion|dame
dams|dam
darling's|darling
darlings|darling
daughterly|daughter's
dawn's|dawned
dawning|dawned
daybreak's|daybreak
dazzlingly|dazzling
deafens|deaf
deafer|deaf
deafest|deaf
department's|department
departments|department
deprives|deprive
depriving|deprive
detain|detained
detaining|detained
detainment|detained
detains|detained
diet's|diet
dieted|diet
dieter|diet
dieters|diet
dieting|diet
diets|diet
dignifies|dignified
dignify|dignified
dignifying|dignified
dignities|dignity
dignity's|dignity
disclose|disclosed
discloses|disclosed
disclosing|disclosed
dish's|dish
dished|dish
dishing|dish
dismally|dismal
dismay's|dismay
dismayed|dismay
dismaying|dismay
dismays|dismay
disorderly|disorder
disturber|disturb
disturbers|disturb
disturbs|disturb
ditch's|ditch
ditched|ditch
ditches|ditch
ditching|ditch
do's|doth
doctored|doctor
doctoring|doctor
doer|doth
doers|doth
doing|doings
doing's|doings
dollar's|dollar
dominion's|dominion
dos|doth
doubtfully|doubtful
doubtfulness|doubtful
doubtlessly|doubtless
dove's|dove
doves|dove
drama's|drama
dramas|drama
dramatics|dramatic
drearier|dreary
dreariest|dreary
dreariness|dreary
drunkenly|drunken
drunkenness|drunken
duel's|duel
dueled|duel
dueler|duel
duelers|duel
dueling|duel
duelings|duel
duels|duel
dumber|dumb
dumbest|dumb
dumbly|dumb
dumbness|dumb
duskier|dusky
duskiest|dusky
duskiness|dusky
earl's|earl
earls|earl
earthlier|earthly
earthliest|earthly
ejaculate|ejaculated
ejaculates|ejaculated
ejaculating|ejaculated
ejaculation|ejaculated
ejaculations|ejaculated
election's|election
elections|election
eloquently|eloquent
embark|embarked
embarking|embarked
embarks|embarked
embarrass|embarrassed
embarrasses|embarrassed
embarrassment's|embarrassment
embarrassments|embarrassment
embassies|embassy
embassy's|embassy
eminence's|eminence
eminences|eminence
eminently|eminent
encamp|encamped
encamping|encamped
encamps|encamped
endow|endowed
endowing|endowed
endowment|endowed
endows|endowed
engagement's|engagement
engagements|engagement
engine's|engines
enlighten|enlightened
enlightening|enlightened
enlightens|enlightened
enlist|enlisted
enlisting|enlisted
enlistment|enlisted
enlists|enlisted
enmities|enmity
enmity's|enmity
envelope's|envelope
envelopes|envelope
esteem's|esteem
esteeming|esteem
esteems|esteem
etiquette's|etiquette
everlasting's|everlasting
everlastingly|everlasting
everlastings|everlasting
excitable|excite
exciter|excite
exciters|excite
excites|excite
exclusive's|exclusive
exclusiveness|exclusive
exclusives|exclusive
exertion's|exertion
exhibition's|exhibition
exhibitions|exhibition
expedient's|expedient
expediently|expedient
expedients|expedient
expel|expelled
expelling|expelled
expels|expelled
expression's|expressions
extremities|extremity
extremity's|extremity
factories|factory
factory's|factory
faculty's|faculties
fainer|fain
fainest|fain
fair's|fairest
fairer|fairest
fairing|fairest
fairings|fairest
falsehood's|falsehood
falsehoods|falsehood
fasten|fastened
fastening|fastened
fastens|fastened
feminine's|feminine
femininely|feminine
feminines|feminine
ferried|ferry
ferries|ferry
ferry's|ferry
ferrying|ferry
fidelity's|fidelity
flag's|flag
flock's|flock
flocked|flock
flocking|flock
flour's|flour
floured|flour
flouring|flour
flours|flour
flown|flew
fonder|fond
fondest|fond
fondly|fond
fondness|fond
forbidding|forbade
forefather|forefathers
forefather's|forefathers
forenoon's|forenoon
forenoons|forenoon
fowl's|fowl
fowled|fowl
fowling|fowl
fragrantly|fragrant
frank|frankly
frank's|frankly
franked|frankly
franker|frankly
frankest|frankly
franking|frankly
frankness|frankly
franks|frankly
fright's|fright
frighted|fright
frightens|fright
frighting|fright
frights|fright
fringed|fringe
fringes|fringe
fringing|fringe
fruitlessly|fruitless
fruitlessness|fruitless
fugitive's|fugitive
fundamental's|fundamental
fundamentally|fundamental
fundamentals|fundamental
furnishes|furnish
furnishing|furnish
futilely|futile
gale's|gale
gales|gale
gallant's|gallant
gallantry's|gallantry
gallants|gallant
gallop's|gallop
gallops|gallop
garment's|garment
gay's|gay
gayer|gay
gayest|gay
gayness|gay
gays|gay
geniuses|genius
gilt's|gilt
gilts|gilt
glee's|glee
glow's|glowed
glower|glowed
glowers|glowed
goose's|goose
goosed|goose
gooses|goose
goosing|goose
gorged|gorge
gorgeously|gorgeous
gorgeousness|gorgeous
gorges|gorge
gorging|gorge
gospel's|gospel
gospels|gospel
governor's|governors
gown's|gown
gowned|gown
gowning|gown
gowns|gown
gratification|gratified
gratifications|gratified
gratifies|gratified
gratifying|gratified
grievously|grievous
grievousness|grievous
grimed|grimly
griming|grimly
grimness|grimly
guiltier|guilty
guiltiest|guilty
guiltiness|guilty
gulf's|gulf
gulfs|gulf
gun's|gun
gunpowder's|gunpowder
habitation's|habitation
habitations|habitation
harbor's|harbor
harbored|harbor
harboring|harbor
harbors|harbor
hare's|hare
hared|hare
hares|hare
haring|hare
harked|hark
harking|hark
harks|hark
hastens|hast
hasting|hast
hatchet's|hatchet
hatchets|hatchet
heartier|hearty
hearties|hearty
heartiest|hearty
heartiness|hearty
hearty's|hearty
heath's|heath
heathen's|heathen
heathens|heath
heather|heath
hen's|hen
highway's|highway
highways|highway
hind's|hind
hinds|hind
hoarseness|hoarse
hoarser|hoarse
hoarsest|hoarse
holiday's|holiday
holidayed|holiday
holidaying|holiday
holidays|holiday
homewards|homeward
honesty's|honesty
hopelessly|hopeless
hospital's|hospital
hospitals|hospital
hotel's|hotel
hotels|hotel
housekeeper's|housekeeper
housekeepers|housekeeper
hurrah's|hurrah
hurrahed|hurrah
hurrahing|hurrah
hymn's|hymn
hymned|hymn
hymning|hymn
hymns|hymn
idiot's|idiot
idiots|idiot
idle's|idle
idled|idle
idleness|idle
idler|idle
idlers|idle
idles|idle
idlest|idle
idling|idle
ignorance's|ignorance
ignorantly|ignorant
illustriously|illustrious
illustriousness|illustrious
imperfect's|imperfect
imperfectly|imperfect
imperfectness|imperfect
imperfects|imperfect
impetuously|impetuous
impetuousness|impetuous
implore|implored
implores|implored
imploring|implored
impossibilities|impossibility
impossibility's|impossibility
impudently|impudent
impulse's|impulse
impulsed|impulse
impulses|impulse
impulsing|impulse
impulsion|impulse
inclination's|inclination
inconvenienced|inconvenience
inconveniencing|inconvenience
independence's|independence
indignation's|indignation
indispensable's|indispensable
indispensables|indispensable
indulged|indulge
indulges|indulge
indulging|indulge
infancy's|infancy
infant's|infant
infants|infant
inferior's|inferior
inferiors|inferior
ingenuity's|ingenuity
inmate|inmates
inmate's|inmates
insolence's|insolence
insolently|insolent
insult's|insults
insulting|insults
insurrection's|insurrection
insurrections|insurrection
interference's|interference
interpose|interposed
interposes|interposed
interposing|interposed
interpreter's|interpreter
interpreters|interpreter
interview's|interview
interviewed|interview
interviewer|interview
interviewers|interview
interviewing|interview
interviews|interview
invader|invaders
irregular's|irregular
irregularly|irregular
irregulars|irregular
irritate|irritated
irritates|irritated
irritating|irritated
irritation|irritated
irritations|irritated
isle's|isle
isles|isle
jealousies|jealousy
jealousy's|jealousy
jollied|jolly
jollier|jolly
jollies|jolly
jolliest|jolly
jolliness|jolly
jolly's|jolly
jollying|jolly
joyfulness|joyful
joyously|joyous
joyousness|joyous
just|justly
juster|justly
justest|justly
justness|justly
kindle|kindled
kindles|kindled
kindred's|kindred
laced|lace
laces|lace
lacing|lace
lame's|lame
lamed|lame
lamely|lame
lameness|lame
lamentation|lamentations
lamentation's|lamentations
lamer|lame
lamers|lame
lames|lame
lamest|lame
laming|lame
landlord's|landlord
landlords|landlord
lark's|lark
larked|lark
larking|lark
larks|lark
latitude's|latitude
latitudes|latitude
lawn's|lawn
lawns|lawn
lawyer's|lawyer
lawyers|lawyer
lecture's|lecture
lectured|lecture
lecturer|lecture
lecturers|lecture
lectures|lecture
lecturing|lecture
leisure's|leisure
leisured|leisure
lesson's|lesson
liberal's|liberal
liberally|liberal
liberalness|liberal
liberals|liberal
literariness|literary
livelier|lively
liveliest|lively
liveliness|lively
localities|locality
locality's|locality
loftier|lofty
loftiest|lofty
loftiness|lofty
longest|longed
longs|longed
loosens|loosened
lordly|lord's
luggage's|luggage
lump's|lump
lumped|lump
lumpen|lump
lumping|lump
lumps|lump
luxuriously|luxurious
luxuriousness|luxurious
madam's|madam
madame's|madame
madams|madam
magnificence's|magnificence
manhood's|manhood
manning|manned
mansion's|mansion
mar's|mar
mare's|mare
mares|mare
marine's|marine
mariner|marine
mariners|marine
marines|marine
marquises|marquis
marriage's|marriage
marriages|marriage
mars|mar
marvel's|marvel
marveled|marvel
marveling|marvel
marvels|marvel
massacre's|massacre
massacred|massacre
massacres|massacre
massacring|massacre
mast's|mast
masted|mast
mat's|mat
mated|mat
mater|mat
maters|mat
mating|mat
mats|mat
meadow's|meadow
melancholy's|melancholy
memorial's|memorial
memorials|memorial
messed|mess
messenger's|messenger
messes|mess
messing|mess
mingle|mingled
mingles|mingled
mingling|mingled
ministries|ministry
ministry's|ministry
mirth's|mirth
mischief's|mischief
missionaries|missionary
missionary's|missionary
mistresses|mistress
mobs|mob
monotonously|monotonous
monotonousness|monotonous
monotony's|monotony
monsieur's|monsieur
moonlight's|moonlight
moonlighted|moonlight
moonlighter|moonlight
moonlighters|moonlight
moonlighting|moonlight
moonlights|moonlight
mothered|mother's
mothering|mother's
motherly|mother's
motor's|motor
motored|motor
motoring|motor
motors|motor
mourning's|mourning
multitude's|multitude
multitudes|multitude
murderously|murderous
music's|music
musician|musicians
musician's|musicians
musicianly|musicians
musics|music
musket's|musket
mutinied|mutiny
mutinies|mutiny
mutiny's|mutiny
mutinying|mutiny
nakedly|naked
nakedness|naked
naught's|naught
naughts|naught
navies|navy
navy's|navy
nay's|nay
nays|nay
neglect's|neglect
neglecting|neglect
neglects|neglect
nineteenth's|nineteenth
noisier|noisy
noisiest|noisy
noisiness|noisy
nurse's|nurse
nursed|nurse
nurser|nurse
nursers|nurse
nurses|nurse
oar's|oar
oared|oar
oaring|oar
object's|objected
objecting|objected
objection's|objection
objectionable|objection
obscurities|obscurity
obscurity's|obscurity
obstinately|obstinate
offspring's|offspring
opinion's|opinion
oppress|oppressed
oppresses|oppressed
oppressing|oppressed
ordain|ordained
ordaining|ordained
ordainment|ordained
ordains|ordained
oriental's|oriental
orientals|oriental
ornament's|ornament
ornamented|ornament
ornamenting|ornament
outrage's|outrage
outraged|outrage
outrages|outrage
outraging|outrage
outset's|outset
outsets|outset
overtakes|overtake
overtaking|overtake
packet's|packet
packets|packet
paddle's|paddle
paddled|paddle
paddler|paddle
paddlers|paddle
paddles|paddle
paddling|paddle
pail's|pail
pails|pail
palace's|palace
pant|panting
pant's|panting
panted|panting
pants|panting
par's|par
parable|par
paradise's|paradise
paradises|paradise
parapet's|parapet
parapets|parapet
pared|par
parer|par
parers|par
paring|par
parings|par
parish's|parish
parishes|parish
parliament's|parliament
parliaments|parliament
pars|par
passion's|passion
patriotism's|patriotism
peculiarities|peculiarity
peculiarity's|peculiarity
peer's|peered
peninsula's|peninsula
peninsulas|peninsula
pennies|penny
penny's|penny
peril's|perils
periled|perils
periling|perils
perpendicular's|perpendicular
perpendicularly|perpendicular
perpendiculars|perpendicular
persecute|persecuted
persecutes|persecuted
persecuting|persecuted
persecution's|persecution
persecutions|persecuted
personage's|personage
personages|personage
petition's|petition
petitioned|petition
petitioner|petition
petitioners|petition
petitioning|petition
petitions|petition
philosopher's|philosopher
philosophers|philosopher
physician's|physician
physicians|physician
piano's|piano
pianos|piano
picture's|pictured
picturesquely|picturesque
picturesqueness|picturesque
picturing|pictured
piety's|piety
pink's|pink
pinked|pink
pinker|pink
pinkest|pink
pinking|pink
pinkness|pink
pinks|pink
pioneer|pioneers
pioneer's|pioneers
pioneered|pioneers
pioneering|pioneers
pistol's|pistol
pitied|pity
pities|pity
pitifully|pitiful
pity's|pity
pitying|pity
plank|planks
plank's|planks
planked|planks
planking|planks
plea's|plea
pleas|plea
plentifully|plentiful
poem's|poem
poet's|poet
poetry's|poetry
policeman's|policeman
policies|policy
policy's|policy
pomp's|pomp
ponderously|ponderous
ponderousness|ponderous
pope's|pope
popes|pope
prairie's|prairie
prairies|prairie
precaution's|precaution
preference's|preference
preferences|preference
prejudice's|prejudice
prejudiced|prejudice
prejudices|prejudice
prejudicing|prejudice
preparation's|preparations
president's|president
presidents|president
pretext's|pretext
pretexts|pretext
princelier|princely
princeliest|princely
princeliness|princely
principal's|principal
principals|principal
probable's|probable
probables|probable
processioned|procession
processioning|procession
professedly|professed
professor's|professor
professors|professor
promontories|promontory
promontory's|promontory
prophet's|prophet
prophets|prophet
proportion's|proportion
proposal's|proposal
proposals|proposal
proprieties|propriety
propriety's|propriety
prostrated|prostrate
prostrates|prostrate
prostrating|prostrate
prostration|prostrate
prostrations|prostrate
province's|province
provincial's|provincial
provincially|provincial
provincials|provincial
prudence's|prudence
pursuer|pursuers
pursues|pursuers
pursuit's|pursuits
quainter|quaint
quaintest|quaint
quaintly|quaint
quaintness|quaint
quarrel's|quarrel
quarreled|quarrel
quarreler|quarrel
quarrelers|quarrel
quarreling|quarrel
queenly|queen's
queer's|queer
queered|queer
queerer|queer
queerest|queer
queering|queer
queerly|queer
queerness|queer
queers|queer
quits|quit
railroad's|railroad
railroaded|railroad
railroader|railroad
railroaders|railroad
railroading|railroad
railroads|railroad
railway's|railway
railways|railway
rainier|rainy
rainiest|rainy
rampart|ramparts
rampart's|ramparts
rapidity's|rapidity
rascal's|rascal
rascally|rascal
rascals|rascal
ravine's|ravine
ravines|ravine
recourse's|recourse
reform's|reform
reformers|reform
refuge's|refuge
refuges|refuge
regiment's|regiment
regimented|regiment
regimenting|regiment
reined|rein
reining|rein
rejoices|rejoice
rejoicing's|rejoicing
rejoicings|rejoice
reproach's|reproach
reproachable|reproach
reproached|reproach
reproaches|reproach
reproaching|reproach
republics|republic
resolutely|resolute
resoluteness|resolute
resound|resounded
resounds|resounded
retort|retorted
retort's|retorted
retorting|retorted
revolted|revolt
revolting|revolt
revolutionaries|revolutionary
revolutionary's|revolutionary
ribbon's|ribbon
ribbons|ribbon
rice's|rice
riced|rice
ricer|rice
ricers|rice
rices|rice
ricing|rice
rifle's|rifle
rifled|rifle
rifler|rifle
riflers|rifle
rifling|rifle
rigging's|rigging
ripely|ripe
ripeness|ripe
romantic's|romantic
romantics|romantic
rose's|roses
rosier|rosy
rosiest|rosy
rosiness|rosy
rouses|rouse
rousing|rouse
royalties|royalty
royalty's|royalty
ruddier|ruddy
ruddiest|ruddy
ruddiness|ruddy
rudely|rude
rudeness|rude
ruder|rude
rudest|rude
rum's|rum
rums|rum
salaried|salary
salaries|salary
salary's|salary
salute's|salute
salutes|salute
saluting|salute
salvation's|salvation
saturday's|saturday
saturdays|saturday
scandal's|scandal
scandals|scandal
scantier|scanty
scanties|scanty
scantiest|scanty
scantiness|scanty
scarceness|scarce
scarcer|scarce
scarcest|scarce
scare's|scare
scares|scare
scenery's|scenery
scorn's|scorn
scorned|scorn
scorner|scorn
scorners|scorn
scornful|scornfully
scorning|scorn
scorns|scorn
scoundrel's|scoundrel
scoundrels|scoundrel
seaman's|seaman
secretaries|secretary
secretary's|secretary
securer|securely
securest|securely
senselessly|senseless
senselessness|senseless
sensibleness|sensible
september's|september
septembers|september
seventh's|seventh
shadier|shady
shadiest|shady
shadiness|shady
shamefully|shameful
shamefulness|shameful
shipping's|shipping
show's|showers
showings|showers
shrunk|shrank
sight's|sighted
sightly|sighted
sillier|silly
sillies|silly
silliest|silly
silliness|silly
silly's|silly
sincerity's|sincerity
sixteenth's|sixteenth
sleepier|sleepy
sleepiest|sleepy
sleepiness|sleepy
slimness|slim
slims|slim
smitten|smote
sob|sobbed
sobbingly|sobbing
sobs|sobbed
sofa's|sofa
sofas|sofa
sojourn's|sojourn
sojourned|sojourn
sojourner|sojourn
sojourners|sojourn
sojourning|sojourn
sojourns|sojourn
solitaries|solitary
solitariness|solitary
solitary's|solitary
sore's|sorely
soreness|sorely
sorer|sorely
sores|sorely
sorest|sorely
sorrow's|sorrow
sorrowed|sorrow
sorrowfully|sorrowful
sorrowfulness|sorrowful
sorrowing|sorrow
sovereignty's|sovereignty
speaker's|speaker
spectacle's|spectacle
spectator|spectators
spectator's|spectators
speedier|speedy
speediest|speedy
speediness|speedy
spiritedly|spirited
splendider|splendid
splendidest|splendid
splendidly|splendid
splendor's|splendor
splendors|splendor
sprinkle|sprinkled
sprinkle's|sprinkled
sprinkler|sprinkled
sprinklers|sprinkled
sprinkles|sprinkled
sprinkling|sprinkled
sprinklings|sprinkled
squadron's|squadron
squadrons|squadron
stammer|stammered
stammer's|stammered
stammerer|stammered
stammerers|stammered
stammering|stammered
stammers|stammered
statelier|stately
stateliest|stately
stateliness|stately
stead's|stead
steads|stead
steed's|steed
steer's|steer
steerable|steer
steering's|steering
steers|steer
sterling's|sterling
steward's|steward
stewarded|steward
stewarding|steward
stewards|steward
stocking's|stockings
stormier|stormy
stormiest|stormy
storminess|stormy
strait's|strait
straiten|strait
straitens|strait
stream's|streamed
streamer|streamed
streamers|streamed
strenuously|strenuous
strenuousness|strenuous
strew|strewn
strewed|strewn
strewing|strewn
strews|strewn
stridden|strode
strife's|strife
strips|stripped
striven|strove
stump's|stump
stumped|stump
stumping|stump
stumps|stump
stupendously|stupendous
subjection's|subjection
submission's|submission
submissions|submission
subordinate's|subordinate
subordinated|subordinate
subordinates|subordinate
subordinating|subordinate
subordination|subordinate
subsistence's|subsistence
sullener|sullen
sullenest|sullen
sullenly|sullen
sullenness|sullen
sunday's|sunday
sundays|sunday
sunshine's|sunshine
superintendent's|superintendent
superintendents|superintendent
surmount|surmounted
surmountable|surmounted
surmounting|surmounted
surmounts|surmounted
suspense's|suspense
suspension|suspense
suspensions|suspense
swan's|swan
swans|swan
swum|swam
telegraph's|telegraph
telegraphed|telegraph
telegrapher|telegraph
telegraphers|telegraph
telegraphing|telegraph
telephone's|telephone
telephoned|telephone
telephoner|telephone
telephoners|telephone
telephones|telephone
telephoning|telephone
tempest's|tempest
tempests|tempest
tender's|tender
tendered|tender
tenderer|tender
tenderest|tender
tendering|tender
tenders|tender
tenth's|tenth
tenthly|tenth
terrace's|terrace
terraced|terrace
terraces|terrace
terracing|terrace
terribleness|terrible
testimonies|testimony
testimony's|testimony
thicket's|thicket
thickets|thicket
thou's|thou
thous|thou
thrill's|thrill
thrilled|thrill
thriller|thrill
thrillers|thrill
thrillingly|thrilling
thrills|thrill
token's|token
tokens|token
ton's|ton
torrent's|torrent
torrents|torrent
tramp's|tramp
tramped|tramp
tramper|tramp
trampers|tramp
tramping|tramp
tramps|tramp
tranquiler|tranquil
tranquilest|tranquil
tranquilly|tranquil
trenched|trench
trenching|trench
trinities|trinity
trinity's|trinity
triumphantly|triumphant
trodden|trod
tropically|tropical
troublesomely|troublesome
trumpet's|trumpet
trumpeted|trumpet
trumpeter|trumpet
trumpeters|trumpet
trumpeting|trumpet
tumult's|tumult
tumults|tumult
tune's|tune
tunes|tune
turf's|turf
turfed|turf
turfing|turf
turfs|turf
twelfth's|twelfth
twinkling's|twinkling
uncommonest|uncommon
undertakes|undertaken
unhappiest|unhappy
uniform's|uniform
uniformed|uniform
uniforming|uniform
uniformly|uniform
union's|union
unions|union
unites|unite
uniting|unite
unity's|unity
unjustly|unjust
unworthiest|unworthy
uplift|uplifted
uplift's|uplifted
uplifting|uplifted
upliftings|uplifted
uplifts|uplifted
uproar's|uproar
uproars|uproar
upwardly|upwards
utterance's|utterance
utterances|utterance
vanquish|vanquished
vanquisher|vanquished
vanquishers|vanquished
vanquishes|vanquished
vanquishing|vanquished
vegetable's|vegetable
velocities|velocity
velocity's|velocity
verged|verge
verges|verge
verging|verge
vex|vexed
vexes|vexed
vexing|vexed
vigilance's|vigilance
vilely|vile
vileness|vile
viler|vile
vilest|vile
virtuously|virtuous
virtuousness|virtuous
voyage's|voyage
voyaged|voyage
voyager|voyage
voyagers|voyage
voyaging|voyage
vulgarer|vulgar
vulgarest|vulgar
vulgarly|vulgar
waistcoat's|waistcoat
waistcoats|waistcoat
waned|wan
wanly|wan
wanness|wan
warmers|warmly
warmest|warmly
warmness|warmly
wedding's|wedding
weddings|wedding
weirder|weird
weirdest|weird
weirdly|weird
weirdness|weird
welfare's|welfare
wheat's|wheat
wheaten|wheat
white's|whites
whiteness|whites
wilt's|wilt
wilted|wilt
wilting|wilt
wilts|wilt
withdrawal's|withdrawal
withdrawals|withdrawal
wive|wives
wived|wives
wiving|wives
wood's|wooded
wooding|wooded
workman|workmen
worldliest|worldly
worldliness|worldly
wreck's|wreck
wrecker|wreck
wreckers|wreck
wrecking|wreck
wrecks|wreck
wretch's|wretch
wrong's|wrongs
wronged|wrongs
wronger|wrongs
wrongest|wrongs
wronging|wrongs
wrongness|wrongs
yea's|yea
yeas|yea
yest|yer
yoked|yoke
yokes|yoke
yoking|yoke
""";

        private static IEnumerable<OrcishLexiconEntry> BuildGutenbergCorpusCandidateEntries(IEnumerable<OrcishLexiconEntry> entries)
        {
            var acceptedEntries = entries.ToList();
            var sourceRoots = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var sourceOrdinal = 0;
            foreach (var english in GutenbergCorpusSourceCandidateData.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var root = $"guthraz-{EncodeTwentyPageOrdinal(sourceOrdinal++)}";
                sourceRoots.Add(english, root);
                var candidate = new OrcishLexiconEntry(english, root, Tags: ["gutenberg", "gutenberg-corpus-candidate-batch", "generated", "review-promoted", "close-form-reviewed", $"family-{english}"]);
                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
            var nearKinOrdinal = 0;
            foreach (var line in GutenbergCorpusNearKinCandidateData.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var fields = line.Split('|', 2, StringSplitOptions.TrimEntries);
                var english = fields[0];
                var sourceEnglish = fields[1];
                var candidate = new OrcishLexiconEntry(english, CreateThirtyPageNearKinForm(sourceRoots[sourceEnglish], english, nearKinOrdinal++), Tags: ["gutenberg", "gutenberg-corpus-near-kin", "near-kin", "derived-by-rule", "review-promoted", "close-form-reviewed", $"family-{sourceEnglish}"]);
                OrcishLexiconReviewUtility.EnsureCanAdd(candidate, acceptedEntries);
                acceptedEntries.Add(candidate);
                yield return candidate;
            }
        }
    }
}
