using PlayerAssistant;
using Microsoft.Playwright;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO.Compression;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Net.Security;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Windows.Forms;
using System.Xml.Linq;

var requestedTestFilter = args.Length > 0 ? string.Join(" ", args).Trim() : string.Empty;

var tests = new (string Name, Action Test)[]
{
    ("orcish translator returns one-to-one english mapping", OrcishTranslatorTests.OrcishTranslatorReturnsOneToOneEnglishMapping),
    ("orcish translator returns several english matches for one orcish word", OrcishTranslatorTests.OrcishTranslatorReturnsSeveralEnglishMatchesForOneOrcishWord),
    ("orcish translator uses part of speech to disambiguate", OrcishTranslatorTests.OrcishTranslatorUsesPartOfSpeechToDisambiguate),
    ("orcish translator filters human terms by register", OrcishTranslatorTests.OrcishTranslatorFiltersHumanTermsByRegister),
    ("orcish translator supports reverse lookup for respectful human term", OrcishTranslatorTests.OrcishTranslatorSupportsReverseLookupForRespectfulHumanTerm),
    ("orcish translator generates plural possessives systematically", OrcishTranslatorTests.OrcishTranslatorGeneratesPluralPossessivesSystematically),
    ("orcish translator supports pale adjective registers", OrcishTranslatorTests.OrcishTranslatorSupportsPaleAdjectiveRegisters),
    ("orcish translator prefers vrak for default skin terms", OrcishTranslatorTests.OrcishTranslatorPrefersVrakForDefaultSkinTerms),
    ("orcish translator reserves drukh for reverent monster hide", OrcishTranslatorTests.OrcishTranslatorReservesDrukhForReverentMonsterHide),
    ("orcish translator supports oglur verb family", OrcishTranslatorTests.OrcishTranslatorSupportsOglurVerbFamily),
    ("orcish translator exposes both i pronoun variants", OrcishTranslatorTests.OrcishTranslatorExposesBothIPronounVariants),
    ("orcish translator random i picker returns valid variant", OrcishTranslatorTests.OrcishTranslatorRandomIPickerReturnsValidVariant),
    ("orcish translator replaces emphasized i in english text", OrcishTranslatorTests.OrcishTranslatorReplacesEmphasizedIInEnglishText),
    ("orcish translator exposes both really adverb variants", OrcishTranslatorTests.OrcishTranslatorExposesBothReallyAdverbVariants),
    ("orcish translator random really picker returns valid variant", OrcishTranslatorTests.OrcishTranslatorRandomReallyPickerReturnsValidVariant),
    ("orcish translator exposes both if variants", OrcishTranslatorTests.OrcishTranslatorExposesBothIfVariants),
    ("orcish translator alternates repeated if terms in sequence", OrcishTranslatorTests.OrcishTranslatorAlternatesRepeatedIfTermsInSequence),
    ("orcish translator exposes both but variants", OrcishTranslatorTests.OrcishTranslatorExposesBothButVariants),
    ("orcish translator supports sarcastic but variants", OrcishTranslatorTests.OrcishTranslatorSupportsSarcasticButVariants),
    ("orcish translator random but picker returns valid variant", OrcishTranslatorTests.OrcishTranslatorRandomButPickerReturnsValidVariant),
    ("orcish translator supports Kirkilston refuge phrase vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsKirkilstonRefugePhraseVocabulary),
    ("orcish translator supports regional map history vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsRegionalMapHistoryVocabulary),
    ("orcish translator supports Xavamros rulership vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsXavamrosRulershipVocabulary),
    ("orcish translator supports Prince Xavin youthful adventure vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsPrinceXavinYouthfulAdventureVocabulary),
    ("orcish translator supports Kirkilston church and Red Laws vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsKirkilstonChurchAndRedLawsVocabulary),
    ("orcish translator supports Kirkliston economy vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsKirklistonEconomyVocabulary),
    ("orcish translator supports Kirkliston watch vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsKirklistonWatchVocabulary),
    ("orcish translator supports Kirkliston daily life vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsKirklistonDailyLifeVocabulary),
    ("orcish translator supports Kirkliston wilderness opportunity vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsKirklistonWildernessOpportunityVocabulary),
    ("orcish translator supports Morgan tavern observation vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsMorganTavernObservationVocabulary),
    ("orcish translator treats dwarf only as Dwarven race", OrcishTranslatorTests.OrcishTranslatorTreatsDwarfOnlyAsDwarvenRace),
    ("orcish translator supports Morgan dining acknowledgement vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsMorganDiningAcknowledgementVocabulary),
    ("orcish translator supports Kelpie road and inn vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsKelpieRoadAndInnVocabulary),
    ("orcish translator supports Kelpie fellowship prayer vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsKelpieFellowshipPrayerVocabulary),
    ("orcish translator supports heraldic stranger equipment vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsHeraldicStrangerEquipmentVocabulary),
    ("orcish translator supports historical wiki fodder vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsHistoricalWikiFodderVocabulary),
    ("orcish translator supports twelve page wiki scrape vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsTwelvePageWikiScrapeVocabulary),
    ("orcish translator supports recovered scroll vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsRecoveredScrollVocabulary),
    ("orcish translator propagates repaired roots through derived families", OrcishTranslatorTests.OrcishTranslatorPropagatesRepairedRootsThroughDerivedFamilies),
    ("orcish translator audits review-promoted derived families", OrcishTranslatorTests.OrcishTranslatorAuditsReviewPromotedDerivedFamilies),
    ("orcish translator shortens mechanically lengthened forms", OrcishTranslatorTests.OrcishTranslatorShortensMechanicallyLengthenedForms),
    ("orcish translator derives predictable morphology by rule", OrcishTranslatorTests.OrcishTranslatorDerivesPredictableMorphologyByRule),
    ("orcish translator culls low value exonym pass throughs", OrcishTranslatorTests.OrcishTranslatorCullsLowValueExonymPassThroughs),
    ("orcish translator enforces lexicon quality invariants", OrcishTranslatorTests.OrcishTranslatorEnforcesLexiconQualityInvariants),
    ("orcish translator reviews proposed lexicon additions", OrcishTranslatorTests.OrcishTranslatorReviewsProposedLexiconAdditions),
    ("orcish translator supports ten page wiki sample vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsTenPageWikiSampleVocabulary),
    ("orcish translator supports near kin morphology families", OrcishTranslatorTests.OrcishTranslatorSupportsNearKinMorphologyFamilies),
    ("orcish translator supports fifteen page sample vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsFifteenPageSampleVocabulary),
    ("orcish translator supports twenty page sample vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsTwentyPageSampleVocabulary),
    ("orcish translator supports thirty page sample vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsThirtyPageSampleVocabulary),
    ("orcish translator supports thirty page followup vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsThirtyPageFollowupVocabulary),
    ("orcish translator supports sixty seven page sample vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsSixtySevenPageSampleVocabulary),
    ("orcish translator supports second thirty page sample vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsSecondThirtyPageSampleVocabulary),
    ("orcish translator supports fifty page sample vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsFiftyPageSampleVocabulary),
    ("orcish translator supports second fifty page sample vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsSecondFiftyPageSampleVocabulary),
    ("orcish translator supports third fifty page sample vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsThirdFiftyPageSampleVocabulary),
    ("orcish translator supports all remaining page sample vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsAllRemainingPageSampleVocabulary),
    ("orcish translator supports Shadowdim blog candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsShadowdimBlogCandidateVocabulary),
    ("orcish translator supports blog follow-up candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsBlogFollowupCandidateVocabulary),
    ("orcish translator supports blog high-yield candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsBlogHighYieldCandidateVocabulary),
    ("orcish translator supports blog mixed high-yield candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsBlogMixedHighYieldCandidateVocabulary),
    ("orcish translator supports blog random hundred candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsBlogRandomHundredCandidateVocabulary),
    ("orcish translator supports blog final sitemap candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsBlogFinalSitemapCandidateVocabulary),
    ("orcish translator supports Gutenberg corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsGutenbergCorpusCandidateVocabulary),
    ("orcish translator supports second Gutenberg corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsGutenbergCorpusSecondCandidateVocabulary),
    ("orcish translator supports third Gutenberg corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsGutenbergCorpusThirdCandidateVocabulary),
    ("orcish translator supports fourth Gutenberg corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsGutenbergCorpusFourthCandidateVocabulary),
    ("orcish translator supports Standard Ebooks corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsStandardEbooksCorpusCandidateVocabulary),
    ("orcish translator supports various ebooks corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsVariousEbooksCorpusCandidateVocabulary),
    ("orcish translator supports second various ebooks corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsVariousEbooksCorpusSecondCandidateVocabulary),
    ("orcish translator supports third various ebooks corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsVariousEbooksCorpusThirdCandidateVocabulary),
    ("orcish translator supports fourth various ebooks corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsVariousEbooksCorpusFourthCandidateVocabulary),
    ("orcish translator supports The Earth It Cares Not vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsEarthItCaresNotVocabulary),
    ("orcish translator supports local Shadowdim vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsLocalShadowdimVocabulary),
    ("orcish translator supports Something Found II vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsSomethingFoundIIVocabulary),
    ("orcish translator supports reviewed megadungeon vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsReviewedMegadungeonVocabulary),
    ("orcish translator supports fifth Gutenberg corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsGutenbergCorpusFifthCandidateVocabulary),
    ("orcish translator supports sixth Gutenberg corpus candidate vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsGutenbergCorpusSixthCandidateVocabulary),
    ("orcish translator excludes approved anachronistic families", OrcishTranslatorTests.OrcishTranslatorExcludesApprovedAnachronisticFamilies),
    ("orcish translator retains approved knowledge vocabulary and noun film sense", OrcishTranslatorTests.OrcishTranslatorRetainsApprovedKnowledgeVocabularyAndNounFilmSense),
    ("orcish translator supports software artifact vocabulary", OrcishTranslatorTests.OrcishTranslatorSupportsSoftwareArtifactVocabulary),
    ("orcish translator translates full text in both directions", OrcishTranslatorTests.OrcishTranslatorTranslatesFullTextInBothDirections),
    ("orcish translator warmup is shared", OrcishTranslatorTests.OrcishTranslatorWarmupIsShared),
    ("orcish translator loads embedded snapshot", OrcishTranslatorTests.OrcishTranslatorLoadsEmbeddedSnapshot),
    ("orcish translator exposes unique english term count", OrcishTranslatorTests.OrcishTranslatorExposesUniqueEnglishTermCount),
    ("to-orcish translates terms before trailing punctuation", OrcishTranslatorTests.ToOrcishTranslatesTermsBeforeTrailingPunctuation),
    ("to-orcish translates dotted abbreviation terms", OrcishTranslatorTests.ToOrcishTranslatesDottedAbbreviationTerms),
    ("to-orcish translates terms inside parentheses", OrcishTranslatorTests.ToOrcishTranslatesTermsInsideParentheses),
    ("to-orcish translates terms inside quotes", OrcishTranslatorTests.ToOrcishTranslatesTermsInsideQuotes),
    ("to-orcish translates words after newlines", OrcishTranslatorTests.ToOrcishTranslatesWordsAfterNewlines),
    ("app configuration validation accepts complete runtime", ConfigurationTests.AppConfigurationValidationAcceptsCompleteRuntime),
    ("settings json accepts current schema version", ConfigurationTests.SettingsJsonAcceptsCurrentSchemaVersion),
    ("settings json rejects future schema version", ConfigurationTests.SettingsJsonRejectsFutureSchemaVersion),
    ("app settings loads hosted encrypted xp tracking url", ConfigurationTests.AppSettingsLoadsHostedEncryptedXpTrackingUrl),
    ("app settings loads hosted encrypted xp tracking url from fixture server", ConfigurationTests.AppSettingsLoadsHostedEncryptedXpTrackingUrlFromFixtureServer),
    ("hosted settings trusted version is encrypted at rest", ConfigurationTests.HostedSettingsTrustedVersionIsEncryptedAtRest),
    ("hosted settings trusted version rejects tampered payload", ConfigurationTests.HostedSettingsTrustedVersionRejectsTamperedPayload),
    ("hosted settings rejects rollback below trusted version floor", ConfigurationTests.HostedSettingsRejectsRollbackBelowTrustedVersionFloor),
    ("hosted settings rejects unexpected signed content identity", ConfigurationTests.HostedSettingsRejectsUnexpectedSignedContentIdentity),
    ("app settings hosted settings failure logs tampered envelope", ConfigurationTests.AppSettingsHostedSettingsFailureLogsTamperedEnvelope),
    ("app settings hosted settings failure logs plaintext payload", ConfigurationTests.AppSettingsHostedSettingsFailureLogsPlaintextPayload),
    ("app settings hosted settings failure logs oversized payload", ConfigurationTests.AppSettingsHostedSettingsFailureLogsOversizedPayload),
    ("app settings hosted settings failure logs unreachable fixture server", ConfigurationTests.AppSettingsHostedSettingsFailureLogsUnreachableFixtureServer),
    ("xp password store loads salted hash sidecar", ConfigurationTests.XpPasswordStoreLoadsSaltedHashSidecar),
    ("xp password store uses unique salts and omits plaintext", ConfigurationTests.XpPasswordStoreUsesUniqueSaltsAndOmitsPlaintext),
    ("xp password store accepts first and full character names", ConfigurationTests.XpPasswordStoreAcceptsFirstAndFullCharacterNames),
    ("xp password store accepts hash sidecar with utf8 bom", ConfigurationTests.XpPasswordStoreAcceptsHashSidecarWithUtf8Bom),
    ("xp password store rejects legacy encrypted sidecar", ConfigurationTests.XpPasswordStoreRejectsLegacyEncryptedSidecar),
    ("xp password store migrates encrypted sidecar", ConfigurationTests.XpPasswordStoreMigratesEncryptedSidecar),
    ("xp password store reports missing sidecar by name", ConfigurationTests.XpPasswordStoreReportsMissingSidecarByName),
    ("app configuration validation reports missing url", ConfigurationTests.AppConfigurationValidationReportsMissingUrl),
    ("app configuration validation rejects disallowed network host", ConfigurationTests.AppConfigurationValidationRejectsDisallowedNetworkHost),
    ("app configuration validation writes repair guidance", ConfigurationTests.AppConfigurationValidationWritesRepairGuidance),
    ("app configuration validation suppresses missing rpol credentials before hosted settings failure", ConfigurationTests.AppConfigurationValidationSuppressesMissingRpolCredentialsBeforeHostedSettingsFailure),
    ("app configuration validation warns about missing rpol credentials after hosted settings failure", ConfigurationTests.AppConfigurationValidationWarnsAboutMissingRpolCredentialsAfterHostedSettingsFailure),
    ("app configuration validation warns about missing sidecars", ConfigurationTests.AppConfigurationValidationWarnsAboutMissingSidecars),
    ("app settings loads rpol credentials from local settings sidecar", ConfigurationTests.AppSettingsLoadsRpolCredentialsFromLocalSettingsSidecar),
    ("app settings uses local rpol credentials when credential store is unavailable", ConfigurationTests.AppSettingsUsesLocalRpolCredentialsWhenCredentialStoreIsUnavailable),
    ("app settings migrate hosted rpol credentials into credential manager", ConfigurationTests.AppSettingsMigrateHostedRpolCredentialsIntoCredentialManager),
    ("app configuration validation accepts valid release manifest", ConfigurationTests.AppConfigurationValidationAcceptsValidReleaseManifest),
    ("app configuration validation rejects missing manifest file", ConfigurationTests.AppConfigurationValidationRejectsMissingManifestFile),
    ("app configuration validation rejects manifest hash mismatch", ConfigurationTests.AppConfigurationValidationRejectsManifestHashMismatch),
    ("health argument surfaces release manifest issue", ConfigurationTests.HealthArgumentSurfacesReleaseManifestIssue),
    ("startup dependency matrix reports bad config and sidecars", ConfigurationTests.StartupDependencyMatrixReportsBadConfigAndSidecars),
    ("startup dependency matrix ignores corrupt optional local settings", ConfigurationTests.StartupDependencyMatrixIgnoresCorruptOptionalLocalSettings),
    ("application version metadata matches hardening release", ConfigurationTests.ApplicationVersionMetadataMatchesHardeningRelease),
    ("application version argument returns version text", ConfigurationTests.ApplicationVersionArgumentReturnsVersionText),
    ("startup manifest status distinguishes skipped and failed", ConfigurationTests.StartupManifestStatusDistinguishesSkippedAndFailed),
    ("startup error log entry includes phase and exception", ConfigurationTests.StartupErrorLogEntryIncludesPhaseAndException),
    ("last crash diagnostic writes redacted exception details", ConfigurationTests.LastCrashDiagnosticWritesRedactedExceptionDetails),
    ("startup health records required phase success", ConfigurationTests.StartupHealthRecordsRequiredPhaseSuccess),
    ("startup health writes schema version", ConfigurationTests.StartupHealthWritesSchemaVersion),
    ("startup health records required phase failure", ConfigurationTests.StartupHealthRecordsRequiredPhaseFailure),
    ("startup health records optional phase failure without throwing", ConfigurationTests.StartupHealthRecordsOptionalPhaseFailureWithoutThrowing),
    ("runtime housekeeping removes stale temp and atomic files", RuntimeNetworkTests.RuntimeHousekeepingRemovesStaleTempAndAtomicFiles),
    ("runtime housekeeping preserves fresh and unrelated tmp files", RuntimeNetworkTests.RuntimeHousekeepingPreservesFreshAndUnrelatedTmpFiles),
    ("runtime housekeeping removes old quarantined json only", RuntimeNetworkTests.RuntimeHousekeepingRemovesOldQuarantinedJsonOnly),
    ("runtime housekeeping removes old backup files only", RuntimeNetworkTests.RuntimeHousekeepingRemovesOldBackupFilesOnly),
    ("runtime housekeeping rotates oversized startup log", RuntimeNetworkTests.RuntimeHousekeepingRotatesOversizedStartupLog),
    ("runtime housekeeping skips locked files", RuntimeNetworkTests.RuntimeHousekeepingSkipsLockedFiles),
    ("ui operation failure reporter logs status and dialog", RuntimeNetworkTests.UiOperationFailureReporterLogsStatusAndDialog),
    ("status bar activity indicator tracks async operations", RuntimeNetworkTests.StatusBarActivityIndicatorTracksAsyncOperations),
    ("background task supervisor suppresses duplicate phases", RuntimeNetworkTests.BackgroundTaskSupervisorSuppressesDuplicatePhases),
    ("background task supervisor logs failures", RuntimeNetworkTests.BackgroundTaskSupervisorLogsFailures),
    ("background task supervisor cancels running tasks on dispose", RuntimeNetworkTests.BackgroundTaskSupervisorCancelsRunningTasksOnDispose),
    ("atomic file promotion preserves existing destination on locked replacement", RuntimeNetworkTests.AtomicFilePromotionPreservesExistingDestinationOnLockedReplacement),
    ("atomic file promotion creates bounded runtime backups", RuntimeNetworkTests.AtomicFilePromotionCreatesBoundedRuntimeBackups),
    ("network request retries transient failures", RuntimeNetworkTests.NetworkRequestRetriesTransientFailures),
    ("outbound network diagnostics records sanitized success endpoint", RuntimeNetworkTests.OutboundNetworkDiagnosticsRecordsSanitizedSuccessEndpoint),
    ("outbound network diagnostics records failure counts", RuntimeNetworkTests.OutboundNetworkDiagnosticsRecordsFailureCounts),
    ("network request rejects disallowed host before send", RuntimeNetworkTests.NetworkRequestRejectsDisallowedHostBeforeSend),
    ("network request does not retry unauthorized", RuntimeNetworkTests.NetworkRequestDoesNotRetryUnauthorized),
    ("network circuit breaker opens after repeated terminal failures", RuntimeNetworkTests.NetworkCircuitBreakerOpensAfterRepeatedTerminalFailures),
    ("network circuit breaker clears after success", RuntimeNetworkTests.NetworkCircuitBreakerClearsAfterSuccess),
    ("startup dependency matrix classifies terminal network failure", RuntimeNetworkTests.StartupDependencyMatrixClassifiesTerminalNetworkFailure),
    ("network request wraps timeout", RuntimeNetworkTests.NetworkRequestWrapsTimeout),
    ("network request preserves caller cancellation", RuntimeNetworkTests.NetworkRequestPreservesCallerCancellation),
    ("network allowlist rejects credentialed and escaped hosts", RuntimeNetworkTests.NetworkAllowlistRejectsCredentialedAndEscapedHosts),
    ("network allowlist accepts obsidian publish content hosts", RuntimeNetworkTests.NetworkAllowlistAcceptsObsidianPublishContentHosts),
    ("network allowlist rejects unexpected hosted settings path", RuntimeNetworkTests.NetworkAllowlistRejectsUnexpectedHostedSettingsPath),
    ("network allowlist rejects unexpected update path", RuntimeNetworkTests.NetworkAllowlistRejectsUnexpectedUpdatePath),
    ("network allowlist generic policy rejects unrelated update host paths", RuntimeNetworkTests.NetworkAllowlistGenericPolicyRejectsUnrelatedUpdateHostPaths),
    ("network response limits define defaults", RuntimeNetworkTests.NetworkResponseLimitsDefineDefaults),
    ("network response limit rejects oversized html header", RuntimeNetworkTests.NetworkResponseLimitRejectsOversizedHtmlHeader),
    ("network response limit rejects oversized markdown stream", RuntimeNetworkTests.NetworkResponseLimitRejectsOversizedMarkdownStream),
    ("network response limit rejects oversized json cache stream", RuntimeNetworkTests.NetworkResponseLimitRejectsOversizedJsonCacheStream),
    ("network response limit rejects oversized image header", RuntimeNetworkTests.NetworkResponseLimitRejectsOversizedImageHeader),
    ("markdown async fetch preserves caller cancellation", RuntimeNetworkTests.MarkdownAsyncFetchPreservesCallerCancellation),
    ("runtime artifact loader quarantines malformed json", RuntimeNetworkTests.RuntimeArtifactLoaderQuarantinesMalformedJson),
    ("runtime artifact loader restores newest valid backup", RuntimeNetworkTests.RuntimeArtifactLoaderRestoresNewestValidBackup),
    ("startup dependency matrix logs locked runtime artifact failures", RuntimeNetworkTests.StartupDependencyMatrixLogsLockedRuntimeArtifactFailures),
    ("login info cache load returns empty for malformed json", RuntimeNetworkTests.LoginInfoCacheLoadReturnsEmptyForMalformedJson),
    ("asset manifest load returns empty for malformed json", RuntimeNetworkTests.AssetManifestLoadReturnsEmptyForMalformedJson),
    ("published asset fallback resolves transclusion without attachment index", RuntimeNetworkTests.PublishedAssetFallbackResolvesTransclusionWithoutAttachmentIndex),
    ("hero token filename resolves listing display name", RuntimeNetworkTests.HeroTokenFileNameResolvesListingDisplayName),
    ("former pc listing parses three-column hero rows", RuntimeNetworkTests.FormerPcListingParsesThreeColumnHeroRows),
    ("active hero markdown cancellation writes no files", RuntimeNetworkTests.ActiveHeroMarkdownCancellationWritesNoFiles),
    ("former hero markdown cancellation writes no inactive files", RuntimeNetworkTests.FormerHeroMarkdownCancellationWritesNoInactiveFiles),
    ("player character refresh cancellation clears in progress flag", RuntimeNetworkTests.PlayerCharacterRefreshCancellationClearsInProgressFlag),
    ("hero image showcase waits for initial player character refresh", RuntimeNetworkTests.HeroImageShowcaseWaitsForInitialPlayerCharacterRefresh),
    ("game forum startup cancellation writes no manifests", RuntimeNetworkTests.GameForumStartupCancellationWritesNoManifests),
    ("keyword index loader quarantines malformed json", RuntimeNetworkTests.KeywordIndexLoaderQuarantinesMalformedJson),
    ("keyword index loader salvages legacy disallowed urls", RuntimeNetworkTests.KeywordIndexLoaderSalvagesLegacyDisallowedUrls),
    ("sitemap validation rejects poisoned url", RuntimeNetworkTests.SitemapValidationRejectsPoisonedUrl),
    ("sitemap keyword dictionary preserves existing output on rejected url", RuntimeNetworkTests.SitemapKeywordDictionaryPreservesExistingOutputOnRejectedUrl),
    ("source integrity records first accepted sitemap", RuntimeNetworkTests.SourceIntegrityRecordsFirstAcceptedSitemap),
    ("source integrity rejects collapsed sitemap and preserves output", RuntimeNetworkTests.SourceIntegrityRejectsCollapsedSitemapAndPreservesOutput),
    ("source integrity rejects collapsed markdown and preserves output", RuntimeNetworkTests.SourceIntegrityRejectsCollapsedMarkdownAndPreservesOutput),
    ("source integrity rejects collapsed keyword index and preserves output", RuntimeNetworkTests.SourceIntegrityRejectsCollapsedKeywordIndexAndPreservesOutput),
    ("keyword index validation rejects poisoned url entries", RuntimeNetworkTests.KeywordIndexValidationRejectsPoisonedUrlEntries),
    ("keyword index validation rejects poisoned match urls", RuntimeNetworkTests.KeywordIndexValidationRejectsPoisonedMatchUrls),
    ("keyword terms release copy generates from keyword index", RuntimeNetworkTests.KeywordTermsReleaseCopyGeneratesFromKeywordIndex),
    ("keyword terms publish copy preserves parent release terms", RuntimeNetworkTests.KeywordTermsPublishCopyPreservesParentReleaseTerms),
    ("rpol auth detects login page fallback", RuntimeNetworkTests.RpolAuthDetectsLoginPageFallback),
    ("rpol auth distinguishes blocked and remote failures", RuntimeNetworkTests.RpolAuthDistinguishesBlockedAndRemoteFailures),
    ("rpol auth prefers installed browsers before playwright chromium", RuntimeNetworkTests.RpolAuthPrefersInstalledBrowsersBeforePlaywrightChromium),
    ("rpol auth enforces browser tls validation", RuntimeNetworkTests.RpolAuthEnforcesBrowserTlsValidation),
    ("rpol auth classifies transport security failures", RuntimeNetworkTests.RpolAuthClassifiesTransportSecurityFailures),
    ("rpol auth cached failure short circuits html fetch", RuntimeNetworkTests.RpolAuthCachedFailureShortCircuitsHtmlFetch),
    ("rpol auth cached failure logs once", RuntimeNetworkTests.RpolAuthCachedFailureLogsOnce),
    ("rpol snapshot signs and verifies canonical payload", RpolSnapshotTests.RpolSnapshotSignsAndVerifiesCanonicalPayload),
    ("rpol snapshot rejects another game", RpolSnapshotTests.RpolSnapshotRejectsAnotherGame),
    ("rpol snapshot sanitizes credentials and login form", RpolSnapshotTests.RpolSnapshotSanitizesCredentialsAndLoginForm),
    ("rpol snapshot accepts sanitized campaign content", RpolSnapshotTests.RpolSnapshotAcceptsSanitizedCampaignContent),
    ("rpol snapshot rejects login-only content", RpolSnapshotTests.RpolSnapshotRejectsLoginOnlyContent),
    ("rpol challenge detection ignores passive cloudflare references", RpolSnapshotTests.RpolChallengeDetectionIgnoresPassiveCloudflareReferences),
    ("rpol verification recognizes authenticated browser title", RpolSnapshotTests.RpolVerificationRecognizesAuthenticatedBrowserTitle),
    ("rpol dice roller navigation uses game page referrer", RpolSnapshotTests.RpolDiceRollerNavigationUsesGamePageReferrer),
    ("snapshot publisher state advances one target and wraps", RpolSnapshotTests.SnapshotPublisherStateAdvancesOneTargetAndWraps),
    ("snapshot discovery approves game links and dice roller", RpolSnapshotTests.SnapshotDiscoveryApprovesGameLinksAndDiceRoller),
    ("snapshot publisher normalizes thread targets to show all", RpolSnapshotTests.SnapshotPublisherNormalizesThreadTargetsToShowAll),
    ("snapshot publisher state injects required dice roller target", RpolSnapshotTests.SnapshotPublisherStateInjectsRequiredDiceRollerTarget),
    ("snapshot publisher state persists its cursor", RpolSnapshotTests.SnapshotPublisherStatePersistsItsCursor),
    ("snapshot publisher state rejects an invalid cursor", RpolSnapshotTests.SnapshotPublisherStateRejectsInvalidCursor),
    ("network allowlist accepts only broker api path", RpolSnapshotTests.NetworkAllowlistAcceptsOnlyBrokerApiPath),
    ("snapshot publisher argument is recognized", RpolSnapshotTests.SnapshotPublisherArgumentIsRecognized),
    ("rpol auth caches blocked and expired session failures", RuntimeNetworkTests.RpolAuthCachesBlockedAndExpiredSessionFailures),
    ("rpol storage state validation accepts current rpol cookies", RuntimeNetworkTests.RpolStorageStateValidationAcceptsCurrentRpolCookies),
    ("rpol storage state validation deletes malformed state", RuntimeNetworkTests.RpolStorageStateValidationDeletesMalformedState),
    ("rpol storage state validation deletes stale state", RuntimeNetworkTests.RpolStorageStateValidationDeletesStaleState),
    ("rpol storage state validation deletes non-rpol state", RuntimeNetworkTests.RpolStorageStateValidationDeletesNonRpolState),
    ("show-all thread url preserves base query and adds show all", RuntimeNetworkTests.ShowAllThreadUrlPreservesBaseQueryAndAddsShowAll),
    ("chapter downloads use show-all thread urls", RuntimeNetworkTests.ChapterDownloadsUseShowAllThreadUrls),
    ("aside downloads use show-all urls and refresh existing files", RuntimeNetworkTests.AsideDownloadsUseShowAllUrlsAndRefreshExistingFiles),
    ("rpol thread export preserves existing output on cancellation", RuntimeNetworkTests.RpolThreadExportPreservesExistingOutputOnCancellation),
    ("rpol thread export commits staged output", RuntimeNetworkTests.RpolThreadExportCommitsStagedOutput),
    ("rpol thread export rejects collapsed source and preserves existing output", RuntimeNetworkTests.RpolThreadExportRejectsCollapsedSourceAndPreservesExistingOutput),
    ("die roll extraction keeps only saved-log lines", RuntimeNetworkTests.DieRollExtractionKeepsOnlySavedLogLines),
    ("die roll extraction handles live rpol paragraph markup", RuntimeNetworkTests.DieRollExtractionHandlesLiveRpolParagraphMarkup),
    ("die roll extraction derives stable ids when rpol omits roll ids", RuntimeNetworkTests.DieRollExtractionDerivesStableIdsWhenRpolOmitsRollIds),
    ("die roll sync appends only unsaved rolls", RuntimeNetworkTests.DieRollSyncAppendsOnlyUnsavedRolls),
    ("regional map downloads when missing", AdventureSearchTests.RegionalMapDownloadsWhenMissing),
    ("regional map downloads when older than one hour", AdventureSearchTests.RegionalMapDownloadsWhenOlderThanOneHour),
    ("regional map skips when newer than one hour", AdventureSearchTests.RegionalMapSkipsWhenNewerThanOneHour),
    ("regional map downloads when newer but transparent", AdventureSearchTests.RegionalMapDownloadsWhenNewerButTransparent),
    ("startup status includes download count and size", AdventureSearchTests.StartupStatusIncludesDownloadCountAndSize),
    ("adventure outline builds from saved IC html", AdventureSearchTests.AdventureOutlineBuildsFromSavedIcHtml),
    ("adventure outline fills every chapter through latest IC chapter", RpolSnapshotTests.AdventureOutlineFillsEveryChapterThroughLatestIcChapter),
    ("adventure outline parses rpol linked author exports", AdventureSearchTests.AdventureOutlineParsesRpolLinkedAuthorExports),
    ("adventure outline summarizes table roles concisely", AdventureSearchTests.AdventureOutlineSummarizesTableRolesConcisely),
    ("adventure outline skips empty bullet marker posts", AdventureSearchTests.AdventureOutlineSkipsEmptyBulletMarkerPosts),
    ("adventure outline rejects weak generated summaries", AdventureSearchTests.AdventureOutlineRejectsWeakGeneratedSummaries),
    ("adventure outline fallback summaries preserve scene specifics", AdventureSearchTests.AdventureOutlineFallbackSummariesPreserveSceneSpecifics),
    ("adventure outline merges new saved IC bullets", AdventureSearchTests.AdventureOutlineMergesNewSavedIcBullets),
    ("adventure outline falls back to Obsidian markdown", AdventureSearchTests.AdventureOutlineFallsBackToObsidianMarkdown),
    ("adventure outline prefers saved IC html over fallback", AdventureSearchTests.AdventureOutlinePrefersSavedIcHtmlOverFallback),
    ("adventure outline ignores failed fallback markdown fetch", AdventureSearchTests.AdventureOutlineIgnoresFailedFallbackMarkdownFetch),
    ("adjusted post tallies aggregate saved IC html", AdventureSearchTests.AdjustedPostTalliesAggregateSavedIcHtml),
    ("keyword search falls back to The-prefixed term", AdventureSearchTests.KeywordSearchFallsBackToThePrefixedTerm),
    ("keyword search keeps quoted phrases together", AdventureSearchTests.KeywordSearchKeepsQuotedPhrasesTogether),
    ("keyword search accepts url source metadata", AdventureSearchTests.KeywordSearchAcceptsUrlSourceMetadata),
    ("keyword search filters rpol hero metadata-only hits", AdventureSearchTests.KeywordSearchFiltersRpolHeroMetadataOnlyHits),
    ("show menu contains xp item", TranslatorUiTests.ShowMenuContainsXpItem),
    ("show menu contains my hero briefing item", TranslatorUiTests.ShowMenuContainsMyHeroBriefingItem),
    ("show menu contains adventure outline item", TranslatorUiTests.ShowMenuContainsAdventureOutlineItem),
    ("show menu contains translator item", TranslatorUiTests.ShowMenuContainsTranslatorItem),
    ("elven translator prefers Sindarin and falls back to Quenya", TranslatorUiTests.ElvenTranslatorPrefersSindarinAndFallsBackToQuenya),
    ("elven translator preserves text and punctuation", TranslatorUiTests.ElvenTranslatorPreservesTextAndPunctuation),
    ("elven translator finalizes every English term", TranslatorUiTests.ElvenTranslatorFinalizesEveryEnglishTerm),
    ("ghukliak translator loads source and complete coverage", TranslatorUiTests.GhukliakTranslatorLoadsSourceAndCompleteCoverage),
    ("ghukliak translator preserves text and punctuation", TranslatorUiTests.GhukliakTranslatorPreservesTextAndPunctuation),
    ("ghukliak complete coverage translates every Orcish English term", TranslatorUiTests.GhukliakCompleteCoverageTranslatesEveryOrcishTerm),
    ("elven morphology derives conservative noun and active verb forms", TranslatorUiTests.ElvenMorphologyDerivesConservativeForms),
    ("elven first iteration loads generated translations", TranslatorUiTests.ElvenFirstIterationLoadsGeneratedTranslations),
    ("elven second iteration loads five thousand generated translations", TranslatorUiTests.ElvenSecondIterationLoadsGeneratedTranslations),
    ("elven complete coverage translates every Orcish English term", TranslatorUiTests.ElvenCompleteCoverageTranslatesEveryOrcishTerm),
    ("elven lexicon validator accepts reviewed rooted additions", TranslatorUiTests.ElvenLexiconValidatorAcceptsReviewedRootedAdditions),
    ("elven lexicon validator rejects unsupported additions", TranslatorUiTests.ElvenLexiconValidatorRejectsUnsupportedAdditions),
    ("elven lexicon validator preserves Sindarin preference", TranslatorUiTests.ElvenLexiconValidatorPreservesSindarinPreference),
    ("translator controller uses injected backend", TranslatorUiTests.TranslatorControllerUsesInjectedBackend),
    ("translator view delegates selection to injected controller", TranslatorUiTests.TranslatorViewDelegatesSelectionToInjectedController),
    ("translator view toggles direction without web links", TranslatorUiTests.TranslatorViewTogglesDirectionWithoutWebLinks),
    ("translator view supports Elven mode", TranslatorUiTests.TranslatorViewSupportsElvenMode),
    ("translator view supports Ghukliak mode", TranslatorUiTests.TranslatorViewSupportsGhukliakMode),
    ("translator view translates while input changes", TranslatorUiTests.TranslatorViewTranslatesWhileInputChanges),
    ("translator view exports english to orcish translation", TranslatorUiTests.TranslatorViewExportsEnglishToOrcishTranslation),
    ("translator view exports english to elvish translation", TranslatorUiTests.TranslatorViewExportsEnglishToElvishTranslation),
    ("adventure outline view displays generated markdown", TranslatorUiTests.AdventureOutlineViewDisplaysGeneratedMarkdown),
    ("about menu contains author and update items", TranslatorUiTests.AboutMenuContainsAuthorAndUpdateItems),
    ("about author text lists developer info", TranslatorUiTests.AboutAuthorTextListsDeveloperInfo),
    ("about version text shows app version", TranslatorUiTests.AboutVersionTextShowsAppVersion),
    ("update check verifies signed p-assist manifest", UpdateDeliveryTests.UpdateCheckVerifiesSignedPAssistManifest),
    ("update check accepts manifest signature made before trailing newline", UpdateDeliveryTests.UpdateCheckAcceptsManifestSignatureMadeBeforeTrailingNewline),
    ("update check chooses newest signed manifest entry", UpdateDeliveryTests.UpdateCheckChoosesNewestSignedManifestEntry),
    ("update check rejects tampered signed manifest", UpdateDeliveryTests.UpdateCheckRejectsTamperedSignedManifest),
    ("update check rejects retired manifest signing key", UpdateDeliveryTests.UpdateCheckRejectsRetiredManifestSigningKey),
    ("update check compares against current app version", UpdateDeliveryTests.UpdateCheckComparesAgainstCurrentAppVersion),
    ("update check reports latest version message", UpdateDeliveryTests.UpdateCheckReportsLatestVersionMessage),
    ("update check fetches signed manifest from allowed update host", UpdateDeliveryTests.UpdateCheckFetchesSignedManifestFromAllowedUpdateHost),
    ("update check remembers highest trusted version observed", UpdateDeliveryTests.UpdateCheckRemembersHighestTrustedVersionObserved),
    ("legacy trusted update state migrates to protected format", UpdateDeliveryTests.LegacyTrustedUpdateStateMigratesToProtectedFormat),
    ("trusted update state is encrypted at rest", UpdateDeliveryTests.TrustedUpdateStateIsEncryptedAtRest),
    ("trusted update state rejects tampered payload", UpdateDeliveryTests.TrustedUpdateStateRejectsTamperedPayload),
    ("update check rejects signed manifest rollback below trusted version floor", UpdateDeliveryTests.UpdateCheckRejectsSignedManifestRollbackBelowTrustedVersionFloor),
    ("update host certificate pinning accepts trusted leaf pin", UpdateDeliveryTests.UpdateHostCertificatePinningAcceptsTrustedLeafPin),
    ("update host certificate pinning accepts trusted intermediate pin", UpdateDeliveryTests.UpdateHostCertificatePinningAcceptsTrustedIntermediatePin),
    ("update host certificate pinning supports rotation window", UpdateDeliveryTests.UpdateHostCertificatePinningSupportsRotationWindow),
    ("update host certificate pinning rejects retired pin", UpdateDeliveryTests.UpdateHostCertificatePinningRejectsRetiredPin),
    ("update host certificate pinning rejects mismatched pin", UpdateDeliveryTests.UpdateHostCertificatePinningRejectsMismatchedPin),
    ("update host certificate validation allows trusted tls with pin mismatch", UpdateDeliveryTests.UpdateHostCertificateValidationAllowsTrustedTlsWithPinMismatch),
    ("certificate validation skips pin extraction for non update hosts", UpdateDeliveryTests.CertificateValidationSkipsPinExtractionForNonUpdateHosts),
    ("verified updater downloads installer to controlled path", UpdateDeliveryTests.VerifiedUpdaterDownloadsInstallerToControlledPath),
    ("verified updater rejects installer sha256 mismatch", UpdateDeliveryTests.VerifiedUpdaterRejectsInstallerSha256Mismatch),
    ("verified updater rejects installer signer mismatch", UpdateDeliveryTests.VerifiedUpdaterRejectsInstallerSignerMismatch),
    ("verified installer launch re-verifies before execution", UpdateDeliveryTests.VerifiedInstallerLaunchReverifiesBeforeExecution),
    ("verified installer launch rejects signer changes after verification", UpdateDeliveryTests.VerifiedInstallerLaunchRejectsSignerChangesAfterVerification),
    ("verified installer launch rejects elevation changes after verification", UpdateDeliveryTests.VerifiedInstallerLaunchRejectsElevationChangesAfterVerification),
    ("search enter triggers click when enabled", PartyHeroTests.SearchEnterTriggersClickWhenEnabled),
    ("keyword search uppercases encrypted index results without changing launch URL", PartyHeroTests.KeywordSearchUppercasesEncryptedIndexResultsWithoutChangingLaunchUrl),
    ("keyword search uppercases online Obsidian fallback results", PartyHeroTests.KeywordSearchUppercasesOnlineObsidianFallbackResults),
    ("keyword search backfills online hits into keyword index", PartyHeroTests.KeywordSearchBackfillsOnlineHitsIntoKeywordIndex),
    ("keyword search offers online fallback on local miss", PartyHeroTests.KeywordSearchOffersOnlineFallbackOnLocalMiss),
    ("keyword search cancels previous online fallback", PartyHeroTests.KeywordSearchCancelsPreviousOnlineFallback),
    ("keyword search rpol scope excludes obsidian-only whiteheart", PartyHeroTests.KeywordSearchRpolScopeExcludesObsidianOnlyWhiteheart),
    ("keyword search rpol scope excludes obsidian-only whiteheart stiffwhiskers", PartyHeroTests.KeywordSearchRpolScopeExcludesObsidianOnlyWhiteheartStiffwhiskers),
    ("keyword search expands hero first and full names", PartyHeroTests.KeywordSearchExpandsHeroFirstAndFullNames),
    ("my hero briefing builds selected hero summary boundary", PartyHeroTests.MyHeroBriefingBuildsSelectedHeroSummaryBoundary),
    ("my hero briefing prefers authenticated hero identity", PartyHeroTests.MyHeroBriefingPrefersAuthenticatedHeroIdentity),
    ("my hero briefing requires explicit dungeon master hero selection", PartyHeroTests.MyHeroBriefingRequiresExplicitDungeonMasterHeroSelection),
    ("my hero briefing leaves ambiguous first name unresolved", PartyHeroTests.MyHeroBriefingLeavesAmbiguousFirstNameUnresolved),
    ("my hero briefing hides xp for unauthenticated selected hero card", PartyHeroTests.MyHeroBriefingHidesXpForUnauthenticatedSelectedHeroCard),
    ("my hero briefing builds recent hero activity", PartyHeroTests.MyHeroBriefingBuildsRecentHeroActivity),
    ("my hero briefing builds likely open response items", PartyHeroTests.MyHeroBriefingBuildsLikelyOpenResponseItems),
    ("my hero briefing surfaces relevant unlocked notes", PartyHeroTests.MyHeroBriefingSurfacesRelevantUnlockedNotes),
    ("my hero briefing requests hero selection when no hero selected", PartyHeroTests.MyHeroBriefingRequestsHeroSelectionWhenNoHeroSelected),
    ("my hero briefing display text includes focused sections", PartyHeroTests.MyHeroBriefingDisplayTextIncludesFocusedSections),
    ("my hero briefing styles likely response key", PartyHeroTests.MyHeroBriefingStylesLikelyResponseKey),
    ("my hero briefing loads cached thread posts from runtime artifacts", PartyHeroTests.MyHeroBriefingLoadsCachedThreadPostsFromRuntimeArtifacts),
    ("my hero briefing loads flat cached thread files from runtime artifacts", PartyHeroTests.MyHeroBriefingLoadsFlatCachedThreadFilesFromRuntimeArtifacts),
    ("my hero briefing encrypted index loader tolerates malformed json", PartyHeroTests.MyHeroBriefingEncryptedIndexLoaderToleratesMalformedJson),
    ("party hero sheet parser reads summary and hides xp lines", PartyHeroTests.PartyHeroSheetParserReadsSummaryAndHidesXpLines),
    ("party hero listing summary overrides stale cached sheet", PartyHeroTests.PartyHeroListingSummaryOverridesStaleCachedSheet),
    ("party hero xp visibility follows authenticated character", PartyHeroTests.PartyHeroXpVisibilityFollowsAuthenticatedCharacter),
    ("tagged note cipher decrypts for matching level tag", PartyHeroTests.TaggedNoteCipherDecryptsForMatchingLevelTag),
    ("tagged note cipher decrypts for matching character tag", PartyHeroTests.TaggedNoteCipherDecryptsForMatchingCharacterTag),
    ("tagged note cipher rejects unmet class tag", PartyHeroTests.TaggedNoteCipherRejectsUnmetClassTag),
    ("tagged note cipher accepts either-or ability tag", PartyHeroTests.TaggedNoteCipherAcceptsEitherOrAbilityTag),
    ("tagged note cipher accepts bare class alternative", PartyHeroTests.TaggedNoteCipherAcceptsBareClassAlternative),
    ("tagged note cipher accepts class level shorthand and faction tag", PartyHeroTests.TaggedNoteCipherAcceptsClassLevelShorthandAndFactionTag),
    ("tagged note cipher accepts grouped and expression tag", PartyHeroTests.TaggedNoteCipherAcceptsGroupedAndExpressionTag),
    ("tagged note cipher reports mismatched decrypt tags", PartyHeroTests.TaggedNoteCipherReportsMismatchedDecryptTags),
    ("tagged note cipher reports encrypted markdown block counts", PartyHeroTests.TaggedNoteCipherReportsEncryptedMarkdownBlockCounts),
    ("tagged note cipher indexes encrypted markdown frontmatter tags", PartyHeroTests.TaggedNoteCipherIndexesEncryptedMarkdownFrontmatterTags),
    ("tagged note cipher authenticates visible tags", PartyHeroTests.TaggedNoteCipherAuthenticatesVisibleTags),
    ("xp display recognizes dungeon master access", PartyHeroTests.XpDisplayRecognizesDungeonMasterAccess),
    ("xp display finds totals by first and full character names", PartyHeroTests.XpDisplayFindsTotalsByFirstAndFullCharacterNames),
    ("xp display stores multiple totals for dungeon master", PartyHeroTests.XpDisplayStoresMultipleTotalsForDungeonMaster),
    ("xp tracking parser reads latest table totals", PartyHeroTests.XpTrackingParserReadsLatestTableTotals),
    ("xp tracking parser rejects missing latest table", PartyHeroTests.XpTrackingParserRejectsMissingLatestTable),
    ("xp tracking failure message hides url and directs players to dm", PartyHeroTests.XpTrackingFailureMessageHidesUrlAndDirectsPlayersToDm),
    ("xp tracking missing pc message directs players to dm", PartyHeroTests.XpTrackingMissingPcMessageDirectsPlayersToDm),
    ("illusionist progression data exposes XP thresholds", PartyHeroTests.IllusionistProgressionDataExposesXpThresholds),
    ("show menu contains party item", TranslatorUiTests.ShowMenuContainsPartyItem),
    ("show menu contains former pcs item", TranslatorUiTests.ShowMenuContainsFormerPcsItem),
    ("former pcs view displays token name and class", TranslatorUiTests.FormerPcsViewDisplaysTokenNameAndClass),
    ("external url launch policy accepts https and rejects http", PartyHeroTests.ExternalUrlLaunchPolicyAcceptsHttpsAndRejectsHttp),
    ("external url launch policy rejects unsafe inputs", PartyHeroTests.ExternalUrlLaunchPolicyRejectsUnsafeInputs),
    ("hero image paths follow listing markdown table", PartyHeroTests.HeroImagePathsFollowListingMarkdownTable),
    ("hero asset paths reject escaped targets", PartyHeroTests.HeroAssetPathsRejectEscapedTargets),
    ("legacy local settings migrate to scoped encryption", SettingsReleaseTests.LegacyLocalSettingsMigrateToPortableEncryption),
    ("v1 local settings migrate to authenticated encryption", SettingsReleaseTests.V1LocalSettingsMigrateToAuthenticatedEncryption),
    ("v2 local settings migrate to scoped encryption", SettingsReleaseTests.V2LocalSettingsMigrateToScopedEncryption),
    ("local settings are encrypted on load", SettingsReleaseTests.LocalSettingsAreEncryptedOnLoad),
    ("portable encrypted settings byte loader clears source buffer", SettingsReleaseTests.PortableEncryptedSettingsByteLoaderClearsSourceBuffer),
    ("credential manager utf8 helpers clear transient buffers", SettingsReleaseTests.CredentialManagerUtf8HelpersClearTransientBuffers),
    ("local settings encrypt command writes portable envelope", SettingsReleaseTests.LocalSettingsEncryptCommandWritesPortableEnvelope),
    ("local settings decrypt command writes plaintext json", SettingsReleaseTests.LocalSettingsDecryptCommandWritesPlaintextJson),
    ("local settings rejects future schema version", SettingsReleaseTests.LocalSettingsRejectsFutureSchemaVersion),
    ("scoped local settings reject copied install path", SettingsReleaseTests.ScopedLocalSettingsRejectCopiedInstallPath),
    ("authenticated local settings reject tampered payload", SettingsReleaseTests.AuthenticatedLocalSettingsRejectTamperedPayload),
    ("local settings restores newest valid backup", SettingsReleaseTests.LocalSettingsRestoresNewestValidBackup),
    ("runtime path utility rejects escaped paths", SettingsReleaseTests.RuntimePathUtilityRejectsEscapedPaths),
    ("health argument returns startup health summary", SettingsReleaseTests.HealthArgumentReturnsStartupHealthSummary),
    ("publish verification accepts current output", SettingsReleaseTests.PublishVerificationAcceptsCurrentOutput),
    ("publish verification rejects stale startup log", SettingsReleaseTests.PublishVerificationRejectsStaleStartupLog),
    ("publish verification rejects startup health artifact", SettingsReleaseTests.PublishVerificationRejectsStartupHealthArtifact),
    ("publish verification rejects outbound network diagnostics artifact", SettingsReleaseTests.PublishVerificationRejectsOutboundNetworkDiagnosticsArtifact),
    ("publish verification rejects last crash artifact", SettingsReleaseTests.PublishVerificationRejectsLastCrashArtifact),
    ("publish verification rejects malformed settings json", SettingsReleaseTests.PublishVerificationRejectsMalformedSettingsJson),
    ("publish verification rejects future settings schema", SettingsReleaseTests.PublishVerificationRejectsFutureSettingsSchema),
    ("publish verification accepts encrypted rpol local settings sidecar", SettingsReleaseTests.PublishVerificationAcceptsEncryptedRpolLocalSettingsSidecar),
    ("publish verification rejects plaintext rpol local settings sidecar", SettingsReleaseTests.PublishVerificationRejectsPlaintextRpolLocalSettingsSidecar),
    ("publish verification accepts missing hosted local settings url", SettingsReleaseTests.PublishVerificationAcceptsMissingHostedLocalSettingsUrl),
    ("publish verification rejects missing xp password sidecar", SettingsReleaseTests.PublishVerificationRejectsMissingXpPasswordSidecar),
    ("publish verification rejects plaintext xp password sidecar", SettingsReleaseTests.PublishVerificationRejectsPlaintextXpPasswordSidecar),
    ("publish verification rejects malformed keyword index", SettingsReleaseTests.PublishVerificationRejectsMalformedKeywordIndex),
    ("publish verification rejects malformed sitemap", SettingsReleaseTests.PublishVerificationRejectsMalformedSitemap),
    ("publish verification rejects incomplete playwright runtime", SettingsReleaseTests.PublishVerificationRejectsIncompletePlaywrightRuntime),
    ("publish verification rejects mismatched executable version", SettingsReleaseTests.PublishVerificationRejectsMismatchedExecutableVersion),
    ("publish verification rejects stale release manifest", SettingsReleaseTests.PublishVerificationRejectsStaleReleaseManifest),
    ("publish verification rejects malformed runtime inventory", SettingsReleaseTests.PublishVerificationRejectsMalformedRuntimeInventory),
    ("publish verification rejects malformed release provenance", SettingsReleaseTests.PublishVerificationRejectsMalformedReleaseProvenance),
    ("publish verification rejects unsigned executable when signing required", SettingsReleaseTests.PublishVerificationRejectsUnsignedExecutableWhenSigningRequired),
    ("installer scripts target program files install path", SettingsReleaseTests.InstallerScriptsTargetProgramFilesInstallPath),
    ("installer package verification accepts current package", SettingsReleaseTests.InstallerPackageVerificationAcceptsCurrentPackage),
    ("installer package verification rejects unsigned payload when signing required", SettingsReleaseTests.InstallerPackageVerificationRejectsUnsignedPayloadWhenSigningRequired),
    ("release update artifact verification accepts generated signed manifest", SettingsReleaseTests.ReleaseUpdateArtifactVerificationAcceptsGeneratedSignedManifest),
    ("release update artifact verification rejects manifest hash mismatch", SettingsReleaseTests.ReleaseUpdateArtifactVerificationRejectsManifestHashMismatch),
    ("hardening workflow builds and uploads signed release update artifacts", SettingsReleaseTests.HardeningWorkflowBuildsAndUploadsSignedReleaseUpdateArtifacts),
    ("published health verification accepts current output", SettingsReleaseTests.PublishedHealthVerificationAcceptsCurrentOutput),
    ("secret scan accepts current repository", SettingsReleaseTests.SecretScanAcceptsCurrentRepository),
    ("secret scan rejects tracked env secret", SettingsReleaseTests.SecretScanRejectsTrackedEnvSecret),
    ("release publish parity accepts current output", SettingsReleaseTests.ReleasePublishParityAcceptsCurrentOutput),
    ("release publish parity rejects mismatched sidecar", SettingsReleaseTests.ReleasePublishParityRejectsMismatchedSidecar),
    ("diagnostic bundle redacts sensitive values", SettingsReleaseTests.DiagnosticBundleRedactsSensitiveValues),
    ("diagnostic bundle verify only rejects forbidden auth state", SettingsReleaseTests.DiagnosticBundleVerifyOnlyRejectsForbiddenAuthState),
    ("diagnostic retention cleanup removes old diagnostics and preserves unrelated scratch files", TestSupport.DiagnosticRetentionCleanupRemovesOldDiagnosticsAndPreservesUnrelatedScratchFiles),
};

if (!string.IsNullOrWhiteSpace(requestedTestFilter))
{
    tests = tests
        .Where(test => test.Name.Contains(requestedTestFilter, StringComparison.OrdinalIgnoreCase))
        .ToArray();
}

var failures = new List<string>();

foreach (var (name, test) in tests)
{
    try
    {
        using var credentialStoreScope = RuntimeSecretStoreUtility.UseBackendForTests(new InMemoryWindowsCredentialStoreBackend());
        test();
        Console.WriteLine($"PASS {name}");
    }
    catch (Exception ex)
    {
        var rootException = ex is TargetInvocationException tie && tie.InnerException is not null
            ? tie.InnerException
            : ex;

        failures.Add($"{name}: {rootException}");
        Console.WriteLine($"FAIL {name}: {rootException}");
    }
}

if (failures.Count > 0)
{
    Console.WriteLine();
    Console.WriteLine("Failures:");
    foreach (var failure in failures)
    {
        Console.WriteLine(failure);
    }

    return 1;
}

return 0;
