using PlayerAssistant;

namespace PlayerAssistant.Tests;

internal static class TestCatalog
{
    internal static (string Name, Action Test)[] Create() =>
        new (string Name, Action Test)[]
{
    ("orcish translator returns one-to-one english mapping", TestCases.OrcishTranslatorReturnsOneToOneEnglishMapping),
    ("repository root discovery handles CI output layout", TestCases.RepositoryRootDiscoveryHandlesCiOutputLayout),
    ("login throttling rejects malformed source at login boundary", TestCases.LoginThrottlingRejectsMalformedSourceAtLoginBoundary),
    ("orcish translator returns several english matches for one orcish word", TestCases.OrcishTranslatorReturnsSeveralEnglishMatchesForOneOrcishWord),
    ("orcish translator uses part of speech to disambiguate", TestCases.OrcishTranslatorUsesPartOfSpeechToDisambiguate),
    ("orcish translator filters human terms by register", TestCases.OrcishTranslatorFiltersHumanTermsByRegister),
    ("orcish translator supports reverse lookup for respectful human term", TestCases.OrcishTranslatorSupportsReverseLookupForRespectfulHumanTerm),
    ("orcish translator generates plural possessives systematically", TestCases.OrcishTranslatorGeneratesPluralPossessivesSystematically),
    ("orcish translator supports pale adjective registers", TestCases.OrcishTranslatorSupportsPaleAdjectiveRegisters),
    ("orcish translator prefers vrak for default skin terms", TestCases.OrcishTranslatorPrefersVrakForDefaultSkinTerms),
    ("orcish translator reserves drukh for reverent monster hide", TestCases.OrcishTranslatorReservesDrukhForReverentMonsterHide),
    ("orcish translator supports oglur verb family", TestCases.OrcishTranslatorSupportsOglurVerbFamily),
    ("orcish translator exposes both i pronoun variants", TestCases.OrcishTranslatorExposesBothIPronounVariants),
    ("orcish translator random i picker returns valid variant", TestCases.OrcishTranslatorRandomIPickerReturnsValidVariant),
    ("orcish translator replaces emphasized i in english text", TestCases.OrcishTranslatorReplacesEmphasizedIInEnglishText),
    ("orcish translator exposes both really adverb variants", TestCases.OrcishTranslatorExposesBothReallyAdverbVariants),
    ("orcish translator random really picker returns valid variant", TestCases.OrcishTranslatorRandomReallyPickerReturnsValidVariant),
    ("orcish translator exposes both if variants", TestCases.OrcishTranslatorExposesBothIfVariants),
    ("orcish translator alternates repeated if terms in sequence", TestCases.OrcishTranslatorAlternatesRepeatedIfTermsInSequence),
    ("orcish translator exposes both but variants", TestCases.OrcishTranslatorExposesBothButVariants),
    ("orcish translator supports sarcastic but variants", TestCases.OrcishTranslatorSupportsSarcasticButVariants),
    ("orcish translator random but picker returns valid variant", TestCases.OrcishTranslatorRandomButPickerReturnsValidVariant),
    ("orcish translator supports Kirkilston refuge phrase vocabulary", TestCases.OrcishTranslatorSupportsKirkilstonRefugePhraseVocabulary),
    ("orcish translator supports regional map history vocabulary", TestCases.OrcishTranslatorSupportsRegionalMapHistoryVocabulary),
    ("orcish translator supports Xavamros rulership vocabulary", TestCases.OrcishTranslatorSupportsXavamrosRulershipVocabulary),
    ("orcish translator supports Prince Xavin youthful adventure vocabulary", TestCases.OrcishTranslatorSupportsPrinceXavinYouthfulAdventureVocabulary),
    ("orcish translator supports Kirkilston church and Red Laws vocabulary", TestCases.OrcishTranslatorSupportsKirkilstonChurchAndRedLawsVocabulary),
    ("orcish translator supports Kirkliston economy vocabulary", TestCases.OrcishTranslatorSupportsKirklistonEconomyVocabulary),
    ("orcish translator supports Kirkliston watch vocabulary", TestCases.OrcishTranslatorSupportsKirklistonWatchVocabulary),
    ("orcish translator supports Kirkliston daily life vocabulary", TestCases.OrcishTranslatorSupportsKirklistonDailyLifeVocabulary),
    ("orcish translator supports Kirkliston wilderness opportunity vocabulary", TestCases.OrcishTranslatorSupportsKirklistonWildernessOpportunityVocabulary),
    ("orcish translator supports Morgan tavern observation vocabulary", TestCases.OrcishTranslatorSupportsMorganTavernObservationVocabulary),
    ("orcish translator treats dwarf only as Dwarven race", TestCases.OrcishTranslatorTreatsDwarfOnlyAsDwarvenRace),
    ("orcish translator supports Morgan dining acknowledgement vocabulary", TestCases.OrcishTranslatorSupportsMorganDiningAcknowledgementVocabulary),
    ("orcish translator supports Kelpie road and inn vocabulary", TestCases.OrcishTranslatorSupportsKelpieRoadAndInnVocabulary),
    ("orcish translator supports Kelpie fellowship prayer vocabulary", TestCases.OrcishTranslatorSupportsKelpieFellowshipPrayerVocabulary),
    ("orcish translator supports heraldic stranger equipment vocabulary", TestCases.OrcishTranslatorSupportsHeraldicStrangerEquipmentVocabulary),
    ("orcish translator supports historical wiki fodder vocabulary", TestCases.OrcishTranslatorSupportsHistoricalWikiFodderVocabulary),
    ("orcish translator supports twelve page wiki scrape vocabulary", TestCases.OrcishTranslatorSupportsTwelvePageWikiScrapeVocabulary),
    ("orcish translator supports recovered scroll vocabulary", TestCases.OrcishTranslatorSupportsRecoveredScrollVocabulary),
    ("orcish translator propagates repaired roots through derived families", TestCases.OrcishTranslatorPropagatesRepairedRootsThroughDerivedFamilies),
    ("orcish translator audits review-promoted derived families", TestCases.OrcishTranslatorAuditsReviewPromotedDerivedFamilies),
    ("orcish translator shortens mechanically lengthened forms", TestCases.OrcishTranslatorShortensMechanicallyLengthenedForms),
    ("orcish translator derives predictable morphology by rule", TestCases.OrcishTranslatorDerivesPredictableMorphologyByRule),
    ("orcish translator culls low value exonym pass throughs", TestCases.OrcishTranslatorCullsLowValueExonymPassThroughs),
    ("orcish translator enforces lexicon quality invariants", TestCases.OrcishTranslatorEnforcesLexiconQualityInvariants),
    ("orcish translator reviews proposed lexicon additions", TestCases.OrcishTranslatorReviewsProposedLexiconAdditions),
    ("orcish translator supports ten page wiki sample vocabulary", TestCases.OrcishTranslatorSupportsTenPageWikiSampleVocabulary),
    ("orcish translator supports near kin morphology families", TestCases.OrcishTranslatorSupportsNearKinMorphologyFamilies),
    ("orcish translator supports fifteen page sample vocabulary", TestCases.OrcishTranslatorSupportsFifteenPageSampleVocabulary),
    ("orcish translator supports twenty page sample vocabulary", TestCases.OrcishTranslatorSupportsTwentyPageSampleVocabulary),
    ("orcish translator supports thirty page sample vocabulary", TestCases.OrcishTranslatorSupportsThirtyPageSampleVocabulary),
    ("orcish translator supports thirty page followup vocabulary", TestCases.OrcishTranslatorSupportsThirtyPageFollowupVocabulary),
    ("orcish translator supports sixty seven page sample vocabulary", TestCases.OrcishTranslatorSupportsSixtySevenPageSampleVocabulary),
    ("orcish translator supports second thirty page sample vocabulary", TestCases.OrcishTranslatorSupportsSecondThirtyPageSampleVocabulary),
    ("orcish translator supports fifty page sample vocabulary", TestCases.OrcishTranslatorSupportsFiftyPageSampleVocabulary),
    ("orcish translator supports second fifty page sample vocabulary", TestCases.OrcishTranslatorSupportsSecondFiftyPageSampleVocabulary),
    ("orcish translator supports third fifty page sample vocabulary", TestCases.OrcishTranslatorSupportsThirdFiftyPageSampleVocabulary),
    ("orcish translator supports all remaining page sample vocabulary", TestCases.OrcishTranslatorSupportsAllRemainingPageSampleVocabulary),
    ("orcish translator supports Shadowdim blog candidate vocabulary", TestCases.OrcishTranslatorSupportsShadowdimBlogCandidateVocabulary),
    ("orcish translator supports blog follow-up candidate vocabulary", TestCases.OrcishTranslatorSupportsBlogFollowupCandidateVocabulary),
    ("orcish translator supports blog high-yield candidate vocabulary", TestCases.OrcishTranslatorSupportsBlogHighYieldCandidateVocabulary),
    ("orcish translator supports blog mixed high-yield candidate vocabulary", TestCases.OrcishTranslatorSupportsBlogMixedHighYieldCandidateVocabulary),
    ("orcish translator supports blog random hundred candidate vocabulary", TestCases.OrcishTranslatorSupportsBlogRandomHundredCandidateVocabulary),
    ("orcish translator supports blog final sitemap candidate vocabulary", TestCases.OrcishTranslatorSupportsBlogFinalSitemapCandidateVocabulary),
    ("orcish translator supports Gutenberg corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsGutenbergCorpusCandidateVocabulary),
    ("orcish translator supports second Gutenberg corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsGutenbergCorpusSecondCandidateVocabulary),
    ("orcish translator supports third Gutenberg corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsGutenbergCorpusThirdCandidateVocabulary),
    ("orcish translator supports fourth Gutenberg corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsGutenbergCorpusFourthCandidateVocabulary),
    ("orcish translator supports Standard Ebooks corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsStandardEbooksCorpusCandidateVocabulary),
    ("orcish translator supports various ebooks corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsVariousEbooksCorpusCandidateVocabulary),
    ("orcish translator supports second various ebooks corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsVariousEbooksCorpusSecondCandidateVocabulary),
    ("orcish translator supports third various ebooks corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsVariousEbooksCorpusThirdCandidateVocabulary),
    ("orcish translator supports fourth various ebooks corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsVariousEbooksCorpusFourthCandidateVocabulary),
    ("orcish translator supports The Earth It Cares Not vocabulary", TestCases.OrcishTranslatorSupportsEarthItCaresNotVocabulary),
    ("orcish translator supports local Shadowdim vocabulary", TestCases.OrcishTranslatorSupportsLocalShadowdimVocabulary),
    ("orcish translator supports Something Found II vocabulary", TestCases.OrcishTranslatorSupportsSomethingFoundIIVocabulary),
    ("orcish translator supports reviewed megadungeon vocabulary", TestCases.OrcishTranslatorSupportsReviewedMegadungeonVocabulary),
    ("orcish translator supports fifth Gutenberg corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsGutenbergCorpusFifthCandidateVocabulary),
    ("orcish translator supports sixth Gutenberg corpus candidate vocabulary", TestCases.OrcishTranslatorSupportsGutenbergCorpusSixthCandidateVocabulary),
    ("orcish translator excludes approved anachronistic families", TestCases.OrcishTranslatorExcludesApprovedAnachronisticFamilies),
    ("orcish translator retains approved knowledge vocabulary and noun film sense", TestCases.OrcishTranslatorRetainsApprovedKnowledgeVocabularyAndNounFilmSense),
    ("orcish translator supports software artifact vocabulary", TestCases.OrcishTranslatorSupportsSoftwareArtifactVocabulary),
    ("orcish translator translates full text in both directions", TestCases.OrcishTranslatorTranslatesFullTextInBothDirections),
    ("orcish translator warmup is shared", TestCases.OrcishTranslatorWarmupIsShared),
    ("orcish translator loads embedded snapshot", TestCases.OrcishTranslatorLoadsEmbeddedSnapshot),
    ("orcish translator exposes unique english term count", TestCases.OrcishTranslatorExposesUniqueEnglishTermCount),
    ("to-orcish translates terms before trailing punctuation", TestCases.ToOrcishTranslatesTermsBeforeTrailingPunctuation),
    ("to-orcish translates dotted abbreviation terms", TestCases.ToOrcishTranslatesDottedAbbreviationTerms),
    ("to-orcish translates terms inside parentheses", TestCases.ToOrcishTranslatesTermsInsideParentheses),
    ("to-orcish translates terms inside quotes", TestCases.ToOrcishTranslatesTermsInsideQuotes),
    ("to-orcish translates words after newlines", TestCases.ToOrcishTranslatesWordsAfterNewlines),
    ("app configuration validation accepts complete runtime", TestCases.AppConfigurationValidationAcceptsCompleteRuntime),
    ("keep alive policy is truthful and observable", TestCases.KeepAlivePolicyIsTruthfulAndObservable),
    ("settings json accepts current schema version", TestCases.SettingsJsonAcceptsCurrentSchemaVersion),
    ("settings json rejects future schema version", TestCases.SettingsJsonRejectsFutureSchemaVersion),
    ("app settings loads hosted encrypted xp tracking url", TestCases.AppSettingsLoadsHostedEncryptedXpTrackingUrl),
    ("app settings loads hosted encrypted xp tracking url from fixture server", TestCases.AppSettingsLoadsHostedEncryptedXpTrackingUrlFromFixtureServer),
    ("hosted settings trusted version is encrypted at rest", TestCases.HostedSettingsTrustedVersionIsEncryptedAtRest),
    ("hosted settings trusted version rejects tampered payload", TestCases.HostedSettingsTrustedVersionRejectsTamperedPayload),
    ("hosted settings rejects rollback below trusted version floor", TestCases.HostedSettingsRejectsRollbackBelowTrustedVersionFloor),
    ("hosted settings rejects unexpected signed content identity", TestCases.HostedSettingsRejectsUnexpectedSignedContentIdentity),
    ("app settings hosted settings failure logs tampered envelope", TestCases.AppSettingsHostedSettingsFailureLogsTamperedEnvelope),
    ("app settings hosted settings failure logs plaintext payload", TestCases.AppSettingsHostedSettingsFailureLogsPlaintextPayload),
    ("app settings hosted settings failure logs oversized payload", TestCases.AppSettingsHostedSettingsFailureLogsOversizedPayload),
    ("app settings hosted settings failure logs unreachable fixture server", TestCases.AppSettingsHostedSettingsFailureLogsUnreachableFixtureServer),
    ("xp password store loads salted hash sidecar", TestCases.XpPasswordStoreLoadsSaltedHashSidecar),
    ("xp identity rejects same first name cross-account password", TestCases.XpIdentityRejectsSameFirstNameCrossAccountPassword),
    ("xp identity accepts explicit unique alias", TestCases.XpIdentityAcceptsExplicitUniqueAlias),
    ("xp password store uses unique salts and omits plaintext", TestCases.XpPasswordStoreUsesUniqueSaltsAndOmitsPlaintext),
    ("xp password store rejects non-canonical character names", TestCases.XpPasswordStoreRejectsNonCanonicalCharacterNames),
    ("xp password store accepts hash sidecar with utf8 bom", TestCases.XpPasswordStoreAcceptsHashSidecarWithUtf8Bom),
    ("xp password store rejects legacy encrypted sidecar", TestCases.XpPasswordStoreRejectsLegacyEncryptedSidecar),
    ("xp password store migrates encrypted sidecar", TestCases.XpPasswordStoreMigratesEncryptedSidecar),
    ("xp password store reports missing sidecar by name", TestCases.XpPasswordStoreReportsMissingSidecarByName),
    ("identity fixtures are distinct and synthetic", TestCases.IdentityFixturesAreDistinctAndSynthetic),
    ("successful authentication returns canonical identity", TestCases.SuccessfulAuthenticationReturnsCanonicalIdentity),
    ("authenticated identity factory derives role and scope", TestCases.AuthenticatedIdentityFactoryDerivesRoleAndScope),
    ("authenticated identity factory rejects impossible canonical role", TestCases.AuthenticatedIdentityFactoryRejectsImpossibleCanonicalRole),
    ("protected boundaries reject forged identity state", TestCases.ProtectedBoundariesRejectForgedIdentityState),
    ("account switching returns the new canonical identity", TestCases.AccountSwitchingReturnsNewCanonicalIdentity),
    ("dungeon master scope uses stable canonical ID", TestCases.DungeonMasterScopeUsesStableCanonicalId),
    ("opaque Dungeon Master canonical ID preserves scope", TestCases.OpaqueDungeonMasterCanonicalIdPreservesScope),
    ("identity registry loads canonical aliases", TestCases.IdentityRegistryLoadsCanonicalAliases),
    ("legacy name lookup reproduces cross-identity leak", TestCases.LegacyNameLookupReproducesCrossIdentityLeak),
    ("cross-account password access is denied", TestCases.CrossAccountPasswordAccessIsDenied),
    ("ambiguous first-name aliases are denied", TestCases.AmbiguousFirstNameAliasesAreDenied),
    ("unknown canonical IDs are denied", TestCases.UnknownCanonicalIdsAreDenied),
    ("mismatched passwords are denied", TestCases.MismatchedPasswordsAreDenied),
    ("colliding hero display names resolve only by canonical ID", TestCases.CollidingHeroDisplayNamesResolveOnlyByCanonicalId),
    ("canonical IDs select matching XP and briefing data", TestCases.CanonicalIdsSelectMatchingXpAndBriefingData),
    ("my hero briefing rejects name-only protected identity", TestCases.MyHeroBriefingRejectsNameOnlyProtectedIdentity),
    ("my hero briefing rejects name-only Dungeon Master selection", TestCases.MyHeroBriefingRejectsNameOnlyDungeonMasterSelection),
    ("my hero briefing rejects unauthenticated canonical ID", TestCases.MyHeroBriefingRejectsUnauthenticatedCanonicalId),
    ("my hero briefing does not infer first-name aliases", TestCases.MyHeroBriefingDoesNotInferFirstNameAliases),
    ("my hero briefing ignores stale party display name for note access", TestCases.MyHeroBriefingIgnoresStalePartyDisplayNameForNoteAccess),
    ("my hero briefing uses explicit identity aliases", TestCases.MyHeroBriefingUsesExplicitIdentityAliases),
    ("my hero briefing dungeon master choices carry canonical IDs", TestCases.MyHeroBriefingDungeonMasterChoicesCarryCanonicalIds),
    ("my hero briefing dungeon master selection uses selected identity aliases", TestCases.MyHeroBriefingDungeonMasterSelectionUsesSelectedIdentityAliases),
    ("my hero briefing dungeon master selection uses canonical ID after roster rename", TestCases.MyHeroBriefingDungeonMasterSelectionUsesCanonicalIdAfterRosterRename),
    ("my hero briefing quick links follow resolved identity", TestCases.MyHeroBriefingQuickLinksFollowResolvedIdentity),
    ("first-name-only inputs cannot authenticate or select protected hero", TestCases.FirstNameOnlyInputsCannotAuthenticateOrSelectProtectedHero),
    ("account switching does not retain previous identity", TestCases.AccountSwitchingDoesNotRetainPreviousIdentity),
    ("app configuration validation reports missing url", TestCases.AppConfigurationValidationReportsMissingUrl),
    ("app configuration validation rejects disallowed network host", TestCases.AppConfigurationValidationRejectsDisallowedNetworkHost),
    ("app configuration validation writes repair guidance", TestCases.AppConfigurationValidationWritesRepairGuidance),
    ("app configuration validation suppresses missing rpol credentials before hosted settings failure", TestCases.AppConfigurationValidationSuppressesMissingRpolCredentialsBeforeHostedSettingsFailure),
    ("app configuration validation warns about missing rpol credentials after hosted settings failure", TestCases.AppConfigurationValidationWarnsAboutMissingRpolCredentialsAfterHostedSettingsFailure),
    ("app configuration validation warns about missing sidecars", TestCases.AppConfigurationValidationWarnsAboutMissingSidecars),
    ("app settings loads rpol credentials from local settings sidecar", TestCases.AppSettingsLoadsRpolCredentialsFromLocalSettingsSidecar),
    ("app settings uses local rpol credentials when credential store is unavailable", TestCases.AppSettingsUsesLocalRpolCredentialsWhenCredentialStoreIsUnavailable),
    ("app settings migrate hosted rpol credentials into credential manager", TestCases.AppSettingsMigrateHostedRpolCredentialsIntoCredentialManager),
    ("app configuration validation accepts valid release manifest", TestCases.AppConfigurationValidationAcceptsValidReleaseManifest),
    ("app configuration validation rejects missing manifest file", TestCases.AppConfigurationValidationRejectsMissingManifestFile),
    ("app configuration validation rejects manifest hash mismatch", TestCases.AppConfigurationValidationRejectsManifestHashMismatch),
    ("health argument surfaces release manifest issue", TestCases.HealthArgumentSurfacesReleaseManifestIssue),
    ("startup dependency matrix reports bad config and sidecars", TestCases.StartupDependencyMatrixReportsBadConfigAndSidecars),
    ("startup dependency matrix ignores corrupt optional local settings", TestCases.StartupDependencyMatrixIgnoresCorruptOptionalLocalSettings),
    ("application version metadata matches hardening release", TestCases.ApplicationVersionMetadataMatchesHardeningRelease),
    ("application version argument returns version text", TestCases.ApplicationVersionArgumentReturnsVersionText),
    ("startup manifest status distinguishes skipped and failed", TestCases.StartupManifestStatusDistinguishesSkippedAndFailed),
    ("startup error log entry includes phase and exception", TestCases.StartupErrorLogEntryIncludesPhaseAndException),
    ("last crash diagnostic writes redacted exception details", TestCases.LastCrashDiagnosticWritesRedactedExceptionDetails),
    ("startup health records required phase success", TestCases.StartupHealthRecordsRequiredPhaseSuccess),
    ("startup health writes schema version", TestCases.StartupHealthWritesSchemaVersion),
    ("startup health records required phase failure", TestCases.StartupHealthRecordsRequiredPhaseFailure),
    ("startup health records optional phase failure without throwing", TestCases.StartupHealthRecordsOptionalPhaseFailureWithoutThrowing),
    ("runtime path utility uses system temp for external browser profile", TestCases.RuntimePathUtilityUsesSystemTempForExternalBrowserProfile),
    ("runtime path utility uses user data root for published runtime", TestCases.RuntimePathUtilityUsesUserDataRootForPublishedRuntime),
    ("runtime housekeeping removes stale temp and atomic files", TestCases.RuntimeHousekeepingRemovesStaleTempAndAtomicFiles),
    ("runtime housekeeping preserves fresh and unrelated tmp files", TestCases.RuntimeHousekeepingPreservesFreshAndUnrelatedTmpFiles),
    ("runtime housekeeping removes old quarantined json only", TestCases.RuntimeHousekeepingRemovesOldQuarantinedJsonOnly),
    ("runtime housekeeping removes old backup files only", TestCases.RuntimeHousekeepingRemovesOldBackupFilesOnly),
    ("runtime housekeeping rotates oversized startup log", TestCases.RuntimeHousekeepingRotatesOversizedStartupLog),
    ("runtime housekeeping skips locked files", TestCases.RuntimeHousekeepingSkipsLockedFiles),
    ("ui operation failure reporter logs status and dialog", TestCases.UiOperationFailureReporterLogsStatusAndDialog),
    ("status bar activity indicator tracks async operations", TestCases.StatusBarActivityIndicatorTracksAsyncOperations),
    ("background task supervisor suppresses duplicate phases", TestCases.BackgroundTaskSupervisorSuppressesDuplicatePhases),
    ("background task supervisor logs failures", TestCases.BackgroundTaskSupervisorLogsFailures),
    ("background task supervisor cancels running tasks on dispose", TestCases.BackgroundTaskSupervisorCancelsRunningTasksOnDispose),
    ("atomic file promotion preserves existing destination on locked replacement", TestCases.AtomicFilePromotionPreservesExistingDestinationOnLockedReplacement),
    ("atomic file promotion creates bounded runtime backups", TestCases.AtomicFilePromotionCreatesBoundedRuntimeBackups),
    ("network request retries transient failures", TestCases.NetworkRequestRetriesTransientFailures),
    ("outbound network diagnostics records sanitized success endpoint", TestCases.OutboundNetworkDiagnosticsRecordsSanitizedSuccessEndpoint),
    ("outbound network diagnostics records failure counts", TestCases.OutboundNetworkDiagnosticsRecordsFailureCounts),
    ("network request rejects disallowed host before send", TestCases.NetworkRequestRejectsDisallowedHostBeforeSend),
    ("network request follows allowed redirect at request boundary", TestCases.NetworkRequestFollowsAllowedRedirectAtRequestBoundary),
    ("network request rejects disallowed redirect before send", TestCases.NetworkRequestRejectsDisallowedRedirectBeforeSend),
    ("network request does not retry unauthorized", TestCases.NetworkRequestDoesNotRetryUnauthorized),
    ("network circuit breaker opens after repeated terminal failures", TestCases.NetworkCircuitBreakerOpensAfterRepeatedTerminalFailures),
    ("network circuit breaker clears after success", TestCases.NetworkCircuitBreakerClearsAfterSuccess),
    ("startup dependency matrix classifies terminal network failure", TestCases.StartupDependencyMatrixClassifiesTerminalNetworkFailure),
    ("network request wraps timeout", TestCases.NetworkRequestWrapsTimeout),
    ("network request preserves caller cancellation", TestCases.NetworkRequestPreservesCallerCancellation),
    ("network allowlist rejects credentialed and escaped hosts", TestCases.NetworkAllowlistRejectsCredentialedAndEscapedHosts),
    ("rpol credential submission requires exact trusted https origin and path", TestCases.RpolCredentialSubmissionRequiresExactTrustedHttpsOriginAndPath),
    ("rpol webview navigation requires approved https path", TestCases.RpolWebViewNavigationRequiresApprovedHttpsPath),
    ("rpol webview navigation starting guard cancels untrusted urls", TestCases.RpolWebViewNavigationStartingGuardCancelsUntrustedUrls),
    ("network allowlist accepts obsidian publish content hosts", TestCases.NetworkAllowlistAcceptsObsidianPublishContentHosts),
    ("network allowlist rejects unexpected hosted settings path", TestCases.NetworkAllowlistRejectsUnexpectedHostedSettingsPath),
    ("network allowlist rejects unexpected update path", TestCases.NetworkAllowlistRejectsUnexpectedUpdatePath),
    ("network allowlist generic policy rejects unrelated update host paths", TestCases.NetworkAllowlistGenericPolicyRejectsUnrelatedUpdateHostPaths),
    ("network response limits define defaults", TestCases.NetworkResponseLimitsDefineDefaults),
    ("network response limit rejects oversized html header", TestCases.NetworkResponseLimitRejectsOversizedHtmlHeader),
    ("network response limit rejects oversized markdown stream", TestCases.NetworkResponseLimitRejectsOversizedMarkdownStream),
    ("network response limit rejects oversized json cache stream", TestCases.NetworkResponseLimitRejectsOversizedJsonCacheStream),
    ("network response limit rejects oversized image header", TestCases.NetworkResponseLimitRejectsOversizedImageHeader),
    ("markdown async fetch preserves caller cancellation", TestCases.MarkdownAsyncFetchPreservesCallerCancellation),
    ("runtime artifact loader quarantines malformed json", TestCases.RuntimeArtifactLoaderQuarantinesMalformedJson),
    ("runtime artifact loader restores newest valid backup", TestCases.RuntimeArtifactLoaderRestoresNewestValidBackup),
    ("startup dependency matrix logs locked runtime artifact failures", TestCases.StartupDependencyMatrixLogsLockedRuntimeArtifactFailures),
    ("login info cache load returns empty for malformed json", TestCases.LoginInfoCacheLoadReturnsEmptyForMalformedJson),
    ("asset manifest load returns empty for malformed json", TestCases.AssetManifestLoadReturnsEmptyForMalformedJson),
    ("published asset fallback resolves transclusion without attachment index", TestCases.PublishedAssetFallbackResolvesTransclusionWithoutAttachmentIndex),
    ("hero token filename resolves listing display name", TestCases.HeroTokenFileNameResolvesListingDisplayName),
    ("former pc listing parses three-column hero rows", TestCases.FormerPcListingParsesThreeColumnHeroRows),
    ("active hero listing carries canonical identity", TestCases.ActiveHeroListingCarriesCanonicalIdentity),
    ("active hero markdown cancellation writes no files", TestCases.ActiveHeroMarkdownCancellationWritesNoFiles),
    ("former hero markdown cancellation writes no inactive files", TestCases.FormerHeroMarkdownCancellationWritesNoInactiveFiles),
    ("player character refresh cancellation clears in progress flag", TestCases.PlayerCharacterRefreshCancellationClearsInProgressFlag),
    ("hero image showcase waits for initial player character refresh", TestCases.HeroImageShowcaseWaitsForInitialPlayerCharacterRefresh),
    ("game forum startup cancellation writes no manifests", TestCases.GameForumStartupCancellationWritesNoManifests),
    ("keyword index loader quarantines malformed json", TestCases.KeywordIndexLoaderQuarantinesMalformedJson),
    ("keyword index loader salvages legacy disallowed urls", TestCases.KeywordIndexLoaderSalvagesLegacyDisallowedUrls),
    ("sitemap validation rejects poisoned url", TestCases.SitemapValidationRejectsPoisonedUrl),
    ("sitemap keyword dictionary preserves existing output on rejected url", TestCases.SitemapKeywordDictionaryPreservesExistingOutputOnRejectedUrl),
    ("source integrity records first accepted sitemap", TestCases.SourceIntegrityRecordsFirstAcceptedSitemap),
    ("source integrity rejects collapsed sitemap and preserves output", TestCases.SourceIntegrityRejectsCollapsedSitemapAndPreservesOutput),
    ("source integrity rejects collapsed markdown and preserves output", TestCases.SourceIntegrityRejectsCollapsedMarkdownAndPreservesOutput),
    ("source integrity rejects collapsed keyword index and preserves output", TestCases.SourceIntegrityRejectsCollapsedKeywordIndexAndPreservesOutput),
    ("keyword index validation rejects poisoned url entries", TestCases.KeywordIndexValidationRejectsPoisonedUrlEntries),
    ("keyword index validation rejects poisoned match urls", TestCases.KeywordIndexValidationRejectsPoisonedMatchUrls),
    ("keyword terms release copy generates from keyword index", TestCases.KeywordTermsReleaseCopyGeneratesFromKeywordIndex),
    ("keyword terms publish copy preserves parent release terms", TestCases.KeywordTermsPublishCopyPreservesParentReleaseTerms),
    ("rpol snapshot publisher report requires one attempt", TestCases.RpolSnapshotPublisherReportRequiresOneAttempt),
    ("rpol protected probe rejects response or settled url changes", TestCases.RpolProtectedProbeRejectsResponseOrSettledUrlChanges),
    ("rpol credential submission request guard validates destination method and frame", TestCases.RpolCredentialSubmissionRequestGuardValidatesDestinationMethodAndFrame),
    ("rpol navigation stability observes delayed redirect and dom replacement", TestCases.RpolNavigationStabilityObservesDelayedRedirectAndDomReplacement),
    ("rpol credential submission is behaviorally atomic against event mutation", TestCases.RpolCredentialSubmissionIsBehaviorallyAtomicAgainstEventMutation),
    ("rpol credential guard remains armed until request or bounded failure", TestCases.RpolCredentialGuardRemainsArmedUntilRequestOrBoundedFailure),
    ("rpol credential migration is atomic at credential store boundary", TestCases.RpolCredentialMigrationIsAtomicAtCredentialStoreBoundary),
    ("rpol webview dispatch cancellation falls back when enqueue fails", TestCases.RpolWebViewDispatchCancellationFallsBackWhenEnqueueFails),
    ("rpol protected probe fixture observes referer response and delayed dom", TestCases.RpolProtectedProbeFixtureObservesRefererResponseAndDelayedDom),
    ("rpol protected probe accepts dice roller shell without roll history", TestCases.RpolProtectedProbeAcceptsDiceRollerShellWithoutRollHistory),
    ("rpol publisher equivalent proof uses separate process architecture", TestCases.RpolPublisherEquivalentProofUsesSeparateProcessArchitecture),
    ("rpol separate process normal active loader proof runs", TestCases.RpolSeparateProcessNormalActiveLoaderProofRuns),
    ("rpol candidate promotion preserves active on failure", TestCases.RpolCandidatePromotionPreservesActiveOnFailure),
    ("rpol versioned promotion preserves verified pointer at every fault boundary", TestCases.RpolVersionedPromotionPreservesVerifiedPointerAtEveryFaultBoundary),
    ("rpol versioned promotion requires post-promotion verification", TestCases.RpolVersionedPromotionRequiresPostPromotionVerification),
    ("rpol credential store rollback proof uses normal active loader", TestCases.RpolCredentialStoreRollbackProofUsesNormalActiveLoader),
    ("rpol external browser uses ephemeral port and authenticated endpoint", TestCases.RpolExternalBrowserUsesEphemeralPortAndAuthenticatedEndpoint),
    ("rpol external browser rejects forged or malformed endpoint", TestCases.RpolExternalBrowserRejectsForgedOrMalformedEndpoint),
    ("rpol operation deadline exposes one monotonic budget", TestCases.RpolOperationDeadlineExposesOneMonotonicBudget),
    ("rpol cross-process lock excludes concurrent run", TestCases.RpolCrossProcessLockExcludesConcurrentRun),
    ("rpol result rejects stale or mismatched run", TestCases.RpolResultRejectsStaleOrMismatchedRun),
    ("rpol result rejects unknown discovery and count mismatch", TestCases.RpolResultRejectsUnknownDiscoveryAndCountMismatch),
    ("rpol result accepts wrapper timeout fallback", TestCases.RpolResultAcceptsWrapperTimeoutFallback),
    ("rpol result path rejects traversal and unrelated runtime overwrite", TestCases.RpolResultPathRejectsTraversalAndUnrelatedRuntimeOverwrite),
    ("rpol publisher wrapper contains atomic supervision contract", TestCases.RpolPublisherWrapperContainsAtomicSupervisionContract),
    ("rpol publisher wrapper allows bounded clock skew", TestCases.RpolPublisherWrapperAllowsBoundedClockSkew),
    ("rpol protected probe does not require network idle", TestCases.RpolProtectedProbeDoesNotRequireNetworkIdle),
    ("rpol protected probe uses json dom boundary", TestCases.RpolProtectedProbeUsesJsonDomBoundary),
    ("rpol protected probe retries transient navigation observation", TestCases.RpolProtectedProbeRetriesTransientNavigationObservation),
    ("rpol login form json preserves frame flag", TestCases.RpolLoginFormJsonPreservesFrameFlag),
    ("rpol publisher validate only wrapper uses valid results root", TestCases.RpolPublisherValidateOnlyWrapperUsesValidResultsRoot),
    ("rpol process supervisor kills timed-out process tree", TestCases.RpolProcessSupervisorKillsTimedOutProcessTree),
    ("rpol secure storage state cleanup runs on failure", TestCases.RpolSecureStorageStateCleanupRunsOnFailure),
    ("rpol cleanup continues after failure", TestCases.RpolCleanupContinuesAfterFailure),
    ("rpol operation deadline carries cleanup margin", TestCases.RpolOperationDeadlineCarriesCleanupMargin),
    ("rpol webview profile lease is exclusive and resets", TestCases.RpolWebViewProfileLeaseIsExclusiveAndResets),
    ("rpol webview profile cleanup can retry after cancelled token", TestCases.RpolWebViewProfileCleanupCanRetryAfterCancelledToken),
    ("rpol webview lifetime honors max wait and disposal", TestCases.RpolWebViewLifetimeHonorsMaxWaitAndDisposal),
    ("rpol webview credential script revalidates before submit", TestCases.RpolWebViewCredentialScriptRevalidatesBeforeSubmit),
    ("rpol external profile cleanup uses independent deadline ownership", TestCases.RpolExternalProfileCleanupUsesIndependentDeadlineOwnership),
    ("rpol external profile scavenger skips active locked profiles", TestCases.RpolExternalProfileScavengerSkipsActiveLockedProfiles),
    ("rpol upload recovery faults remain truthful", TestCases.RpolUploadRecoveryFaultsRemainTruthful),
    ("rpol publish recovery reconciles before upload", TestCases.RpolPublishRecoveryReconcilesBeforeUpload),
    ("rpol protected probe rejects public campaign content", TestCases.RpolProtectedProbeRejectsPublicCampaignContent),
    ("rpol protected probe rejects login redirect", TestCases.RpolProtectedProbeRejectsLoginRedirect),
    ("rpol protected probe rejects untrusted uris", TestCases.RpolProtectedProbeRejectsUntrustedUris),
    ("rpol protected probe classifies cloudflare challenge", TestCases.RpolProtectedProbeClassifiesCloudflareChallenge),
    ("rpol protected probe classifies missing response", TestCases.RpolProtectedProbeClassifiesMissingResponse),
    ("rpol protected probe accepts exact dice roller contract", TestCases.RpolProtectedProbeAcceptsExactDiceRollerContract),
    ("rpol protected probe does not treat cookie shape as authentication", TestCases.RpolProtectedProbeDoesNotTreatCookieShapeAsAuthentication),
    ("rpol protected probe rejects dice roller login controls", TestCases.RpolProtectedProbeRejectsDiceRollerLoginControls),
    ("rpol login classifier handles html attribute variants", TestCases.RpolLoginClassifierHandlesHtmlAttributeVariants),
    ("rpol protected probe requires unique dice roller structure", TestCases.RpolProtectedProbeRequiresUniqueDiceRollerStructure),
    ("rpol protected probe requires observed referer and settlement", TestCases.RpolProtectedProbeRequiresObservedRefererAndSettlement),
    ("rpol cross-process lock is reentrant across await and threads", TestCases.RpolCrossProcessLockIsReentrantAcrossAwaitAndThreads),
    ("rpol publisher refresh carries lock ownership", TestCases.RpolPublisherRefreshCarriesLockOwnership),
    ("rpol initial and stale discovery refresh auth under owned publisher lock", TestCases.RpolInitialAndStaleDiscoveryRefreshAuthUnderOwnedPublisherLock),
    ("rpol publisher entry points share one cross-process lock", TestCases.RpolPublisherEntryPointsShareOneCrossProcessLock),
    ("rpol cross-process lock async acquire release is standalone and concurrent", TestCases.RpolCrossProcessLockAsyncAcquireReleaseIsStandaloneAndConcurrent),
    ("rpol auth detects login page fallback", TestCases.RpolAuthDetectsLoginPageFallback),
    ("rpol auth distinguishes blocked and remote failures", TestCases.RpolAuthDistinguishesBlockedAndRemoteFailures),
    ("rpol auth prefers installed browsers before playwright chromium", TestCases.RpolAuthPrefersInstalledBrowsersBeforePlaywrightChromium),
    ("rpol auth enforces browser tls validation", TestCases.RpolAuthEnforcesBrowserTlsValidation),
    ("rpol auth classifies transport security failures", TestCases.RpolAuthClassifiesTransportSecurityFailures),
    ("rpol auth retries initial login rejection with headed browser", TestCases.RpolAuthRetriesInitialLoginRejectionWithHeadedBrowser),
    ("rpol auth awaits manual persistent headed login page", TestCases.RpolAuthAwaitsManualPersistentHeadedLoginPage),
    ("rpol auth classifies embedded login form by campaign content", TestCases.RpolAuthClassifiesEmbeddedLoginFormByCampaignContent),
    ("rpol auth cached failure short circuits html fetch", TestCases.RpolAuthCachedFailureShortCircuitsHtmlFetch),
    ("rpol auth cached failure logs once", TestCases.RpolAuthCachedFailureLogsOnce),
    ("rpol snapshot signs and verifies canonical payload", TestCases.RpolSnapshotSignsAndVerifiesCanonicalPayload),
    ("rpol snapshot freshness detects possibly stale payloads", TestCases.RpolSnapshotFreshnessDetectsPossiblyStalePayloads),
    ("rpol snapshot preparation rejects login page before sanitizing", TestCases.RpolSnapshotPreparationRejectsLoginPageBeforeSanitizing),
    ("rpol snapshot preparation accepts campaign content with embedded login form", TestCases.RpolSnapshotPreparationAcceptsCampaignContentWithEmbeddedLoginForm),
    ("rpol snapshot preparation rejects disguised login page", TestCases.RpolSnapshotPreparationRejectsDisguisedLoginPage),
    ("rpol snapshot preparation accepts campaign posts quoting challenge text", TestCases.RpolSnapshotPreparationAcceptsCampaignPostsQuotingChallengeText),
    ("rpol snapshot probe failure requires refresh", TestCases.RpolSnapshotProbeFailureRequiresRefresh),
    ("rpol snapshot publisher preserves caller cancellation", TestCases.RpolSnapshotPublisherPreservesCallerCancellation),
    ("snapshot discovery merge prioritizes new target and preserves normalized queue", TestCases.SnapshotDiscoveryMergePrioritizesNewTargetAndPreservesNormalizedQueue),
    ("snapshot discovery allows embedded login form on campaign root", TestCases.SnapshotDiscoveryAllowsEmbeddedLoginFormOnCampaignRoot),
    ("snapshot broker unavailable falls back to direct rpol", TestCases.SnapshotBrokerUnavailableFallsBackToDirectRpol),
    ("game forum startup checks snapshots before downloads", TestCases.GameForumStartupChecksSnapshotsBeforeDownloads),
    ("rpol snapshot rejects another game", TestCases.RpolSnapshotRejectsAnotherGame),
    ("rpol snapshot sanitizes credentials and login form", TestCases.RpolSnapshotSanitizesCredentialsAndLoginForm),
    ("rpol snapshot accepts sanitized campaign content", TestCases.RpolSnapshotAcceptsSanitizedCampaignContent),
    ("rpol snapshot rejects login-only content", TestCases.RpolSnapshotRejectsLoginOnlyContent),
    ("rpol challenge detection ignores passive cloudflare references", TestCases.RpolChallengeDetectionIgnoresPassiveCloudflareReferences),
    ("rpol protected probe handles dynamic login fixture", TestCases.RpolProtectedProbeHandlesDynamicLoginFixture),
    ("rpol verification recognizes authenticated browser title", TestCases.RpolVerificationRecognizesAuthenticatedBrowserTitle),
    ("rpol verification browser starts with cdp enabled", TestCases.RpolVerificationBrowserStartsWithCdpEnabled),
    ("rpol credential entry uri requires exact trusted origin and path", TestCases.RpolCredentialEntryUriRequiresExactTrustedOriginAndPath),
    ("rpol verification navigation requires trusted https rpol path", TestCases.RpolVerificationNavigationRequiresTrustedHttpsRpolPath),
    ("rpol webview credential flow guards navigation and submission", TestCases.RpolWebViewCredentialFlowGuardsNavigationAndSubmission),
    ("rpol verification connects over cdp before inspecting page state", TestCases.RpolVerificationConnectsOverCdpBeforeInspectingPageState),
    ("rpol webview state replays in headed browser", TestCases.RpolWebViewStateReplaysInHeadedBrowser),
    ("rpol snapshot upload json uses broker canonical escaping", TestCases.RpolSnapshotUploadJsonUsesBrokerCanonicalEscaping),
    ("rpol dice roller navigation uses game page referrer", TestCases.RpolDiceRollerNavigationUsesGamePageReferrer),
    ("snapshot publisher state advances one target and wraps", TestCases.SnapshotPublisherStateAdvancesOneTargetAndWraps),
    ("snapshot discovery approves game links and dice roller", TestCases.SnapshotDiscoveryApprovesGameLinksAndDiceRoller),
    ("snapshot publisher normalizes thread targets to show all", TestCases.SnapshotPublisherNormalizesThreadTargetsToShowAll),
    ("snapshot publisher state injects required dice roller target", TestCases.SnapshotPublisherStateInjectsRequiredDiceRollerTarget),
    ("snapshot publisher state persists its cursor", TestCases.SnapshotPublisherStatePersistsItsCursor),
    ("snapshot publisher state rejects an invalid cursor", TestCases.SnapshotPublisherStateRejectsInvalidCursor),
    ("network allowlist accepts only broker api path", TestCases.NetworkAllowlistAcceptsOnlyBrokerApiPath),
    ("snapshot publisher argument is recognized", TestCases.SnapshotPublisherArgumentIsRecognized),
    ("rpol auth caches blocked and expired session failures", TestCases.RpolAuthCachesBlockedAndExpiredSessionFailures),
    ("rpol storage state validation accepts current rpol cookies", TestCases.RpolStorageStateValidationAcceptsCurrentRpolCookies),
    ("rpol storage state validation deletes malformed state", TestCases.RpolStorageStateValidationDeletesMalformedState),
    ("rpol storage state validation deletes stale state", TestCases.RpolStorageStateValidationDeletesStaleState),
    ("rpol storage state validation deletes non-rpol state", TestCases.RpolStorageStateValidationDeletesNonRpolState),
    ("show-all thread url preserves base query and adds show all", TestCases.ShowAllThreadUrlPreservesBaseQueryAndAddsShowAll),
    ("chapter downloads use show-all thread urls", TestCases.ChapterDownloadsUseShowAllThreadUrls),
    ("house rules download uses show-all thread url", TestCases.HouseRulesDownloadUsesShowAllThreadUrl),
    ("aside downloads use show-all urls and refresh existing files", TestCases.AsideDownloadsUseShowAllUrlsAndRefreshExistingFiles),
    ("rpol thread export preserves existing output on cancellation", TestCases.RpolThreadExportPreservesExistingOutputOnCancellation),
    ("rpol thread export commits staged output", TestCases.RpolThreadExportCommitsStagedOutput),
    ("rpol thread export rejects collapsed source and preserves existing output", TestCases.RpolThreadExportRejectsCollapsedSourceAndPreservesExistingOutput),
    ("die roll extraction keeps only saved-log lines", TestCases.DieRollExtractionKeepsOnlySavedLogLines),
    ("die roll extraction handles live rpol paragraph markup", TestCases.DieRollExtractionHandlesLiveRpolParagraphMarkup),
    ("die roll extraction derives stable ids when rpol omits roll ids", TestCases.DieRollExtractionDerivesStableIdsWhenRpolOmitsRollIds),
    ("die roll sync appends only unsaved rolls", TestCases.DieRollSyncAppendsOnlyUnsavedRolls),
    ("regional map downloads when missing", TestCases.RegionalMapDownloadsWhenMissing),
    ("regional map uses hosted maps url", TestCases.RegionalMapUsesHostedMapsUrl),
    ("regional map downloads when older than one hour", TestCases.RegionalMapDownloadsWhenOlderThanOneHour),
    ("regional map skips when newer than one hour", TestCases.RegionalMapSkipsWhenNewerThanOneHour),
    ("regional map downloads when newer but transparent", TestCases.RegionalMapDownloadsWhenNewerButTransparent),
    ("startup status includes download count and size", TestCases.StartupStatusIncludesDownloadCountAndSize),
    ("adventure outline builds from saved IC html", TestCases.AdventureOutlineBuildsFromSavedIcHtml),
    ("adventure outline fills every chapter through latest IC chapter", TestCases.AdventureOutlineFillsEveryChapterThroughLatestIcChapter),
    ("adventure outline parses rpol linked author exports", TestCases.AdventureOutlineParsesRpolLinkedAuthorExports),
    ("adventure outline summarizes table roles concisely", TestCases.AdventureOutlineSummarizesTableRolesConcisely),
    ("adventure outline skips empty bullet marker posts", TestCases.AdventureOutlineSkipsEmptyBulletMarkerPosts),
    ("adventure outline rejects weak generated summaries", TestCases.AdventureOutlineRejectsWeakGeneratedSummaries),
    ("adventure outline fallback summaries preserve scene specifics", TestCases.AdventureOutlineFallbackSummariesPreserveSceneSpecifics),
    ("adventure outline merges new saved IC bullets", TestCases.AdventureOutlineMergesNewSavedIcBullets),
    ("adventure outline falls back to Obsidian markdown", TestCases.AdventureOutlineFallsBackToObsidianMarkdown),
    ("adventure outline prefers saved IC html over fallback", TestCases.AdventureOutlinePrefersSavedIcHtmlOverFallback),
    ("adventure outline ignores failed fallback markdown fetch", TestCases.AdventureOutlineIgnoresFailedFallbackMarkdownFetch),
    ("adjusted post tallies aggregate saved IC html", TestCases.AdjustedPostTalliesAggregateSavedIcHtml),
    ("keyword search falls back to The-prefixed term", TestCases.KeywordSearchFallsBackToThePrefixedTerm),
    ("keyword search keeps quoted phrases together", TestCases.KeywordSearchKeepsQuotedPhrasesTogether),
    ("keyword search accepts url source metadata", TestCases.KeywordSearchAcceptsUrlSourceMetadata),
    ("keyword search filters rpol hero metadata-only hits", TestCases.KeywordSearchFiltersRpolHeroMetadataOnlyHits),
    ("show menu contains xp item", TestCases.ShowMenuContainsXpItem),
    ("show menu contains my hero briefing item", TestCases.ShowMenuContainsMyHeroBriefingItem),
    ("show menu contains adventure outline item", TestCases.ShowMenuContainsAdventureOutlineItem),
    ("show menu contains translator item", TestCases.ShowMenuContainsTranslatorItem),
    ("elven translator prefers Sindarin and falls back to Quenya", TestCases.ElvenTranslatorPrefersSindarinAndFallsBackToQuenya),
    ("elven translator preserves text and punctuation", TestCases.ElvenTranslatorPreservesTextAndPunctuation),
    ("elven translator finalizes every English term", TestCases.ElvenTranslatorFinalizesEveryEnglishTerm),
    ("ghukliak translator loads source and complete coverage", TestCases.GhukliakTranslatorLoadsSourceAndCompleteCoverage),
    ("ghukliak translator preserves text and punctuation", TestCases.GhukliakTranslatorPreservesTextAndPunctuation),
    ("ghukliak complete coverage translates every Orcish English term", TestCases.GhukliakCompleteCoverageTranslatesEveryOrcishTerm),
    ("elven morphology derives conservative noun and active verb forms", TestCases.ElvenMorphologyDerivesConservativeForms),
    ("elven first iteration loads generated translations", TestCases.ElvenFirstIterationLoadsGeneratedTranslations),
    ("elven second iteration loads five thousand generated translations", TestCases.ElvenSecondIterationLoadsGeneratedTranslations),
    ("elven complete coverage translates every Orcish English term", TestCases.ElvenCompleteCoverageTranslatesEveryOrcishTerm),
    ("elven lexicon validator accepts reviewed rooted additions", TestCases.ElvenLexiconValidatorAcceptsReviewedRootedAdditions),
    ("elven lexicon validator rejects unsupported additions", TestCases.ElvenLexiconValidatorRejectsUnsupportedAdditions),
    ("elven lexicon validator preserves Sindarin preference", TestCases.ElvenLexiconValidatorPreservesSindarinPreference),
    ("translator controller cancels superseded injected service work", TestCases.TranslatorControllerCancelsSupersededInjectedServiceWork),
    ("translator view toggles direction without web links", TestCases.TranslatorViewTogglesDirectionWithoutWebLinks),
    ("translator view supports Elven mode", TestCases.TranslatorViewSupportsElvenMode),
    ("translator view supports Ghukliak mode", TestCases.TranslatorViewSupportsGhukliakMode),
    ("translator view translates while input changes", TestCases.TranslatorViewTranslatesWhileInputChanges),
    ("translator view exports english to orcish translation", TestCases.TranslatorViewExportsEnglishToOrcishTranslation),
    ("translator view exports english to elvish translation", TestCases.TranslatorViewExportsEnglishToElvishTranslation),

    ("adventure outline view displays generated markdown", TestCases.AdventureOutlineViewDisplaysGeneratedMarkdown),
    ("about menu contains author and update items", TestCases.AboutMenuContainsAuthorAndUpdateItems),
    ("file menu contains count words and take snapshots item", TestCases.FileMenuContainsCountWordsAndTakeSnapshotsItem),
    ("count words and take snapshots rejects invalid dungeon master password", TestCases.CountWordsAndTakeSnapshotsRejectsInvalidDungeonMasterPassword),
    ("count words and take snapshots launches both publisher tasks", TestCases.CountWordsAndTakeSnapshotsLaunchesBothPublisherTasks),
    ("scheduled task launcher uses native schtasks arguments", TestCases.ScheduledTaskLauncherUsesNativeSchtasksArguments),
    ("scheduled task launcher rejects pre-canceled request before process creation", TestCases.ScheduledTaskLauncherRejectsPreCanceledRequestBeforeProcessCreation),
    ("scheduled task launcher cancellation terminates process", TestCases.ScheduledTaskLauncherCancellationTerminatesProcess),
    ("count words and take snapshots attempts both tasks after one failure", TestCases.CountWordsAndTakeSnapshotsAttemptsBothTasksAfterOneFailure),
    ("form closure cancels manual publisher launch", TestCases.FormClosureCancelsManualPublisherLaunch),
    ("count words and take snapshots preserves caller cancellation", TestCases.CountWordsAndTakeSnapshotsPreservesCallerCancellation),
    ("manual publisher failure reporting skips ui after closure", TestCases.ManualPublisherFailureReportingSkipsUiAfterClosure),
    ("about author text lists developer info", TestCases.AboutAuthorTextListsDeveloperInfo),
    ("about version text shows app version", TestCases.AboutVersionTextShowsAppVersion),
    ("update check verifies signed p-assist manifest", TestCases.UpdateCheckVerifiesSignedPAssistManifest),
    ("update check accepts manifest signature made before trailing newline", TestCases.UpdateCheckAcceptsManifestSignatureMadeBeforeTrailingNewline),
    ("update check chooses newest signed manifest entry", TestCases.UpdateCheckChoosesNewestSignedManifestEntry),
    ("update check rejects tampered signed manifest", TestCases.UpdateCheckRejectsTamperedSignedManifest),
    ("update check rejects retired manifest signing key", TestCases.UpdateCheckRejectsRetiredManifestSigningKey),
    ("update check compares against current app version", TestCases.UpdateCheckComparesAgainstCurrentAppVersion),
    ("update check reports latest version message", TestCases.UpdateCheckReportsLatestVersionMessage),
    ("update check fetches signed manifest from allowed update host", TestCases.UpdateCheckFetchesSignedManifestFromAllowedUpdateHost),
    ("update check remembers highest trusted version observed", TestCases.UpdateCheckRemembersHighestTrustedVersionObserved),
    ("legacy trusted update state migrates to protected format", TestCases.LegacyTrustedUpdateStateMigratesToProtectedFormat),
    ("trusted update state is encrypted at rest", TestCases.TrustedUpdateStateIsEncryptedAtRest),
    ("trusted update state rejects tampered payload", TestCases.TrustedUpdateStateRejectsTamperedPayload),
    ("update check rejects signed manifest rollback below trusted version floor", TestCases.UpdateCheckRejectsSignedManifestRollbackBelowTrustedVersionFloor),
    ("update host certificate pinning accepts trusted leaf pin", TestCases.UpdateHostCertificatePinningAcceptsTrustedLeafPin),
    ("update host certificate pinning accepts trusted intermediate pin", TestCases.UpdateHostCertificatePinningAcceptsTrustedIntermediatePin),
    ("update host certificate pinning supports rotation window", TestCases.UpdateHostCertificatePinningSupportsRotationWindow),
    ("update host certificate pinning rejects retired pin", TestCases.UpdateHostCertificatePinningRejectsRetiredPin),
    ("update host certificate pinning rejects mismatched pin", TestCases.UpdateHostCertificatePinningRejectsMismatchedPin),
    ("update host certificate validation allows trusted tls with pin mismatch", TestCases.UpdateHostCertificateValidationAllowsTrustedTlsWithPinMismatch),
    ("certificate validation skips pin extraction for non update hosts", TestCases.CertificateValidationSkipsPinExtractionForNonUpdateHosts),
    ("verified updater downloads installer to controlled path", TestCases.VerifiedUpdaterDownloadsInstallerToControlledPath),
    ("verified updater honors cancellation before mutation", TestCases.VerifiedUpdaterHonorsCancellationBeforeMutation),
    ("verified updater rejects installer sha256 mismatch", TestCases.VerifiedUpdaterRejectsInstallerSha256Mismatch),
    ("verified updater rejects installer signer mismatch", TestCases.VerifiedUpdaterRejectsInstallerSignerMismatch),
    ("verified installer launch re-verifies before execution", TestCases.VerifiedInstallerLaunchReverifiesBeforeExecution),
    ("verified installer launch rejects signer changes after verification", TestCases.VerifiedInstallerLaunchRejectsSignerChangesAfterVerification),
    ("verified installer launch rejects elevation changes after verification", TestCases.VerifiedInstallerLaunchRejectsElevationChangesAfterVerification),
    ("verified installer launch honors cancellation before execution", TestCases.VerifiedInstallerLaunchHonorsCancellationBeforeExecution),
    ("search enter triggers click when enabled", TestCases.SearchEnterTriggersClickWhenEnabled),
    ("keyword search uppercases encrypted index results without changing launch URL", TestCases.KeywordSearchUppercasesEncryptedIndexResultsWithoutChangingLaunchUrl),
    ("keyword search uppercases online Obsidian fallback results", TestCases.KeywordSearchUppercasesOnlineObsidianFallbackResults),
    ("keyword search backfills online hits into keyword index", TestCases.KeywordSearchBackfillsOnlineHitsIntoKeywordIndex),
    ("keyword search offers online fallback on local miss", TestCases.KeywordSearchOffersOnlineFallbackOnLocalMiss),
    ("keyword search cancels previous online fallback", TestCases.KeywordSearchCancelsPreviousOnlineFallback),
    ("keyword search rpol scope excludes obsidian-only whiteheart", TestCases.KeywordSearchRpolScopeExcludesObsidianOnlyWhiteheart),
    ("keyword search rpol scope excludes obsidian-only whiteheart stiffwhiskers", TestCases.KeywordSearchRpolScopeExcludesObsidianOnlyWhiteheartStiffwhiskers),
    ("keyword search expands hero first and full names", TestCases.KeywordSearchExpandsHeroFirstAndFullNames),
    ("my hero briefing builds selected hero summary boundary", TestCases.MyHeroBriefingBuildsSelectedHeroSummaryBoundary),
    ("my hero briefing prefers authenticated hero identity", TestCases.MyHeroBriefingPrefersAuthenticatedHeroIdentity),
    ("my hero briefing requires explicit dungeon master hero selection", TestCases.MyHeroBriefingRequiresExplicitDungeonMasterHeroSelection),
    ("my hero briefing leaves ambiguous first name unresolved", TestCases.MyHeroBriefingLeavesAmbiguousFirstNameUnresolved),
    ("my hero briefing rejects unauthenticated selected hero", TestCases.MyHeroBriefingRejectsUnauthenticatedSelectedHero),
    ("my hero briefing picker returns canonical ID", TestCases.MyHeroBriefingPickerReturnsCanonicalId),
    ("my hero briefing builds recent hero activity", TestCases.MyHeroBriefingBuildsRecentHeroActivity),
    ("my hero briefing builds likely open response items", TestCases.MyHeroBriefingBuildsLikelyOpenResponseItems),
    ("my hero briefing surfaces relevant unlocked notes", TestCases.MyHeroBriefingSurfacesRelevantUnlockedNotes),
    ("my hero briefing requests hero selection when no hero selected", TestCases.MyHeroBriefingRequestsHeroSelectionWhenNoHeroSelected),
    ("my hero briefing display text includes focused sections", TestCases.MyHeroBriefingDisplayTextIncludesFocusedSections),
    ("my hero briefing styles likely response key", TestCases.MyHeroBriefingStylesLikelyResponseKey),
    ("my hero briefing loads cached thread posts from runtime artifacts", TestCases.MyHeroBriefingLoadsCachedThreadPostsFromRuntimeArtifacts),
    ("my hero briefing loads flat cached thread files from runtime artifacts", TestCases.MyHeroBriefingLoadsFlatCachedThreadFilesFromRuntimeArtifacts),
    ("my hero briefing encrypted index loader tolerates malformed json", TestCases.MyHeroBriefingEncryptedIndexLoaderToleratesMalformedJson),
    ("party hero sheet parser reads summary and hides xp lines", TestCases.PartyHeroSheetParserReadsSummaryAndHidesXpLines),
    ("party hero listing summary overrides stale cached sheet", TestCases.PartyHeroListingSummaryOverridesStaleCachedSheet),
    ("party hero xp visibility follows authenticated character", TestCases.PartyHeroXpVisibilityFollowsAuthenticatedCharacter),
    ("party hero legacy file rejects different full name", TestCases.PartyHeroLegacyFileRejectsDifferentFullName),
    ("party hero xp visibility requires unique canonical identity", TestCases.PartyHeroXpVisibilityRequiresUniqueCanonicalIdentity),
    ("tagged note cipher decrypts for matching level tag", TestCases.TaggedNoteCipherDecryptsForMatchingLevelTag),
    ("tagged note cipher decrypts for matching character tag", TestCases.TaggedNoteCipherDecryptsForMatchingCharacterTag),
    ("tagged note cipher rejects inferred first-name alias", TestCases.TaggedNoteCipherRejectsInferredFirstNameAlias),
    ("tagged note cipher rejects unmet class tag", TestCases.TaggedNoteCipherRejectsUnmetClassTag),
    ("tagged note cipher accepts either-or ability tag", TestCases.TaggedNoteCipherAcceptsEitherOrAbilityTag),
    ("tagged note cipher accepts bare class alternative", TestCases.TaggedNoteCipherAcceptsBareClassAlternative),
    ("tagged note cipher accepts class level shorthand and faction tag", TestCases.TaggedNoteCipherAcceptsClassLevelShorthandAndFactionTag),
    ("tagged note cipher accepts grouped and expression tag", TestCases.TaggedNoteCipherAcceptsGroupedAndExpressionTag),
    ("tagged note cipher reports mismatched decrypt tags", TestCases.TaggedNoteCipherReportsMismatchedDecryptTags),
    ("tagged note cipher reports encrypted markdown block counts", TestCases.TaggedNoteCipherReportsEncryptedMarkdownBlockCounts),
    ("tagged note cipher indexes encrypted markdown frontmatter tags", TestCases.TaggedNoteCipherIndexesEncryptedMarkdownFrontmatterTags),
    ("tagged note cipher authenticates visible tags", TestCases.TaggedNoteCipherAuthenticatesVisibleTags),
    ("xp identity lookup rejects duplicate canonical names", TestCases.XpIdentityLookupRejectsDuplicateCanonicalNames),
    ("xp display stores multiple totals for dungeon master", TestCases.XpDisplayStoresMultipleTotalsForDungeonMaster),
    ("xp tracking parser reads latest table totals", TestCases.XpTrackingParserReadsLatestTableTotals),
    ("xp tracking parser rejects missing latest table", TestCases.XpTrackingParserRejectsMissingLatestTable),
    ("xp tracking parser rejects missing or duplicate canonical IDs", TestCases.XpTrackingParserRejectsMissingOrDuplicateCanonicalIds),
    ("xp tracking failure message hides url and directs players to dm", TestCases.XpTrackingFailureMessageHidesUrlAndDirectsPlayersToDm),
    ("xp tracking missing pc message directs players to dm", TestCases.XpTrackingMissingPcMessageDirectsPlayersToDm),
    ("illusionist progression data exposes XP thresholds", TestCases.IllusionistProgressionDataExposesXpThresholds),
    ("show menu contains party item", TestCases.ShowMenuContainsPartyItem),
    ("show menu contains former pcs item", TestCases.ShowMenuContainsFormerPcsItem),
    ("former pcs view displays token name and class", TestCases.FormerPcsViewDisplaysTokenNameAndClass),
    ("external url launch policy accepts https and rejects http", TestCases.ExternalUrlLaunchPolicyAcceptsHttpsAndRejectsHttp),
    ("external url launch policy rejects unsafe inputs", TestCases.ExternalUrlLaunchPolicyRejectsUnsafeInputs),
    ("hero image paths follow listing markdown table", TestCases.HeroImagePathsFollowListingMarkdownTable),
    ("hero asset paths reject escaped targets", TestCases.HeroAssetPathsRejectEscapedTargets),
    ("legacy local settings migrate to scoped encryption", TestCases.LegacyLocalSettingsMigrateToPortableEncryption),
    ("v1 local settings migrate to authenticated encryption", TestCases.V1LocalSettingsMigrateToAuthenticatedEncryption),
    ("v2 local settings migrate to scoped encryption", TestCases.V2LocalSettingsMigrateToScopedEncryption),
    ("local settings are encrypted on load", TestCases.LocalSettingsAreEncryptedOnLoad),
    ("portable local settings omit RPOL credentials", TestCases.PortableLocalSettingsOmitRpolCredentials),
    ("portable encrypted settings byte loader clears source buffer", TestCases.PortableEncryptedSettingsByteLoaderClearsSourceBuffer),
    ("credential manager utf8 helpers clear transient buffers", TestCases.CredentialManagerUtf8HelpersClearTransientBuffers),
    ("local settings encrypt command writes portable envelope", TestCases.LocalSettingsEncryptCommandWritesPortableEnvelope),
    ("portable settings never carry rpol credentials", TestCases.PortableSettingsNeverCarryRpolCredentials),
    ("local settings decrypt command writes plaintext json", TestCases.LocalSettingsDecryptCommandWritesPlaintextJson),
    ("local settings rejects future schema version", TestCases.LocalSettingsRejectsFutureSchemaVersion),
    ("current-user local settings copied fixture round-trips", TestCases.CurrentUserLocalSettingsCopiedFixtureRoundTrips),
    ("authenticated local settings reject tampered payload", TestCases.AuthenticatedLocalSettingsRejectTamperedPayload),
    ("local settings restores newest valid backup", TestCases.LocalSettingsRestoresNewestValidBackup),
    ("runtime path utility rejects escaped paths", TestCases.RuntimePathUtilityRejectsEscapedPaths),
    ("health argument returns startup health summary", TestCases.HealthArgumentReturnsStartupHealthSummary),
    ("publish verification accepts current output", TestCases.PublishVerificationAcceptsCurrentOutput),
    ("publish verification rejects stale startup log", TestCases.PublishVerificationRejectsStaleStartupLog),
    ("publish verification rejects startup health artifact", TestCases.PublishVerificationRejectsStartupHealthArtifact),
    ("publish verification rejects outbound network diagnostics artifact", TestCases.PublishVerificationRejectsOutboundNetworkDiagnosticsArtifact),
    ("publish verification rejects last crash artifact", TestCases.PublishVerificationRejectsLastCrashArtifact),
    ("publish verification rejects malformed settings json", TestCases.PublishVerificationRejectsMalformedSettingsJson),
    ("publish verification rejects future settings schema", TestCases.PublishVerificationRejectsFutureSettingsSchema),
    ("publish verification accepts encrypted rpol local settings sidecar", TestCases.PublishVerificationAcceptsEncryptedRpolLocalSettingsSidecar),
    ("publish verification rejects plaintext rpol local settings sidecar", TestCases.PublishVerificationRejectsPlaintextRpolLocalSettingsSidecar),
    ("publish verification accepts missing hosted local settings url", TestCases.PublishVerificationAcceptsMissingHostedLocalSettingsUrl),
    ("publish verification rejects missing xp password sidecar", TestCases.PublishVerificationRejectsMissingXpPasswordSidecar),
    ("publish verification rejects plaintext xp password sidecar", TestCases.PublishVerificationRejectsPlaintextXpPasswordSidecar),
    ("publish verification rejects malformed canonical ID", TestCases.PublishVerificationRejectsMalformedCanonicalId),
    ("publish verification rejects malformed keyword index", TestCases.PublishVerificationRejectsMalformedKeywordIndex),
    ("publish verification rejects malformed sitemap", TestCases.PublishVerificationRejectsMalformedSitemap),
    ("publish verification rejects incomplete playwright runtime", TestCases.PublishVerificationRejectsIncompletePlaywrightRuntime),
    ("publish verification rejects mismatched executable version", TestCases.PublishVerificationRejectsMismatchedExecutableVersion),
    ("publish verification rejects stale release manifest", TestCases.PublishVerificationRejectsStaleReleaseManifest),
    ("publish verification rejects malformed runtime inventory", TestCases.PublishVerificationRejectsMalformedRuntimeInventory),
    ("publish verification rejects malformed release provenance", TestCases.PublishVerificationRejectsMalformedReleaseProvenance),
    ("publish verification rejects unsigned executable when signing required", TestCases.PublishVerificationRejectsUnsignedExecutableWhenSigningRequired),
    ("installer scripts target program files install path", TestCases.InstallerScriptsTargetProgramFilesInstallPath),
    ("installer protects installed application tree", TestCases.InstallerProtectsInstalledApplicationTree),
    ("installer package verification accepts current package", TestCases.InstallerPackageVerificationAcceptsCurrentPackage),
    ("installer package verification rejects unsigned payload when signing required", TestCases.InstallerPackageVerificationRejectsUnsignedPayloadWhenSigningRequired),
    ("release update artifact verification accepts generated signed manifest", TestCases.ReleaseUpdateArtifactVerificationAcceptsGeneratedSignedManifest),
    ("release update artifact verification rejects manifest hash mismatch", TestCases.ReleaseUpdateArtifactVerificationRejectsManifestHashMismatch),
    ("hardening workflow builds and uploads signed release update artifacts", TestCases.HardeningWorkflowBuildsAndUploadsSignedReleaseUpdateArtifacts),
    ("published health verification accepts current output", TestCases.PublishedHealthVerificationAcceptsCurrentOutput),
    ("secret scan accepts current repository", TestCases.SecretScanAcceptsCurrentRepository),
    ("secret scan rejects tracked env secret", TestCases.SecretScanRejectsTrackedEnvSecret),
    ("secret scan rejects deleted secret in quoted path", TestCases.SecretScanRejectsDeletedSecretInQuotedPath),
    ("secret scan rejects forbidden path unique to merge results", TestCases.SecretScanRejectsForbiddenPathUniqueToMergeResults),
    ("release publish parity accepts current output", TestCases.ReleasePublishParityAcceptsCurrentOutput),
    ("release publish parity rejects mismatched sidecar", TestCases.ReleasePublishParityRejectsMismatchedSidecar),
    ("diagnostic bundle redacts sensitive values", TestCases.DiagnosticBundleRedactsSensitiveValues),
    ("diagnostic bundle verify only rejects forbidden auth state", TestCases.DiagnosticBundleVerifyOnlyRejectsForbiddenAuthState),
    ("diagnostic retention cleanup removes old diagnostics and preserves unrelated scratch files", TestCases.DiagnosticRetentionCleanupRemovesOldDiagnosticsAndPreservesUnrelatedScratchFiles)
        };
}
